const unit389Quizzes = [
  // Quiz 1: Définitions de base
  [
    { question: "Que signifie 'l'inflation' ?", options: ["La baisse des prix", "La hausse généralisée des prix", "L'augmentation des salaires", "La création de monnaie"], answer: "La hausse généralisée des prix" },
    { question: "Qu'est-ce que le PIB ?", options: ["Le Poids Intérieur Brut", "Le Produit Intérieur Brut", "Le Profit Industriel Brut", "Le Placement Intérieur Brut"], answer: "Le Produit Intérieur Brut" },
    { question: "Que signifie 'le chômage' ?", options: ["Le manque de travail", "Le manque d'argent", "Le manque de vacances", "Le manque de sommeil"], answer: "Le manque de travail" },
    { question: "Qu'est-ce qu'une 'entreprise' ?", options: ["Un lieu de vacances", "Une organisation qui produit des biens ou services", "Un stade de sport", "Un type de taxe"], answer: "Une organisation qui produit des biens ou services" },
    { question: "Que signifie 'investir' ?", options: ["Dépenser de l'argent inutilement", "Placer de l'argent pour obtenir un profit futur", "Économiser tout son argent", "Donner de l'argent à une association"], answer: "Placer de l'argent pour obtenir un profit futur" },
    { question: "Qu'est-ce que 'le marché' en économie ?", options: ["Un lieu pour acheter des légumes", "Le lieu de rencontre entre l'offre et la demande", "Le siège d'une banque", "Un type de monnaie"], answer: "Le lieu de rencontre entre l'offre et la demande" },
    { question: "Que signifie 'le profit' ?", options: ["La perte d'argent", "Le bénéfice réalisé par une entreprise", "Le montant des impôts", "Le salaire d'un employé"], answer: "Le bénéfice réalisé par une entreprise" },
    { question: "Qu'est-ce qu'un 'impôt' ?", options: ["Un cadeau de l'État", "Une contribution obligatoire aux charges publiques", "Un prêt de la banque", "Un type d'investissement"], answer: "Une contribution obligatoire aux charges publiques" },
    { question: "Que signifie 'la dette' ?", options: ["L'argent que l'on possède", "L'argent que l'on doit à quelqu'un", "L'argent que l'on gagne", "L'argent que l'on cache"], answer: "L'argent que l'on doit à quelqu'un" },
    { question: "Qu'est-ce que 'la monnaie' ?", options: ["Un type de papier", "L'unité de mesure de la valeur et instrument d'échange", "Un objet de collection", "Un synonyme de richesse"], answer: "L'unité de mesure de la valeur et instrument d'échange" },
    { question: "Que signifie 'la croissance' ?", options: ["La diminution de la richesse", "L'augmentation de la production de richesse", "Le vieillissement de la population", "La hausse du chômage"], answer: "L'augmentation de la production de richesse" },
    { question: "Qu'est-ce qu'un 'salarié' ?", options: ["Une personne qui travaille gratuitement", "Une personne qui reçoit un salaire en échange de son travail", "Un patron d'entreprise", "Un actionnaire en bourse"], answer: "Une person qui reçoit un salaire en échange de son travail" },
    { question: "Que signifie 'la consommation' ?", options: ["La production de biens", "L'utilisation de biens et services pour satisfaire des besoins", "L'épargne d'argent", "L'exportation de produits"], answer: "L'utilisation de biens et services pour satisfaire des besoins" },
    { question: "Qu'est-ce que 'la bourse' ?", options: ["Un sac à main", "Le marché financier où s'échangent les actions", "Une banque centrale", "Un type d'impôt"], answer: "Le marché financier où s'échangent les actions" },
    { question: "Que signifie 'le pouvoir d'achat' ?", options: ["La capacité d'acheter des actions", "La quantité de biens qu'un revenu permet d'acheter", "Le droit de voter", "La richesse d'un pays"], answer: "La quantité de biens qu'un revenu permet d'acheter" },
    { question: "Qu'est-ce qu'une 'crise' ?", options: ["Une période de prospérité", "Une période de difficultés économiques graves", "Une fête nationale", "Une nouvelle loi"], answer: "Une période de difficultés économiques graves" },
    { question: "Que signifie 'épargner' ?", options: ["Dépenser tout son argent", "Mettre de l'argent de côté", "Emprunter à la banque", "Investir en bourse"], answer: "Mettre de l'argent de côté" },
    { question: "Qu'est-ce qu'un 'syndicat' ?", options: ["Une organisation de patrons", "Une organisation de défense des intérêts des travailleurs", "Une banque d'investissement", "Un service de l'État"], answer: "Une organisation de défense des intérêts des travailleurs" },
    { question: "Que signifie 'la concurrence' ?", options: ["L'entente entre les entreprises", "La rivalité entre plusieurs entreprises sur un marché", "Le monopole d'une seule entreprise", "La fermeture d'une entreprise"], answer: "La rivalité entre plusieurs entreprises sur un marché" },
    { question: "Qu'est-ce qu'un 'budget' ?", options: ["Une liste de courses", "L'ensemble des recettes et des dépenses prévues", "Un prêt bancaire", "Un type de compte en banque"], answer: "L'ensemble des recettes et des dépenses prévues" }
  ],
  // Quiz 2: Tendances et Problèmes
  [
    { question: "Quelle est la conséquence directe d'une inflation élevée ?", options: ["Les prix baissent", "Le pouvoir d'achat diminue", "Le chômage s'arrête", "La monnaie prend de la valeur"], answer: "Le pouvoir d'achat diminue" },
    { question: "Que se passe-t-il lors d'une période de récession ?", options: ["Le PIB augmente", "Le PIB diminue pendant plusieurs trimestres", "Tout le monde trouve un travail", "Les banques ferment"], answer: "Le PIB diminue pendant plusieurs trimestres" },
    { question: "Comment appelle-t-on le fait de ne pas avoir de travail ?", options: ["La grève", "Le chômage", "Le congé", "La retraite"], answer: "Le chômage" },
    { question: "Quel indicateur mesure la richesse produit par un pays en un an ?", options: ["L'inflation", "Le PIB", "La dette", "Le budget"], answer: "Le PIB" },
    { question: "Que signifie 'faire faillite' ?", options: ["Gagner beaucoup d'argent", "Ne plus pouvoir payer ses dettes et fermer", "Ouvrir une nouvelle succursale", "Changer de direction"], answer: "Ne plus pouvoir payer ses dettes et fermer" },
    { question: "Quel est le rôle de la Banque Centrale ?", options: ["Prêter de l'argent aux particuliers", "Gérer la monnaie et les taux d'intérêt", "Vendre des produits au marché", "Collecter les impôts"], answer: "Gérer la monnaie et les taux d'intérêt" },
    { question: "Pourquoi les prix augmentent-ils souvent ?", options: ["Parce que la demande dépasse l'offre", "Parce que tout le monde est riche", "Parce que la production est trop facile", "Parce que les gens n'achètent rien"], answer: "Parce que la demande dépasse l'offre" },
    { question: "Qu'est-ce qu'une 'subvention' ?", options: ["Une amende à payer", "Une aide financière de l'État", "Un type d'action en bourse", "Une taxe sur la consommation"], answer: "Une aide financière de l'État" },
    { question: "Que signifie 'la mondialisation' ?", options: ["Le repli sur soi d'un pays", "L'interdépendance croissante des économies mondiales", "Le voyage dans l'espace", "La fin du commerce"], answer: "L'interdépendance croissante des économies mondiales" },
    { question: "Quel secteur s'occupe de la finance et du commerce ?", options: ["Le secteur primaire", "Le secteur secondaire", "Le secteur tertiaire", "Le secteur quaternaire"], answer: "Le secteur tertiaire" },
    { question: "Que signifie 'le taux d'intérêt' ?", options: ["Le prix de l'argent emprunté", "Le montant des impôts", "Le salaire minimum", "La valeur du dollar"], answer: "Le prix de l'argent emprunté" },
    { question: "Quel est le but d'un syndicat ?", options: ["Maximiser les profits", "Défendre les droits des salariés", "Collecter les taxes", "Investir en bourse"], answer: "Défendre les droits des salariés" },
    { question: "Que signifie 'la précarité' ?", options: ["La richesse extrême", "Une situation d'instabilité financière", "Un CDI", "Une promotion au travail"], answer: "Une situation d'instabilité financière" },
    { question: "Qu'est-ce qu'un 'débit' sur un compte ?", options: ["Une entrée d'argent", "Une sortie d'argent", "Un gain au loto", "Un nouveau prêt"], answer: "Une sortie d'argent" },
    { question: "Que signifie 'l'austérité' ?", options: ["Une politique de grandes dépenses", "Une politique de réduction stricte des dépenses publiques", "Une période de fête", "La fin de la monnaie"], answer: "Une politique de réduction stricte des dépenses publiques" },
    { question: "Quelle est la différence entre brut et net pour un salaire ?", options: ["Il n'y a pas de différence", "Le net est ce que l'on reçoit après les taxes", "Le brut est plus petit que le net", "Le brut inclut les vacances"], answer: "Le net est ce que l'on reçoit après les taxes" },
    { question: "Que signifie 'délocaliser' une usine ?", options: ["La fermer définitivement", "La déplacer dans un pays où les coûts sont plus bas", "L'agrandir sur place", "La vendre à l'État"], answer: "La déplacer dans un pays où les coûts sont plus bas" },
    { question: "Qu'est-ce que le 'SMIC' en France ?", options: ["Le syndicat des mines", "Le Salaire Minimum Interprofessionnel de Croissance", "Une taxe sur le café", "Un type d'investissement"], answer: "Le Salaire Minimum Interprofessionnel de Croissance" },
    { question: "Que signifie 'le plein emploi' ?", options: ["Une situation où tout le monde a un travail", "Une entreprise qui n'a plus de place", "Un réservoir d'essence plein", "Un emploi à 40 heures"], answer: "Une situation où tout le monde a un travail" },
    { question: "Qu'est-ce qu'une 'action' en bourse ?", options: ["Un geste héroïque", "Une part du capital d'une entreprise", "Une dette envers la banque", "Un type de contrat de travail"], answer: "Une part du capital d'une entreprise" }
  ],
  // Quiz 3: Finance et Commerce
  [
    { question: "Si j'achète un produit à l'étranger pour le vendre ici, c'est une...", options: ["Exportation", "Importation", "Subvention", "Donation"], answer: "Importation" },
    { question: "Si une entreprise vend ses produits aux USA, c'est une...", options: ["Importation", "Exportation", "Perte", "Taxation"], answer: "Exportation" },
    { question: "Que signifie 'être à découvert' à la banque ?", options: ["Avoir beaucoup d'argent", "Avoir un compte négatif", "Avoir perdu ses clefs", "Avoir un nouveau compte"], answer: "Avoir un compte negatif" },
    { question: "Qu'est-ce qu'un 'virement' ?", options: ["Un licenciement", "Un transfert d'argent d'un compte à un autre", "Une augmentation de salaire", "Une taxe sur les vêtements"], answer: "Un transfert d'argent d'un compte à un autre" },
    { question: "Que signifie 'rentable' ?", options: ["Qui coûte cher", "Qui produit un bénéfice", "Qui est inutile", "Qui est gratuit"], answer: "Qui produit un bénéfice" },
    { question: "Qu'est-ce que 'la TVA' ?", options: ["Une Taxe sur la Valeur Ajoutée", "Un type de voiture", "Une aide pour les vacances", "Un syndicat d'artistes"], answer: "Une Taxe sur la Valeur Ajoutée" },
    { question: "Que signifie 'négocier' un prix ?", options: ["Payer sans discuter", "Discuter pour obtenir un meilleur prix", "Demander un reçu", "Payer par carte"], answer: "Discuter pour obtenir un meilleur prix" },
    { question: "Qu'est-ce qu'un 'crédit' ?", options: ["Une dette que l'on rembourse", "Un cadeau de la banque", "Une amende policière", "Un type d'épargne"], answer: "Une dette que l'on rembourse" },
    { question: "Que signifie 'solvable' ?", options: ["Qui peut payer ses dettes", "Qui est en prison", "Qui n'a pas de compte", "Qui travaille au soleil"], answer: "Qui peut payer ses dettes" },
    { question: "Qu'est-ce qu'un 'dividende' ?", options: ["Une part du profit versée aux actionnaires", "Une taxe sur le pétrole", "Un nouveau règlement", "Un type de chèque"], answer: "Une part du profit versée aux actionnaires" },
    { question: "Que signifie 'le pouvoir d'achat' ?", options: ["La force physique", "La capacité financière d'acheter", "Le droit de vote", "La publicité"], answer: "La capacité financière d'acheter" },
    { question: "Si les prix baissent de façon généralisée, on parle de...", options: ["Déflation", "Inflation", "Croissance", "Expansion"], answer: "Déflation" },
    { question: "Qu'est-ce qu'une 'pénurie' ?", options: ["Une abondance de produits", "Un manque de produits", "Une baisse des prix", "Une nouvelle monnaie"], answer: "Un manque de produits" },
    { question: "Que signifie 'le capital' ?", options: ["La ville principale", "Les ressources financières d'une entreprise", "Une lettre majuscule", "Un type de chapeau"], answer: "Les ressources financières d'une entreprise" },
    { question: "Qu'est-ce qu'un 'prélèvement' ?", options: ["Un ajout d'argent", "Un retrait automatique d'argent", "Une prime de Noël", "Un type de contrat"], answer: "Un retrait automatique d'argent" },
    { question: "Que signifie 'le marché noir' ?", options: ["Un marché pendant la nuit", "Le commerce illégal de marchandises", "Un marché de charbon", "Un type de bourse"], answer: "Le commerce illégal de marchandises" },
    { question: "Qu'est-ce qu'un 'courtier' ?", options: ["Un sportif qui court", "Un intermédiaire sur les marchés financiers", "Un avocat spécialisé", "Un juge"], answer: "Un intermédiaire sur les marchés financiers" },
    { question: "Que signifie 'la parité' d'une monnaie ?", options: ["Son poids", "Sa valeur par rapport à une autre monnaie", "Sa couleur", "Sa date de création"], answer: "Sa valeur par rapport à une autre monnaie" },
    { question: "Qu'est-ce que 'l'équilibre budgétaire' ?", options: ["Dépenser plus que ce que l'on gagne", "Recettes égales aux dépenses", "Ne rien dépenser", "Ne rien gagner"], answer: "Recettes égales aux dépenses" },
    { question: "Que signifie 'subvenir' à ses besoins ?", options: ["Avoir besoin d'aide", "Avoir assez d'argent pour vivre", "Vouloir devenir riche", "Travailler pour quelqu'un"], answer: "Avoir assez d'argent pour vivre" }
  ],
  // Quiz 4: Macroéconomie et Société
  [
    { question: "La mondialisation favorise surtout...", options: ["L'isolement des pays", "Les échanges internationaux", "La baisse de la technologie", "La fin du tourisme"], answer: "Les échanges internationaux" },
    { question: "Quel est l'un des buts de la taxe carbone ?", options: ["Augmenter la pollution", "Réduire les émissions de CO2", "Encourager l'achat de voitures", "Rendre le pétrole gratuit"], answer: "Réduire les émissions de CO2" },
    { question: "Que signifie 'le secteur public' ?", options: ["Les entreprises privées", "Les services et organisations gérés par l'État", "Le commerce de rue", "Les bars et restaurants"], answer: "Les services et organisations gérés par l'État" },
    { question: "Qu'est-ce qu'une 'loi de finances' ?", options: ["Une loi sur le sport", "Le texte qui prévoit le budget de l'État", "Une amende pour excès de vitesse", "Un contrat de travail"], answer: "Le texte qui prévoit le budget de l'État" },
    { question: "Que signifie 'indexer' les salaires sur l'inflation ?", options: ["Les diminuer", "Les faire augmenter en suivant les prix", "Les supprimer", "Les bloquer pendant dix ans"], answer: "Les faire augmenter en suivant les prix" },
    { question: "L'augmentation du prix du pétrole entraîne souvent...", options: ["Une baisse des prix des transports", "Une hausse des prix généralisée", "La fin de l'économie", "La richesse de tout le monde"], answer: "Une hausse des prix généralisée" },
    { question: "Que signifie 'l'autosuffisance' ?", options: ["Dépendre des autres", "Produire soi-même ce dont on a besoin", "Acheter tout à l'étranger", "Vendre tout son stock"], answer: "Produire soi-même ce dont on a besoin" },
    { question: "Qu'est-ce que le 'libre-échange' ?", options: ["Le commerce interdit", "La libre circulation des biens sans taxes douanières", "Un marché gratuit", "Un échange de cadeaux"], answer: "La libre circulation des biens sans taxes douanières" },
    { question: "Que signifie 'le protectionnisme' ?", options: ["Favoriser les importations", "Protéger l'économie nationale par des taxes sur l'import", "Protéger la nature", "Protéger les banques"], answer: "Protéger l'économie nationale par des taxes sur l'import" },
    { question: "Quel est l'effet d'une monnaie forte sur les exportations ?", options: ["Elles deviennent plus faciles", "Elles deviennent plus chères et donc plus difficiles", "Elles s'arrêtent", "Elles ne changent pas"], answer: "Elles deviennent plus chères et donc plus difficiles" },
    { question: "Que signifie 'le développement durable' ?", options: ["Une croissance rapide et polluante", "Une croissance qui respecte l'environnement et le futur", "La fin de la technologie", "L'achat de vieux produits"], answer: "Une croissance qui respecte l'environnement et le futur" },
    { question: "Qu'est-ce qu'un 'paradis fiscal' ?", options: ["Un pays sans soleil", "Un pays avec des impôts très bas ou inexistants", "Un type de banque en ligne", "Une île de vacances gratuite"], answer: "Un pays avec des impôts très bas ou inexistants" },
    { question: "Que signifie 'le pouvoir législatif' ?", options: ["Celui qui gouverne", "Celui qui vote les lois", "Celui qui juge", "Celui qui collecte les taxes"], answer: "Celui qui vote les lois" },
    { question: "Une économie fleurissante est une économie qui...", options: ["Est en crise", "Se développe bien", "Est en train de mourir", "Est fermée"], answer: "Se développe bien" },
    { question: "Que signifie 'stimuler' l'économie ?", options: ["La ralentir", "Prendre des mesures pour encourager la croissance", "L'arrêter", "La taxer lourdement"], answer: "Prendre des mesures pour encourager la croissance" },
    { question: "Qu'est-ce que 'l'exode rural' ?", options: ["Le départ des citadins vers la campagne", "Le départ des campagnards vers la ville", "Le départ vers l'étranger", "La fin de l'agriculture"], answer: "Le départ des campagnards vers la ville" },
    { question: "Que signifie 'le capitalisme' ?", options: ["Système basé sur la propriété privée et le marché", "Système où l'État possède tout", "Système sans monnaie", "Système de pure plantation"], answer: "Système basé sur la propriété privée et le marché" },
    { question: "Qu'est-ce qu'une 'prime' ?", options: ["Une amende", "Une somme d'argent supplémentaire au salaire", "Un type de taxe", "Un nouveau prêt"], answer: "Une somme d'argent supplémentaire au salaire" },
    { question: "Que signifie 'faire grève' ?", options: ["Travailler plus", "Cesser le travail pour revendiquer des droits", "Prendre des vacances", "Changer de métier"], answer: "Cesser le travail pour revendiquer des droits" },
    { question: "Qu'est-ce que 'la redistribution' ?", options: ["Donner tout son argent aux banques", "Répartir une partie des richesses via les aides sociales", "Tout vendre au marché", "Voter pour une nouvelle loi"], answer: "Répartir une partie des richesses via les aides sociales" }
  ]
];

console.log(JSON.stringify(unit389Quizzes));
