import { Question } from '../../questions';

export const u191_195: Record<number, Record<number, Question[]>> = {
    191: {
        1: [ // QUIZ 1: EASY (B2 Basics - Past Perfect Continuous)
            { id: 1, type: "SELECT", question: "Which is Past Perfect Continuous?", options: [{ id: "a", text: "had been waiting", correct: true }, { id: "b", text: "have been waiting", correct: false }, { id: "c", text: "was waiting", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (study) for hours before the test.", options: [{ id: "a", text: "had been studying", correct: true }, { id: "b", text: "has been studying", correct: false }] },
            { id: 3, type: "SELECT", question: "Past Perfect Continuous structure:", options: [{ id: "a", text: "had been + V-ing", correct: true }, { id: "b", text: "has been + V3", correct: false }] },
            { id: 4, type: "TRANSLATE", question: "Çevir:", hint: "İki saattir bekliyordum.", correctAnswer: "I had been waiting for two hours" },
            { id: 5, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They had been working.", options: [{ id: "a", text: "Çalışıyorlardı", correct: true }, { id: "b", text: "Çalışmak zorundaydılar", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We _____ (not / sleep) well lately.", options: [{ id: "a", text: "hadn't been sleeping", correct: true }, { id: "b", text: "weren't sleeping", correct: false }] },
            { id: 7, type: "SELECT", question: "Why was he tired? Because he ___ (run).", options: [{ id: "a", text: "had been running", correct: true }, { id: "b", text: "was run", correct: false }] },
            { id: 8, type: "TRANSLATE", question: "Çevir:", hint: "Yağmur yağıyordu (öncesinde).", correctAnswer: "It had been raining" },
            { id: 9, type: "SELECT", question: "How long ___ (you / wait)?", options: [{ id: "a", text: "had you been waiting", correct: true }, { id: "b", text: "have you waited", correct: false }] },
            { id: 10, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (drive) for five hours.", options: [{ id: "a", text: "had been driving", correct: true }, { id: "b", text: "was driving", correct: false }] },
            { id: 11, type: "SELECT", question: "Past Perfect Continuous emphasizes:", options: [{ id: "a", text: "Duration of past action", correct: true }, { id: "b", text: "Completed result", correct: false }] },
            { id: 12, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He had been teaching here.", options: [{ id: "a", text: "Burada öğretmenlik yapıyordu", correct: true }, { id: "b", text: "Burada öğrenciydi", correct: false }] },
            { id: 13, type: "TRANSLATE", question: "Çevir:", hint: "Konuşuyorlardı.", correctAnswer: "They had been talking" },
            { id: 14, type: "FILL_BLANK", question: "Doldur:", sentence: "The baby _____ (cry) all night.", options: [{ id: "a", text: "had been crying", correct: true }, { id: "b", text: "is crying", correct: false }] },
            { id: 15, type: "SELECT", question: "Positive form: She ___.", options: [{ id: "a", text: "had been cooking", correct: true }, { id: "b", text: "had cooked", correct: false }] },
            { id: 16, type: "SELECT", question: "Negative form: I ___.", options: [{ id: "a", text: "had not been listening", correct: true }, { id: "b", text: "was not listen", correct: false }] },
            { id: 17, type: "TRANSLATE", question: "Çevir:", hint: "Nefes nefese kalmıştı.", correctAnswer: "He had been running" },
            { id: 18, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Where had you been playing?", options: [{ id: "a", text: "Nerede oynuyordun?", correct: true }, { id: "b", text: "Ne oynuyordun?", correct: false }] },
            { id: 19, type: "FILL_BLANK", question: "Doldur:", sentence: "It _____ (snow) for days.", options: [{ id: "a", text: "had been snowing", correct: true }, { id: "b", text: "snowed", correct: false }] },
            { id: 20, type: "SELECT", question: "Interrogative: ___ they ___ studying?", options: [{ id: "a", text: "Had / been", correct: true }, { id: "b", text: "Were / not", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM
            { id: 1, type: "SELECT", question: "Their clothes were dirty because they ___ (play) football.", options: [{ id: "a", text: "had been playing", correct: true }, { id: "b", text: "have been playing", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (attempt) to call you for an hour.", options: [{ id: "a", text: "had been attempting", correct: true }, { id: "b", text: "has attempted", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gözleri kırmızıydı çünkü ağlıyordu.", correctAnswer: "Her eyes were red because she had been crying" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had you been exercising before the incident?", options: [{ id: "a", text: "Olaydan önce egzersiz mi yapıyordun?", correct: true }, { id: "b", text: "Egzersiz yapacak mısın?", correct: false }] },
            { id: 5, type: "SELECT", question: "Choose correct link: 'He was out of breath ___ he had been running.'", options: [{ id: "a", text: "because", correct: true }, { id: "b", text: "although", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "They _____ (not / pay) attention to the lecture.", options: [{ id: "a", text: "hadn't been paying", correct: true }, { id: "b", text: "weren't paying", correct: false }] },
            { id: 7, type: "SELECT", question: "Which indicates a finished result?", options: [{ id: "a", text: "Past Perfect", correct: true }, { id: "b", text: "Past Perfect Continuous", correct: false }] },
            { id: 8, type: "TRANSLATE", question: "Çevir:", hint: "Yıllardır o şirkette çalışıyordu.", correctAnswer: "He had been working at that company for years" },
            { id: 9, type: "SELECT", question: "Identify error: 'He have been waiting since noon.'", options: [{ id: "a", text: "have -> had", correct: true }, { id: "b", text: "waiting -> waited", correct: false }] },
            { id: 10, type: "FILL_BLANK", question: "Doldur:", sentence: "How long _____ (you / look) for your phone?", options: [{ id: "a", text: "had you been looking", correct: true }, { id: "b", text: "was you looking", correct: false }] },
            { id: 11, type: "SELECT", question: "The ground was wet because it ___ (rain) all night.", options: [{ id: "a", text: "had been raining", correct: true }, { id: "b", text: "had rain", correct: false }] },
            { id: 12, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I had been living in Berlin for a decade.", options: [{ id: "a", text: "On yıldır Berlin'de yaşıyordum", correct: true }, { id: "b", text: "Berlin'e on yıl önce gittim", correct: false }] },
            { id: 13, type: "TRANSLATE", question: "Çevir:", hint: "Kimlerle konuşuyordun?", correctAnswer: "Who had you been talking to?" },
            { id: 14, type: "FILL_BLANK", question: "Doldur:", sentence: "The pipes _____ (leak).", options: [{ id: "a", text: "had been leaking", correct: true }, { id: "b", text: "are leaking", correct: false }] },
            { id: 15, type: "SELECT", question: "Which emphasizes a state like 'believe'?", options: [{ id: "a", text: "Past Perfect", correct: true }, { id: "b", text: "Past Perfect Continuous (Avoid)", correct: false }] },
            { id: 16, type: "SELECT", question: "Correct negation: 'We ___ studying.'", options: [{ id: "a", text: "hadn't been", correct: true }, { id: "b", text: "weren't be", correct: false }] },
            { id: 17, type: "TRANSLATE", question: "Çevir:", hint: "Neden bahsediyorlardı?", correctAnswer: "What had they been talking about?" },
            { id: 18, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She had been ignoring his messages.", options: [{ id: "a", text: "Mesajlarını görmezden geliyordu", correct: true }, { id: "b", text: "Mesajlarını okuyordu", correct: false }] },
            { id: 19, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (expect) a letter for weeks.", options: [{ id: "a", text: "had been expecting", correct: true }, { id: "b", text: "expected", correct: false }] },
            { id: 20, type: "SELECT", question: "Which is more appropriate for a duration up to a past point?", options: [{ id: "a", text: "Past Perfect Continuous", correct: true }, { id: "b", text: "Present Perfect Continuous", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD
            { id: 1, type: "SELECT", question: "When I met him, he ___ (teach) at the university for 20 years.", options: [{ id: "a", text: "had been teaching", correct: true }, { id: "b", text: "has been teaching", correct: false }, { id: "c", text: "taught", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The engine failed because it _____ (not / run) efficiently for a long time.", options: [{ id: "a", text: "hadn't been running", correct: true }, { id: "b", text: "wasn't running", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Oraya vardığımızda üç saattir yürümekteydik.", correctAnswer: "We had been walking for three hours when we got there" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had they been negotiating before the strike?", options: [{ id: "a", text: "Grevden önce müzakere ediyorlar mıydı?", correct: true }, { id: "b", text: "Grevi bitirdiler mi?", correct: false }] },
            { id: 5, type: "SELECT", question: "In narrative, which action happened first? 'He was exhausted; he had been driving all day.'", options: [{ id: "a", text: "Driving", correct: true }, { id: "b", text: "Feeling exhausted", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "By the time we noticed the fire, it _____ (burn) for an hour.", options: [{ id: "a", text: "had been burning", correct: true }, { id: "b", text: "burnt", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Başım ağrıyordu çünkü bütün gün ekrana bakıyordum.", correctAnswer: "My head was aching because I had been looking at the screen all day" },
            { id: 8, type: "SELECT", question: "Which use is correct for non-continuous verbs (e.g., know)?", options: [{ id: "a", text: "I had known him for years.", correct: true }, { id: "b", text: "I had been knowing him for years.", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (not / study) hard enough, hence the failure.", options: [{ id: "a", text: "hadn't been studying", correct: true }, { id: "b", text: "wasn't study", correct: false }] },
            { id: 10, type: "SELECT", question: "Contrast: 'I ___ (wait) for an hour when the bus finally ___ (arrive).'", options: [{ id: "a", text: "had been waiting / arrived", correct: true }, { id: "b", text: "was waiting / had arrived", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Tatile çıkmadan önce deli gibi çalışıyordum.", correctAnswer: "I had been working like crazy before I went on vacation" },
            { id: 12, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He had been suffering from a cold for a week.", options: [{ id: "a", text: "Bir haftadır soğuk algınlığı çekiyordu", correct: true }, { id: "b", text: "Geçen hafta hastalandı", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (they / discuss) the merger for long?", options: [{ id: "a", text: "Had they been discussing", correct: true }, { id: "b", text: "Were they discuss", correct: false }] },
            { id: 14, type: "SELECT", question: "Duration up to a past time: 'I ___ (write) since 10 AM when the light went out.'", options: [{ id: "a", text: "had been writing", correct: true }, { id: "b", text: "write", correct: false }] },
            { id: 15, type: "TRANSLATE", question: "Çevir:", hint: "Oraya taşınmadan önce Paris'te yaşıyordu.", correctAnswer: "He had been living in Paris before he moved there" },
            { id: 16, type: "FILL_BLANK", question: "Doldur:", sentence: "We _____ (not / practice) very often lately.", options: [{ id: "a", text: "hadn't been practicing", correct: true }, { id: "b", text: "haven't practice", correct: false }] },
            { id: 17, type: "SELECT", question: "Reason for past state: 'He was happy because he ___ (plan) a surprise.'", options: [{ id: "a", text: "had been planning", correct: true }, { id: "b", text: "plans", correct: false }] },
            { id: 18, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I had been expecting a different result.", options: [{ id: "a", text: "Farklı bir sonuç bekliyordum", correct: true }, { id: "b", text: "Aynı sonucu bekliyordum", correct: false }] },
            { id: 19, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (he / hide) something from us?", options: [{ id: "a", text: "Had he been hiding", correct: true }, { id: "b", text: "Has he hiding", correct: false }] },
            { id: 20, type: "TRANSLATE", question: "Çevir:", hint: "Hukuk çalışmaktansa tıp okuyordu.", correctAnswer: "He had been studying medicine instead of law" }
        ],
        4: [ // QUIZ 4: EXPERT (Mix & Academic Context)
            { id: 1, type: "TRANSLATE", question: "Çevir:", hint: "Aniden istifa etmeden önce terfi için lobi yapmaktaydı.", correctAnswer: "He had been lobbying for a promotion before he suddenly resigned" },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Until that day, I _____ (never / consider) that he might be lying.", options: [{ id: "a", text: "had never considered", correct: true }, { id: "b", text: "had never been considering", correct: false }] },
            { id: 3, type: "SELECT", question: "Subtle difference: 'He had been drinking' vs 'He had drunk'. Which implies he is still affected now?", options: [{ id: "a", text: "had been drinking (process)", correct: true }, { id: "b", text: "had drunk (completion)", correct: false }] },
            { id: 4, type: "TRANSLATE", question: "Çevir:", hint: "Piyasa çökmeden önce şirket hızla büyümekteydi.", correctAnswer: "The company had been growing rapidly before the market crashed" },
            { id: 5, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They had been contemplating a expansion since last winter.", options: [{ id: "a", text: "Geçen kıştan beri bir genişleme planlıyorlardı/düşünüyorlardı", correct: true }, { id: "b", text: "Geçen kış genişlediler", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The scientist _____ (research) the virus for years before finding a cure.", options: [{ id: "a", text: "had been researching", correct: true }, { id: "b", text: "researched", correct: false }] },
            { id: 7, type: "SELECT", question: "Which sounds more formal academic? 'The subject ___ (observe) for a week.'", options: [{ id: "a", text: "had been being observed (Passive - Rarely used)", correct: false }, { id: "b", text: "had been observed (Simple Passive)", correct: true }] },
            { id: 8, type: "TRANSLATE", question: "Çevir:", hint: "Enflasyon kontrol altına alınana kadar artmaya devam ediyordu.", correctAnswer: "Inflation had been increasing until it was brought under control" },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (you / investigate) the case before the FBI took over?", options: [{ id: "a", text: "Had you been investigating", correct: true }, { id: "b", text: "Were you investigate", correct: false }] },
            { id: 10, type: "SELECT", question: "Contrast: 'I ___ (read) the book' vs 'I ___ (read) the book since morning.'", options: [{ id: "a", text: "had read / had been reading", correct: true }, { id: "b", text: "had been reading / had read", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Şüpheli, polis gelmeden önce delilleri yok etmekteydi.", correctAnswer: "The suspect had been destroying the evidence before the police arrived" },
            { id: 12, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had the community been flourishing before the dam was built?", options: [{ id: "a", text: "Baraj yapılmadan önce topluluk gelişiyor muydu?", correct: true }, { id: "b", text: "Baraj topluluğu geliştirdi mi?", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "By the end of the year, we _____ (negotiate) for six months.", options: [{ id: "a", text: "had been negotiating", correct: true }, { id: "b", text: "negotiated", correct: false }] },
            { id: 14, type: "SELECT", question: "Find error: 'He were been living in London for centuries.'", options: [{ id: "a", text: "were -> had", correct: true }, { id: "b", text: "been -> being", correct: false }] },
            { id: 15, type: "TRANSLATE", question: "Çevir:", hint: "Ekonomik kriz vurmadan önce hane halkı borçları birikmekteydi.", correctAnswer: "Household debt had been accumulating before the economic crisis hit" },
            { id: 16, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (not / practice) her speech, which was evident.", options: [{ id: "a", text: "hadn't been practicing", correct: true }, { id: "b", text: "wasn't practice", correct: false }] },
            { id: 17, type: "SELECT", question: "Action interrupted by another: 'She ___ (cook) when the fire alarm ___ (go) off.'", options: [{ id: "a", text: "had been cooking / went", correct: true }, { id: "b", text: "cooked / had gone", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bütün gece çalışmaktan yorgun düşmüştü.", correctAnswer: "He was exhausted from having been working all night" },
            { id: 19, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (the company / struggle) financially for a long period?", options: [{ id: "a", text: "Had the company been struggling", correct: true }, { id: "b", text: "Has the struggle", correct: false }] },
            { id: 20, type: "SELECT", question: "Ultimate B2 check: 'I ___ (always / intend) to visit Japan before I finally went.'", options: [{ id: "a", text: "had always intended (State)", correct: true }, { id: "b", text: "had always been intending (Continuous - focus on process)", correct: false }] }
        ]
    },
    193: {
        1: [ // QUIZ 1: EASY (Animal Idioms)
            { id: 1, type: "SELECT", question: "Elephant in the room means:", options: [{ id: "a", text: "Görmezden gelinen açık sorun", correct: true }, { id: "b", text: "Odaya giren bir fil", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Stop crying over spilled _____. It's done.", options: [{ id: "a", text: "milk", correct: true }, { id: "b", text: "water", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Baklayı ağzından çıkar.", correctAnswer: "Let the cat out of the bag" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't count your chickens before they hatch.", options: [{ id: "a", text: "Dereyi görmeden paçaları sıvama", correct: true }, { id: "b", text: "Tavukları saymayı unutma", correct: false }] },
            { id: 5, type: "SELECT", question: "A 'dark horse' is:", options: [{ id: "a", text: "Sürpriz yapan yetenekli kimse", correct: true }, { id: "b", text: "Siyah bir at", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He is a real lone _____. He works better alone.", options: [{ id: "a", text: "wolf", correct: true }, { id: "b", text: "dog", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, her şey yalan.", correctAnswer: "I know, it's all a pack of lies" },
            { id: 8, type: "SELECT", question: "'Barking up the wrong tree' means:", options: [{ id: "a", text: "Yanlış yere yönelmek", correct: true }, { id: "b", text: "Ağaca havlamak", correct: false }] },
            { id: 9, type: "TRANSLATE", question: "Çevir:", hint: "O bir fare gibi sessiz.", correctAnswer: "She is as quiet as a mouse" },
            { id: 10, type: "FILL_BLANK", question: "Doldur:", sentence: "You are the _____ of my eye.", options: [{ id: "a", text: "apple", correct: true }, { id: "b", text: "orange", correct: false }] },
            { id: 11, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's raining cats and dogs.", options: [{ id: "a", text: "Bardaktan boşalırcasına yağıyor", correct: true }, { id: "b", text: "Kedi ve köpekler yağıyor", correct: false }] },
            { id: 12, type: "SELECT", question: "'Hold your horses' means:", options: [{ id: "a", text: "Sakin ol, bekle", correct: true }, { id: "b", text: "Atları yakala", correct: false }] },
            { id: 13, type: "TRANSLATE", question: "Çevir:", hint: "Yorgunluktan öldüm.", correctAnswer: "I'm dog-tired" },
            { id: 14, type: "FILL_BLANK", question: "Doldur:", sentence: "Working like a _____.", options: [{ id: "a", text: "dog", correct: true }, { id: "b", text: "cat", correct: false }] },
            { id: 15, type: "SELECT", question: "Bull in a china shop:", options: [{ id: "a", text: "Sakar/dikkatsiz kişi", correct: true }, { id: "b", text: "Porselen dükkanındaki boğa", correct: false }] },
            { id: 16, type: "TRANSLATE", question: "Çevir:", hint: "O çok kurnaz.", correctAnswer: "He is as sly as a fox" },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "A bird's _____ view.", options: [{ id: "a", text: "eye", correct: true }, { id: "b", text: "view", correct: false }] },
            { id: 18, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Kill two birds with one stone.", options: [{ id: "a", text: "Bir taşla iki kuş vurmak", correct: true }, { id: "b", text: "İki kuş satın almak", correct: false }] },
            { id: 19, type: "SELECT", question: "Whale of a time:", options: [{ id: "a", text: "Çok harika vakit", correct: true }, { id: "b", text: "Balina zamanı", correct: false }] },
            { id: 20, type: "TRANSLATE", question: "Çevir:", hint: "Bu bir aslan işi.", correctAnswer: "This is a lion's share" }
        ],
        2: [ // QUIZ 2: MEDIUM (Success/Failure)
            { id: 1, type: "SELECT", question: "Break a leg means:", options: [{ id: "a", text: "İyi şanslar", correct: true }, { id: "b", text: "Bacağını kır", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The project failed, so we are back to _____ one.", options: [{ id: "a", text: "square", correct: true }, { id: "b", text: "box", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Pes etme, dayan.", correctAnswer: "Hang in there" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Cut to the chase.", options: [{ id: "a", text: "Sadede gel", correct: true }, { id: "b", text: "Kovalamaca yap", correct: false }] },
            { id: 5, type: "SELECT", question: "'Hit the nail on the head' means:", options: [{ id: "a", text: "Tam üstüne bastın", correct: true }, { id: "b", text: "Çivi çakmak", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "That car costs an arm and a _____.", options: [{ id: "a", text: "leg", correct: true }, { id: "b", text: "hand", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Son şansın.", correctAnswer: "It's your last shot" },
            { id: 8, type: "SELECT", question: "'A piece of cake' means:", options: [{ id: "a", text: "Çok kolay", correct: true }, { id: "b", text: "Bir dilim pasta", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The exam was as easy as _____.", options: [{ id: "a", text: "pie", correct: true }, { id: "b", text: "cake", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't judge a book by its cover.", options: [{ id: "a", text: "Görünüşe aldanma", correct: true }, { id: "b", text: "Kitabı kapağıyla yargılama", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu bardağı taşıran son damla.", correctAnswer: "This is the last straw" },
            { id: 12, type: "SELECT", question: "Blessing in disguise:", options: [{ id: "a", text: "Kötü görünen iyi bir şey", correct: true }, { id: "b", text: "Kılık değiştirmiş büyü", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Better late than _____.", options: [{ id: "a", text: "never", correct: true }, { id: "b", text: "always", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Durumu düzeltelim.", correctAnswer: "Let's fix the situation" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Burn the midnight oil.", options: [{ id: "a", text: "Gece gündüz çalışmak", correct: true }, { id: "b", text: "Yağ yakmak", correct: false }] },
            { id: 16, type: "SELECT", question: "Call it a day:", options: [{ id: "a", text: "Bugünlük bu kadar", correct: true }, { id: "b", text: "Güne isim ver", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "No pain, no _____.", options: [{ id: "a", text: "gain", correct: true }, { id: "b", text: "pain", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Zaman nakittir.", correctAnswer: "Time is money" },
            { id: 19, type: "SELECT", question: "Under the weather:", options: [{ id: "a", text: "Keyifsiz/Hasta", correct: true }, { id: "b", text: "Hava altında", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Make a long story _____.", options: [{ id: "a", text: "short", correct: true }, { id: "b", text: "long", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Time/Money)
            { id: 1, type: "SELECT", question: "At the eleventh hour means:", options: [{ id: "a", text: "Son dakikada", correct: true }, { id: "b", text: "On birde", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "That fancy dinner really broke the _____.", options: [{ id: "a", text: "bank", correct: true }, { id: "b", text: "glass", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Zaman her şeyin ilacıdır.", correctAnswer: "Time heals all wounds" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Time flies when you're having fun.", options: [{ id: "a", text: "Eğlenirken zaman uçar", correct: true }, { id: "b", text: "Zaman sinekleri sevmez", correct: false }] },
            { id: 5, type: "SELECT", question: "To 'foot the bill' means:", options: [{ id: "a", text: "Hesabı ödemek", correct: true }, { id: "b", text: "Faturayı ayağıyla itmek", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I'm feeling a bit short of _____ this month.", options: [{ id: "a", text: "cash", correct: true }, { id: "b", text: "time", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Zaman su gibi akıp geçiyor.", correctAnswer: "Time is running out" },
            { id: 8, type: "SELECT", question: "'Money doesn't grow on trees' means:", options: [{ id: "a", text: "Para kolay kazanılmaz", correct: true }, { id: "b", text: "Ağaçta para yetişmez", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Saving for a _____ day.", options: [{ id: "a", text: "rainy", correct: true }, { id: "b", text: "sunny", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Time is of the essence.", options: [{ id: "a", text: "Zaman kritik/önemli", correct: true }, { id: "b", text: "Zaman esanstır", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Ucuz mal alacak kadar zengin değilim.", correctAnswer: "I'm not rich enough to buy cheap things" },
            { id: 12, type: "SELECT", question: "Nest egg:", options: [{ id: "a", text: "Gelecek için biriktirilen para", correct: true }, { id: "b", text: "Yuvadaki yumurta", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Living from hand to _____.", options: [{ id: "a", text: "mouth", correct: true }, { id: "b", text: "hand", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Hesap benden.", correctAnswer: "It's on me" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Make ends meet.", options: [{ id: "a", text: "Ucu ucuna getirmek (maddi)", correct: true }, { id: "b", text: "Uçları birleştirmek", correct: false }] },
            { id: 16, type: "SELECT", question: "A penny for your thoughts:", options: [{ id: "a", text: "Ne düşünüyorsun? (Söyle)", correct: true }, { id: "b", text: "Düşüncen için bir kuruş", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Brought home the _____.", options: [{ id: "a", text: "bacon", correct: true }, { id: "b", text: "bread", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Vakit nakittir.", correctAnswer: "Time is money" },
            { id: 19, type: "SELECT", question: "In the red:", options: [{ id: "a", text: "Borç içinde", correct: true }, { id: "b", text: "Kırmızıda", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Time is _____.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "down", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Complex Idioms)
            { id: 1, type: "SELECT", question: "Caught red-handed:", options: [{ id: "a", text: "Suçüstü yakalanmak", correct: true }, { id: "b", text: "Eli boyanmak", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Stop beating around the _____. Just tell me.", options: [{ id: "a", text: "bush", correct: true }, { id: "b", text: "tree", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Her bulutun gümüş bir astarı vardır (Her şerde bir hayır vardır).", correctAnswer: "Every cloud has a silver lining" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Cry wolf.", options: [{ id: "a", text: "Yalandan tehlike çığlığı atmak", correct: true }, { id: "b", text: "Kurt ağlaması", correct: false }] },
            { id: 5, type: "SELECT", question: "To jump the gun:", options: [{ id: "a", text: "Vaktinden önce harekete geçmek", correct: true }, { id: "b", text: "Silahla atlamak", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The balls is in your _____ now.", options: [{ id: "a", text: "court", correct: true }, { id: "b", text: "field", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Ateşe körükle gitme.", correctAnswer: "Don't add fuel to the fire" },
            { id: 8, type: "SELECT", question: "'Once in a blue moon' means:", options: [{ id: "a", text: "Çok nadir", correct: true }, { id: "b", text: "Mavi ay çıktığında", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Steal someone's _____.", options: [{ id: "a", text: "thunder", correct: true }, { id: "b", text: "rain", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't put all your eggs in one basket.", options: [{ id: "a", text: "Bütün varlığını tek bir şeye bağlama", correct: true }, { id: "b", text: "Sepetteki yumurtalara dikkat et", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Onu bir tutam tuzla al (Pek inanma).", correctAnswer: "Take it with a grain of salt" },
            { id: 12, type: "SELECT", question: "Best of both worlds:", options: [{ id: "a", text: "İki avantajı aynı anda yaşamak", correct: true }, { id: "b", text: "İki dünya arası", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "A hot _____.", options: [{ id: "a", text: "potato", correct: true }, { id: "b", text: "tomato", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Üzerinde uyuyayım (Bir gün düşüneyim).", correctAnswer: "Let me sleep on it" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "See eye to eye.", options: [{ id: "a", text: "Hemfikir olmak", correct: true }, { id: "b", text: "Göz göze gelmek", correct: false }] },
            { id: 16, type: "SELECT", question: "Wrap your head around something:", options: [{ id: "a", text: "Bir şeyi anlamak/kavramak", correct: true }, { id: "b", text: "Başını sarmak", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Lose your _____.", options: [{ id: "a", text: "marbles", correct: true }, { id: "b", text: "mind", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gecikme (Vakit kaybetme).", correctAnswer: "Don't drag your feet" },
            { id: 19, type: "SELECT", question: "Through thick and thin:", options: [{ id: "a", text: "İyi günde kötü günde", correct: true }, { id: "b", text: "İnce ve kalın arasından", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Hit the _____.", options: [{ id: "a", text: "hay", correct: true }, { id: "b", text: "grass", correct: false }] }
        ]
    },
    192: {
        1: [ // QUIZ 1: EASY (Future Perfect Basics)
            { id: 1, type: "SELECT", question: "Future Perfect structure:", options: [{ id: "a", text: "will have + V3", correct: true }, { id: "b", text: "will be + Ving", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "By next year, I _____ (graduate).", options: [{ id: "a", text: "will have graduated", correct: true }, { id: "b", text: "will graduate", correct: false }] },
            { id: 3, type: "SELECT", question: "Future Perfect Continuous structure:", options: [{ id: "a", text: "will have been + Ving", correct: true }, { id: "b", text: "will have + V3", correct: false }] },
            { id: 4, type: "TRANSLATE", question: "Çevir:", hint: "Yarın bu vakitte bitirmiş olacağım.", correctAnswer: "I will have finished by this time tomorrow" },
            { id: 5, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We will have been living here for 5 years.", options: [{ id: "a", text: "Burada 5 yıldır yaşıyor olacağız", correct: true }, { id: "b", text: "Burada 5 yıl yaşadık", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (not / finish) the report by noon.", options: [{ id: "a", text: "won't have finished", correct: true }, { id: "b", text: "doesn't finish", correct: false }] },
            { id: 7, type: "SELECT", question: "Future Perfect indicates an action ___ before a point.", options: [{ id: "a", text: "completed", correct: true }, { id: "b", text: "in progress", correct: false }] },
            { id: 8, type: "TRANSLATE", question: "Çevir:", hint: "Akşama kadar varmış olacağız.", correctAnswer: "We will have arrived by evening" },
            { id: 9, type: "SELECT", question: "Will they ___ (leave) before we arrive?", options: [{ id: "a", text: "have left", correct: true }, { id: "b", text: "leaving", correct: false }] },
            { id: 10, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (save) enough money by 2030.", options: [{ id: "a", text: "will have saved", correct: true }, { id: "b", text: "will save", correct: false }] },
            { id: 11, type: "LISTENING", question: "Duyduğunu seç:", audioText: "How long will you have been waitng?", options: [{ id: "a", text: "Ne kadar süredir bekliyor olacaksın?", correct: true }, { id: "b", text: "Nereye gidiyorsun?", correct: false }] },
            { id: 12, type: "TRANSLATE", question: "Çevir:", hint: "O vakte kadar uyumuş olacağım.", correctAnswer: "I will have slept by then" },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "They _____ (not / arrive) yet.", options: [{ id: "a", text: "won't have arrived", correct: true }, { id: "b", text: "not arrive", correct: false }] },
            { id: 14, type: "SELECT", question: "Which is Future Continuous?", options: [{ id: "a", text: "will be working", correct: true }, { id: "b", text: "will have worked", correct: false }] },
            { id: 15, type: "TRANSLATE", question: "Çevir:", hint: "On saattir çalışıyor olacağız.", correctAnswer: "We will have been working for ten hours" },
            { id: 16, type: "SELECT", question: "By noon, he ___ (paint) the wall.", options: [{ id: "a", text: "will have painted", correct: true }, { id: "b", text: "paints", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (you / learn) Spanish by July?", options: [{ id: "a", text: "Will you have learned", correct: true }, { id: "b", text: "Do you learn", correct: false }] },
            { id: 18, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The movie will have started.", options: [{ id: "a", text: "Film başlamış olacak", correct: true }, { id: "b", text: "Film başlayacak", correct: false }] },
            { id: 19, type: "TRANSLATE", question: "Çevir:", hint: "Evlenmiş olacaklar.", correctAnswer: "They will have married" },
            { id: 20, type: "SELECT", question: "Future Perfect focus:", options: [{ id: "a", text: "Results by a specific time", correct: true }, { id: "b", text: "Ongoing process", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM
            { id: 1, type: "SELECT", question: "By 2025, computers ___ (become) even smarter.", options: [{ id: "a", text: "will have become", correct: true }, { id: "b", text: "has become", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "By the time you see this, I _____ (leave).", options: [{ id: "a", text: "will have left", correct: true }, { id: "b", text: "was left", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "İki yıldır İngilizce çalışıyor olacağım.", correctAnswer: "I will have been studying English for two years" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "How long will he have been driving by midnight?", options: [{ id: "a", text: "Gece yarısına kadar ne kadar süredir araç sürüyor olacak?", correct: true }, { id: "b", text: "Nereye gidiyor?", correct: false }] },
            { id: 5, type: "SELECT", question: "Use for a finished future action: 'She ___ (cook) dinner when we get home.'", options: [{ id: "a", text: "will have cooked", correct: true }, { id: "b", text: "will be cooking", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We _____ (negotiate) for days by then.", options: [{ id: "a", text: "will have been negotiating", correct: true }, { id: "b", text: "were negotiating", correct: false }] },
            { id: 7, type: "SELECT", question: "Which denotes duration until a future point?", options: [{ id: "a", text: "Future Perfect Continuous", correct: true }, { id: "b", text: "Future Continuous", correct: false }] },
            { id: 8, type: "TRANSLATE", question: "Çevir:", hint: "Kitabı bitirmiş olacağım.", correctAnswer: "I will have finished the book" },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (not / meet) him yet.", options: [{ id: "a", text: "won't have met", correct: true }, { id: "b", text: "didn't meet", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They will have built the bridge.", options: [{ id: "a", text: "Köprüyü inşa etmiş olacaklar", correct: true }, { id: "b", text: "Köprü inşa edildi", correct: false }] },
            { id: 11, type: "SELECT", question: "'By' usually indicates ___.", options: [{ id: "a", text: "A deadline for Future Perfect", correct: true }, { id: "b", text: "Exactly at that time", correct: false }] },
            { id: 12, type: "TRANSLATE", question: "Çevir:", hint: "Tatile kadar her şeyi hazırlamış olacağız.", correctAnswer: "We will have prepared everything by the vacation" },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (sit) here for hours by then.", options: [{ id: "a", text: "will have been sitting", correct: true }, { id: "b", text: "was sitting", correct: false }] },
            { id: 14, type: "SELECT", question: "Will you ___ (complete) the task by Friday?", options: [{ id: "a", text: "have completed", correct: true }, { id: "b", text: "had completed", correct: false }] },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Where will he have gone?", options: [{ id: "a", text: "Nereye gitmiş olacak?", correct: true }, { id: "b", text: "Nereye gidiyor?", correct: false }] },
            { id: 16, type: "FILL_BLANK", question: "Doldur:", sentence: "By next week, the weather _____ (change).", options: [{ id: "a", text: "will have changed", correct: true }, { id: "b", text: "changes", correct: false }] },
            { id: 17, type: "TRANSLATE", question: "Çevir:", hint: "Üç saattir konuşuyor olacaklar.", correctAnswer: "They will have been talking for three hours" },
            { id: 18, type: "SELECT", question: "Which sentence is wrong?", options: [{ id: "a", text: "I will have being working.", correct: true }, { id: "b", text: "I will have been working.", correct: false }] },
            { id: 19, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The project will have succeeded.", options: [{ id: "a", text: "Proje başarılı olmuş olacak", correct: true }, { id: "b", text: "Proje başarısız olacak", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (you / arrive) by 8 PM?", options: [{ id: "a", text: "Will you have arrived", correct: true }, { id: "b", text: "Are you arrived", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD
            { id: 1, type: "SELECT", question: "By the time the manager arrives, we ___ (organize) the files.", options: [{ id: "a", text: "will have organized", correct: true }, { id: "b", text: "will organize", correct: false }, { id: "c", text: "organize", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (not / finalize) the budget by tomorrow morning.", options: [{ id: "a", text: "won't have finalized", correct: true }, { id: "b", text: "hasn't finalized", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu yılın sonunda, beş yıldır bu şirkette çalışıyor olacağım.", correctAnswer: "By the end of this year, I will have been working at this company for five years" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Will the stock prices have increased by next quarter?", options: [{ id: "a", text: "Gelecek çeyreğe kadar hisse fiyatları artmış olacak mı?", correct: true }, { id: "b", text: "Hisseler ne kadar?", correct: false }] },
            { id: 5, type: "SELECT", question: "The deadline is coming. I ___ (write) most of the report by then.", options: [{ id: "a", text: "will have written", correct: true }, { id: "b", text: "will be writing", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "How long _____ (they / wait) in line by the time the gates open?", options: [{ id: "a", text: "will they have been waiting", correct: true }, { id: "b", text: "were they waiting", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "O vakte kadar kesin bir karar vermiş olacaklar.", correctAnswer: "They will have made a final decision by then" },
            { id: 8, type: "SELECT", question: "Identify future result: 'By June, I ___ (finish) the marathon.'", options: [{ id: "a", text: "will have finished", correct: true }, { id: "b", text: "finish", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (not / practice) enough by the audition.", options: [{ id: "a", text: "won't have practiced", correct: true }, { id: "b", text: "didn't practice", correct: false }] },
            { id: 10, type: "TRANSLATE", question: "Çevir:", hint: "Yirmi yıldır evli olmuş olacaklar.", correctAnswer: "They will have been married for twenty years" },
            { id: 11, type: "SELECT", question: "Interrupted future duration: 'I ___ (study) for two hours when you arrive.'", options: [{ id: "a", text: "will have been studying", correct: true }, { id: "b", text: "studied", correct: false }] },
            { id: 12, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The sun will have set by the time we leave.", options: [{ id: "a", text: "Ayrıldığımızda güneş batmış olacak", correct: true }, { id: "b", text: "Güneş ne zaman batıyor?", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (the team / complete) the prototype by the end of May?", options: [{ id: "a", text: "Will the team have completed", correct: true }, { id: "b", text: "Are team completed", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "On saattir uçuyor olacağız.", correctAnswer: "We will have been flying for ten hours" },
            { id: 15, type: "SELECT", question: "Which indicates an ongoing future process?", options: [{ id: "a", text: "Future Continuous", correct: true }, { id: "b", text: "Future Perfect", correct: false }] },
            { id: 16, type: "FILL_BLANK", question: "Doldur:", sentence: "By this time tomorrow, they _____ (land) in Tokyo.", options: [{ id: "a", text: "will have landed", correct: true }, { id: "b", text: "will land", correct: false }] },
            { id: 17, type: "TRANSLATE", question: "Çevir:", hint: "Hafta sonuna kadar projeyi bitirmemiş olacak.", correctAnswer: "He won't have finished the project by the weekend" },
            { id: 18, type: "LISTENING", question: "Duyduğunu seç:", audioText: "How long will you have been staying there?", options: [{ id: "a", text: "Orada ne kadar süre kalmış olacaksın?", correct: true }, { id: "b", text: "Oraya ne zaman gideceksin?", correct: false }] },
            { id: 19, type: "SELECT", question: "Which is Future Perfect Passive?", options: [{ id: "a", text: "will have been done", correct: true }, { id: "b", text: "will be done", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "By the end of the day, I _____ (read) 100 pages.", options: [{ id: "a", text: "will have read", correct: true }, { id: "b", text: "readed", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT
            { id: 1, type: "TRANSLATE", question: "Çevir:", hint: "Ekonomi düzelmeden önce aylarca mücadele etmiş olacağız.", correctAnswer: "We will have been struggling for months before the economy recovers" },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "By the time the robot is deployed, we _____ (test) it for a thousand hours.", options: [{ id: "a", text: "will have been testing", correct: true }, { id: "b", text: "have been testing", correct: false }] },
            { id: 3, type: "SELECT", question: "Advanced Timeline: 'By 2050, AI ___ (take over) most routine jobs.'", options: [{ id: "a", text: "will have taken over", correct: true }, { id: "b", text: "will take over", correct: false }] },
            { id: 4, type: "TRANSLATE", question: "Çevir:", hint: "Enflasyon yıl sonuna kadar %10 artmış olacak.", correctAnswer: "Inflation will have increased by 10% by the end of the year" },
            { id: 5, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had the researchers been expecting such a breakthrough?", options: [{ id: "a", text: "Araştırmacılar böyle bir atılım bekliyorlar mıydı? (Past Mix Quiz)", correct: true }, { id: "b", text: "Araştırmacılar ne bekliyor?", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "By next decade, humans _____ (colonize) Mars according to some experts.", options: [{ id: "a", text: "will have colonized", correct: true }, { id: "b", text: "will colonize", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "O vakte kadar bütün deliller yok edilmiş olacak.", correctAnswer: "All evidence will have been destroyed by then" },
            { id: 8, type: "SELECT", question: "Logic Check: 'I will be working at 10 PM' vs 'I will have been working since 8 AM.'", options: [{ id: "a", text: "Focus on moment vs Duration until point", correct: true }, { id: "b", text: "No difference", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "By the time she retires, she _____ (practice) medicine for forty years.", options: [{ id: "a", text: "will have been practicing", correct: true }, { id: "b", text: "practiced", correct: false }] },
            { id: 10, type: "TRANSLATE", question: "Çevir:", hint: "Konuşma başladığında iki saattir bekliyor olacağız.", correctAnswer: "We will have been waiting for two hours by the time the speech starts" },
            { id: 11, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Will you have finalized the merger by then?", options: [{ id: "a", text: "O vakte kadar birleşmeyi nihayete erdirmiş olacak mısın?", correct: true }, { id: "b", text: "Birleşme ne zaman?", correct: false }] },
            { id: 12, type: "FILL_BLANK", question: "Doldur:", sentence: "The building _____ (complete) by the next Olympic Games.", options: [{ id: "a", text: "will have been completed", correct: true }, { id: "b", text: "completes", correct: false }] },
            { id: 13, type: "SELECT", question: "Identify the false sentence:", options: [{ id: "a", text: "By tomorrow I will have been being there.", correct: true }, { id: "b", text: "By tomorrow I will be there.", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Gelecek hafta sonuna kadar raporu teslim etmiş olacağım.", correctAnswer: "I will have submitted the report by next weekend" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The technology will have evolved significantly.", options: [{ id: "a", text: "Teknoloji önemli ölçüde gelişmiş olacak", correct: true }, { id: "b", text: "Teknoloji gelişecek mi?", correct: false }] },
            { id: 16, type: "FILL_BLANK", question: "Doldur:", sentence: "How many books _____ (you / read) by a single month if you keep this pace?", options: [{ id: "a", text: "will you have read", correct: true }, { id: "b", text: "did you read", correct: false }] },
            { id: 17, type: "TRANSLATE", question: "Çevir:", hint: "Pazar gününe kadar her şey düzelmiş olacak.", correctAnswer: "Everything will have been resolved by Sunday" },
            { id: 18, type: "SELECT", question: "Future Result vs Process: 'I ___ (write) 5 emails' vs 'I ___ (write) for 5 hours.'", options: [{ id: "a", text: "will have written / will have been writing", correct: true }, { id: "b", text: "will be writing / will write", correct: false }] },
            { id: 19, type: "FILL_BLANK", question: "Doldur:", sentence: "By the end of the trip, we _____ (visit) five countries.", options: [{ id: "a", text: "will have visited", correct: true }, { id: "b", text: "visit", correct: false }] },
            { id: 20, type: "TRANSLATE", question: "Çevir:", hint: "B2 düzeyini tamamlayana kadar çok çalışmış olacaksınız.", correctAnswer: "You will have been working hard until you complete the B2 level" }
        ]
    },
    194: {
        1: [ // QUIZ 1: EASY (Common Phrasal Verbs)
            { id: 1, type: "SELECT", question: "'Give up' means:", options: [{ id: "a", text: "Pes etmek / Bırakmak", correct: true }, { id: "b", text: "Yukarı vermek", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Please turn _____ the music, it's too loud.", options: [{ id: "a", text: "down", correct: true }, { id: "b", text: "up", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Ayakkabılarını çıkar.", correctAnswer: "Take off your shoes" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll look after your cat.", options: [{ id: "a", text: "Kedine bakacağım/ilgileneceğim", correct: true }, { id: "b", text: "Kedini arıyorum", correct: false }] },
            { id: 5, type: "SELECT", question: "'Go on' is a synonym for:", options: [{ id: "a", text: "Continue", correct: true }, { id: "b", text: "Stop", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Don't _____ out! It's dangerous.", options: [{ id: "a", text: "go", correct: true }, { id: "b", text: "be", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Hızlan!", correctAnswer: "Hurry up!" },
            { id: 8, type: "SELECT", question: "'Find out' means:", options: [{ id: "a", text: "Öğrenmek/Bulup çıkarmak", correct: true }, { id: "b", text: "Dışarıda bulmak", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I ran _____ of sugar.", options: [{ id: "a", text: "out", correct: true }, { id: "b", text: "in", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Pick up the phone.", options: [{ id: "a", text: "Telefonu aç/kaldır", correct: true }, { id: "b", text: "Telefonu seç", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Seni asla yarı yolda bırakmayacağım.", correctAnswer: "I will never let you down" },
            { id: 12, type: "SELECT", question: "'Set up' a business:", options: [{ id: "a", text: "Kurmak", correct: true }, { id: "b", text: "Yukarı koymak", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "We need to _____ off now to arrive on time.", options: [{ id: "a", text: "set", correct: true }, { id: "b", text: "put", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onu geri ver.", correctAnswer: "Give it back" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Keep on working.", options: [{ id: "a", text: "Çalışmaya devam et", correct: true }, { id: "b", text: "Çalışmayı bırak", correct: false }] },
            { id: 16, type: "SELECT", question: "'Break up' with someone:", options: [{ id: "a", text: "Ayrılmak", correct: true }, { id: "b", text: "Yukarı kırmak", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I can't put _____ with this noise.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Formu doldur.", correctAnswer: "Fill in the form" },
            { id: 19, type: "SELECT", question: "'Bring up' a child:", options: [{ id: "a", text: "Büyütmek/Yetiştirmek", correct: true }, { id: "b", text: "Yukarı getirmek", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Call _____ the meeting.", options: [{ id: "a", text: "off", correct: true }, { id: "b", text: "on", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM
            { id: 1, type: "SELECT", question: "'Carry out' a plan means:", options: [{ id: "a", text: "Uygulamak/Yürütmek", correct: true }, { id: "b", text: "Dışarı taşımak", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "We need to clear _____ the misunderstanding.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "off", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Onu uydurdum.", correctAnswer: "I made it up" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The car broke down on the highway.", options: [{ id: "a", text: "Araba otobanda bozuldu", correct: true }, { id: "b", text: "Araba otobanda durdu", correct: false }] },
            { id: 5, type: "SELECT", question: "'Take up' a hobby:", options: [{ id: "a", text: "Bir hobiye başlamak", correct: true }, { id: "b", text: "Hobiyi yukarı almak", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He passed _____ last night.", options: [{ id: "a", text: "away", correct: true }, { id: "b", text: "by", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Seninle görüşmeyi dört gözle bekliyorum.", correctAnswer: "I am looking forward to seeing you" },
            { id: 8, type: "SELECT", question: "'Back up' data:", options: [{ id: "a", text: "Yedeklemek", correct: true }, { id: "b", text: "Geri gitmek", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Don't _____ in. Keep fighting.", options: [{ id: "a", text: "give", correct: true }, { id: "b", text: "go", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I came across an old photo.", options: [{ id: "a", text: "Eski bir fotoğrafa rastladım", correct: true }, { id: "b", text: "Eski bir fotoğrafı attım", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Uçağımız on dakikada kalkıyor.", correctAnswer: "Our plane takes off in ten minutes" },
            { id: 12, type: "SELECT", question: "'Work out' at the gym:", options: [{ id: "a", text: "Antrenman yapmak", correct: true }, { id: "b", text: "Dışarıda çalışmak", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Please look _____ the contract carefully.", options: [{ id: "a", text: "over", correct: true }, { id: "b", text: "at", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Benzinimiz bitti.", correctAnswer: "We ran out of gas" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Get along with colleagues.", options: [{ id: "a", text: "Meslektaşlarla iyi geçinmek", correct: true }, { id: "b", text: "Meslektaşlarla yarışmak", correct: false }] },
            { id: 16, type: "SELECT", question: "'Drop out' of school:", options: [{ id: "a", text: "Okuldan ayrılmak/terk etmek", correct: true }, { id: "b", text: "Okula düşmek", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Wait! Don't hang _____ yet.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Onu halledeceğim.", correctAnswer: "I will deal with it" },
            { id: 19, type: "SELECT", question: "'Point out' a mistake:", options: [{ id: "a", text: "Bir hataya işaret etmek", correct: true }, { id: "b", text: "Hatayı atmak", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The heater gave _____ a weird smell.", options: [{ id: "a", text: "off", correct: true }, { id: "b", text: "on", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Formal/Business)
            { id: 1, type: "SELECT", question: "'Bring about' change means:", options: [{ id: "a", text: "Değişime neden olmak", correct: true }, { id: "b", text: "Değişimi getirmek (fiziksel)", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "We must _____ in the costs for next year.", options: [{ id: "a", text: "factored", correct: false }, { id: "b", text: "factor", correct: true }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Şirketi iflastan kurtardılar.", correctAnswer: "They bailed the company out" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The deal fell through at the last minute.", options: [{ id: "a", text: "Anlaşma son dakikada suya düştü", correct: true }, { id: "b", text: "Anlaşma son dakikada imzalandı", correct: false }] },
            { id: 5, type: "SELECT", question: "'Draw up' a contract:", options: [{ id: "a", text: "Sözleşme hazırlamak/düzenlemek", correct: true }, { id: "b", text: "Sözleşmeyi çizmek", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The meeting has been _____ forward to Monday.", options: [{ id: "a", text: "brought", correct: true }, { id: "b", text: "put", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Konuyu toplantıda açacağım.", correctAnswer: "I will bring up the subject at the meeting" },
            { id: 8, type: "SELECT", question: "'Close down' a factory:", options: [{ id: "a", text: "Fabrikayı (tamamen) kapatmak", correct: true }, { id: "b", text: "Fabrikayı aşağı çekmek", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The negotiations were _____ out for months.", options: [{ id: "a", text: "dragged", correct: true }, { id: "b", text: "gone", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We need to phase out old equipment.", options: [{ id: "a", text: "Eski ekipmanları kademeli olarak kaldırmalıyız", correct: true }, { id: "b", text: "Eski ekipmanları boyamalıyız", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Onu bir süreliğine erteleyelim.", correctAnswer: "Let's put it off for a while" },
            { id: 12, type: "SELECT", question: "'Settle for' less:", options: [{ id: "a", text: "Daha azına razı olmak", correct: true }, { id: "b", text: "Daha azını ödemek", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Investors surged _____ the project.", options: [{ id: "a", text: "into", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yalanı ortaya çıktı.", correctAnswer: "His lie came out" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The business is picking up.", options: [{ id: "a", text: "İşler düzeliyor/canlanıyor", correct: true }, { id: "b", text: "İşler bitiyor", correct: false }] },
            { id: 16, type: "SELECT", question: "'Step down' from a position:", options: [{ id: "a", text: "Görevden ayrılmak/çekilmek", correct: true }, { id: "b", text: "Aşağı basmak", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Prices are marked _____.", options: [{ id: "a", text: "down", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bunu göz önünde bulundurmalısın.", correctAnswer: "You should take this into account" },
            { id: 19, type: "SELECT", question: "'Talk over' a deal:", options: [{ id: "a", text: "Anlaşma üzerine konuşmak/tartışmak", correct: true }, { id: "b", text: "Anlaşmayı konuşarak bitirmek", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I will look _____ the matter.", options: [{ id: "a", text: "into", correct: true }, { id: "b", text: "up", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Complex Phrasal Verbs)
            { id: 1, type: "SELECT", question: "'Make do with' means:", options: [{ id: "a", text: "Eldekiyle yetinmek", correct: true }, { id: "b", text: "Yapmak", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Success boils _____ to hard work.", options: [{ id: "a", text: "down", correct: true }, { id: "b", text: "up", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Fikrime sadık kalacağım.", correctAnswer: "I will stick to my opinion" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He comes across as a bit arrogant.", options: [{ id: "a", text: "Biraz kibirli görünüyor/izlenimi veriyor", correct: true }, { id: "b", text: "Kibirli olduğunu söyledi", correct: false }] },
            { id: 5, type: "SELECT", question: "'Get away with' murder:", options: [{ id: "a", text: "Bir suçtan ceza almadan kurtulmak", correct: true }, { id: "b", text: "Cinayet işlemek", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The news sank _____ slowly.", options: [{ id: "a", text: "in", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Hiçbir şey için zaman kalmadı.", correctAnswer: "Nothing left to spare" },
            { id: 8, type: "SELECT", question: "'Brush up on' English:", options: [{ id: "a", text: "İngilizceyi tazelemek/geliştirmek", correct: true }, { id: "b", text: "İngilizceyi fırçalamak", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I'll try to get _____ to your request.", options: [{ id: "a", text: "round", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't let your guard down.", options: [{ id: "a", text: "Gardını/Dikkati elden bırakma", correct: true }, { id: "b", text: "Gardiyanı bırakma", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Olaylar beklenmedik bir hal aldı.", correctAnswer: "Things took an unexpected turn" },
            { id: 12, type: "SELECT", question: "'Abide by' the rules:", options: [{ id: "a", text: "Kurallara uymak/sadık kalmak", correct: true }, { id: "b", text: "Kuralları yıkmak", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "They are crying _____ for help.", options: [{ id: "a", text: "out", correct: true }, { id: "b", text: "in", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Ona güvenebilirsin.", correctAnswer: "You can count on him" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The plan was backed down.", options: [{ id: "a", text: "Plandan vazgeçildi", correct: true }, { id: "b", text: "Plan desteklendi", correct: false }] },
            { id: 16, type: "SELECT", question: "'Go through with' a decision:", options: [{ id: "a", text: "Kararı sonuna kadar götürmek/uygulamak", correct: true }, { id: "b", text: "Karardan vazgeçmek", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "We must brace ourselves _____ the impact.", options: [{ id: "a", text: "for", correct: true }, { id: "b", text: "at", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Zor zamanlardan geçiyor.", correctAnswer: "She is going through hard times" },
            { id: 19, type: "SELECT", question: "What does 'Stand for' mean in 'NASA stands for...'?", options: [{ id: "a", text: "Temsil etmek/Anlamına gelmek", correct: true }, { id: "b", text: "İçin ayakta durmak", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I want to settle _____ and start a family.", options: [{ id: "a", text: "down", correct: true }, { id: "b", text: "up", correct: false }] }
        ]
    },
    195: {
        1: [ // QUIZ 1: EASY (Conjunctions)
            { id: 1, type: "SELECT", question: "Which indicates addition?", options: [{ id: "a", text: "and", correct: true }, { id: "b", text: "but", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I like tea _____ coffee.", options: [{ id: "a", text: "and", correct: true }, { id: "b", text: "but", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Hava yağmurlu ama sıcak.", correctAnswer: "It is rainy but warm" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Either you come or I go.", options: [{ id: "a", text: "Ya sen gel ya da ben gideyim", correct: true }, { id: "b", text: "İkimiz de gidelim", correct: false }] },
            { id: 5, type: "SELECT", question: "Which indicates choice?", options: [{ id: "a", text: "or", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He was tired _____ he went to bed.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Çünkü hastayım.", correctAnswer: "Because I am sick" },
            { id: 8, type: "SELECT", question: "Which indicates reason?", options: [{ id: "a", text: "because", correct: true }, { id: "b", text: "yet", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Neither John _____ Mary came.", options: [{ id: "a", text: "nor", correct: true }, { id: "b", text: "or", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Not only smart but also kind.", options: [{ id: "a", text: "Sadece zeki değil aynı zamanda nazik", correct: true }, { id: "b", text: "Zeki ve nazik değil", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Hem elma hem armut.", correctAnswer: "Both apples and pears" },
            { id: 12, type: "SELECT", question: "Which indicates contrast?", options: [{ id: "a", text: "yet", correct: true }, { id: "b", text: "furthermore", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Would you like tea _____ coffee?", options: [{ id: "a", text: "or", correct: true }, { id: "b", text: "nor", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Öyleyse gidelim.", correctAnswer: "So let's go" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll do it for you.", options: [{ id: "a", text: "Onu senin için yapacağım", correct: true }, { id: "b", text: "Onu sen yap", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is a coordinating conjunction?", options: [{ id: "a", text: "but", correct: true }, { id: "b", text: "although", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He worked hard _____ he failed.", options: [{ id: "a", text: "but", correct: true }, { id: "b", text: "and", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Ancak başardık.", correctAnswer: "Yet we succeeded" },
            { id: 19, type: "SELECT", question: "Structure of 'neither':", options: [{ id: "a", text: "neither ... nor", correct: true }, { id: "b", text: "neither ... or", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I don't like milk _____ eggs.", options: [{ id: "a", text: "or", correct: true }, { id: "b", text: "and", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Contrast)
            { id: 1, type: "SELECT", question: "Which is more formal than 'but'?", options: [{ id: "a", text: "however", correct: true }, { id: "b", text: "and", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ the rain, the game continued.", options: [{ id: "a", text: "Despite", correct: true }, { id: "b", text: "Although", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Zengin olmasına rağmen mutsuz.", correctAnswer: "Although he is rich, he is unhappy" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "On the other hand, it's expensive.", options: [{ id: "a", text: "Öte yandan, pahalı", correct: true }, { id: "b", text: "Onun elinde pahalı bir şey var", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is followed by a clause? (Subject + Verb)", options: [{ id: "a", text: "although", correct: true }, { id: "b", text: "in spite of", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I'm busy. _____, I'll help you.", options: [{ id: "a", text: "Nevertheless", correct: true }, { id: "b", text: "Furthermore", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Aksi takdirde geç kalacağız.", correctAnswer: "Otherwise we will be late" },
            { id: 8, type: "SELECT", question: "'While' can indicate:", options: [{ id: "a", text: "Contrast", correct: true }, { id: "b", text: "Conclusion", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He is talented _____ he is lazy.", options: [{ id: "a", text: "whereas", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "In spite of the failure, he kept trying.", options: [{ id: "a", text: "Başarısızlığa rağmen denemeye devam etti", correct: true }, { id: "b", text: "Başarısız olduğu için bıraktı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Buna rağmen gitmek zorundayım.", correctAnswer: "Even so, I have to go" },
            { id: 12, type: "SELECT", question: "Which is a synonym for 'despite'?", options: [{ id: "a", text: "in spite of", correct: true }, { id: "b", text: "consequently", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Take an umbrella _____ it rains.", options: [{ id: "a", text: "in case", correct: true }, { id: "b", text: "whereas", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yine de teşekkürler.", correctAnswer: "Even so, thanks" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Despite the fact that he was old.", options: [{ id: "a", text: "Yaşlı olmasına rağmen", correct: true }, { id: "b", text: "Yaşlı olduğu bir gerçek", correct: false }] },
            { id: 16, type: "SELECT", question: "'Even though' is ___ than 'although'.", options: [{ id: "a", text: "more emphatic", correct: true }, { id: "b", text: "less formal", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The movie was long. _____, it was good.", options: [{ id: "a", text: "Still", correct: true }, { id: "b", text: "Since", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Oysa ben seni uyarmıştım.", correctAnswer: "Whereas I had warned you" },
            { id: 19, type: "SELECT", question: "'Despite' is followed by:", options: [{ id: "a", text: "Noun or V-ing", correct: true }, { id: "b", text: "Full clause", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ popular, the song is actually old.", options: [{ id: "a", text: "Though", correct: true }, { id: "b", text: "But", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Cause/Effect)
            { id: 1, type: "SELECT", question: "Which indicates result?", options: [{ id: "a", text: "consequently", correct: true }, { id: "b", text: "since", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I was late _____ traffic.", options: [{ id: "a", text: "due to", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu nedenle toplantı iptal edildi.", correctAnswer: "Therefore the meeting was cancelled" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "As a result, we lost the game.", options: [{ id: "a", text: "Sonuç olarak oyunu kaybettik", correct: true }, { id: "b", text: "Oyunun sonucunu merak ediyoruz", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is formal for 'because'?", options: [{ id: "a", text: "as", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ it was raining, we stayed in.", options: [{ id: "a", text: "Since", correct: true }, { id: "b", text: "Due to", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Böylece sorunu çözdük.", correctAnswer: "Thus we solved the problem" },
            { id: 8, type: "SELECT", question: "'Hence' is used for:", options: [{ id: "a", text: "Logical conclusion", correct: true }, { id: "b", text: "Contrast", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He worked hard. _____, he got the job.", options: [{ id: "a", text: "Accordingly", correct: true }, { id: "b", text: "Yet", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "In view of the recent events.", options: [{ id: "a", text: "Son olaylar ışığında/göz önüne alındığında", correct: true }, { id: "b", text: "Olayları izlerken", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu yüzden buradayım.", correctAnswer: "That's why I'm here" },
            { id: 12, type: "SELECT", question: "Which is followed by a noun phrase?", options: [{ id: "a", text: "owing to", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The project failed _____ lack of funds.", options: [{ id: "a", text: "owing to", correct: true }, { id: "b", text: "consequently", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Buna bağlı olarak fiyatlar artacak.", correctAnswer: "Consequently prices will increase" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The outcome was expected.", options: [{ id: "a", text: "Sonuç/Çıktı bekleniyordu", correct: true }, { id: "b", text: "Gelir bekleniyordu", correct: false }] },
            { id: 16, type: "SELECT", question: "'So that' indicates:", options: [{ id: "a", text: "Purpose", correct: true }, { id: "b", text: "Contrast", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I saved money _____ I could buy a car.", options: [{ id: "a", text: "so that", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bundan dolayı (bu yüzden).", correctAnswer: "Hence" },
            { id: 19, type: "SELECT", question: "Synonym for 'therefore':", options: [{ id: "a", text: "consequently", correct: true }, { id: "b", text: "nevertheless", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ he was late, he missed the start.", options: [{ id: "a", text: "Given that", correct: true }, { id: "b", text: "Despite", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Formal Register)
            { id: 1, type: "SELECT", question: "'Notwithstanding' means:", options: [{ id: "a", text: "Her şeye rağmen", correct: true }, { id: "b", text: "Dahası", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ requested, we will provide it.", options: [{ id: "a", text: "Provided", correct: true }, { id: "b", text: "Given", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Dahası (Ayrıca).", correctAnswer: "Furthermore" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "In light of the evidence presented.", options: [{ id: "a", text: "Sunulan deliller ışığında", correct: true }, { id: "b", text: "Delilleri gördük", correct: false }] },
            { id: 5, type: "SELECT", question: "'Moreover' is used to:", options: [{ id: "a", text: "Add information", correct: true }, { id: "b", text: "Contrast information", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He is old. _____, he is healthy.", options: [{ id: "a", text: "Albeit", correct: false }, { id: "b", text: "Nevertheless", correct: true }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Kısacası (Özetle).", correctAnswer: "In short" },
            { id: 8, type: "SELECT", question: "'Albeit' indicates:", options: [{ id: "a", text: "Concession (even though)", correct: true }, { id: "b", text: "Addition", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "They succeeded, _____ with some help.", options: [{ id: "a", text: "albeit", correct: true }, { id: "b", text: "since", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "To sum up our findings.", options: [{ id: "a", text: "Bulgularımızı özetlemek gerekirse", correct: true }, { id: "b", text: "Yolumuzu bulduk", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Benzer şekilde.", correctAnswer: "Similarly" },
            { id: 12, type: "SELECT", question: "Which is used for enumeration?", options: [{ id: "a", text: "Firstly", correct: true }, { id: "b", text: "Indeed", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The data is clear. _____, we must act.", options: [{ id: "a", text: "Consequently", correct: true }, { id: "b", text: "Rather", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Buna ilave olarak.", correctAnswer: "In addition to this" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It should be noted that...", options: [{ id: "a", text: "Şu not edilmelidir ki...", correct: true }, { id: "b", text: "Not al", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is used for rephrasing?", options: [{ id: "a", text: "In other words", correct: true }, { id: "b", text: "For instance", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "We don't need rain. _____, we need sun.", options: [{ id: "a", text: "Rather", correct: true }, { id: "b", text: "Likewise", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Örneğin.", correctAnswer: "For example" },
            { id: 19, type: "SELECT", question: "They stayed at the beach all day ___ the wind was strong.", options: [{ id: "a", text: "even though", correct: true }, { id: "b", text: "whereas", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He decided to buy the car _____ its high price.", options: [{ id: "a", text: "despite", correct: true }, { id: "b", text: "although", correct: false }] },
        ]
    },
};
