import { Question } from '../../questions';

export const u196_200: Record<number, Record<number, Question[]>> = {
    197: {
        1: [ // QUIZ 1: EASY (Passive Basics)
            { id: 1, type: "SELECT", question: "Passive form of 'They built the house' is:", options: [{ id: "a", text: "The house was built.", correct: true }, { id: "b", text: "The house built.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The room _____ (clean) every day.", options: [{ id: "a", text: "is cleaned", correct: true }, { id: "b", text: "cleans", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu kitap 1920'de yazıldı.", correctAnswer: "This book was written in 1920" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "My car is being repaired.", options: [{ id: "a", text: "Arabam tamir ediliyor", correct: true }, { id: "b", text: "Arabam tamir edildi", correct: false }] },
            { id: 5, type: "SELECT", question: "Passive for Present Continuous:", options: [{ id: "a", text: "am/is/are + being + V3", correct: true }, { id: "b", text: "am/is/are + V3", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The letter _____ (send) yesterday.", options: [{ id: "a", text: "was sent", correct: true }, { id: "b", text: "is sent", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, her şey hazırlandı.", correctAnswer: "I know, everything was prepared" },
            { id: 8, type: "SELECT", question: "Passive for Future Simple:", options: [{ id: "a", text: "will be + V3", correct: true }, { id: "b", text: "will have + V3", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The cake _____ (eat) by the kids already.", options: [{ id: "a", text: "has been eaten", correct: true }, { id: "b", text: "is eaten", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "English is spoken all over the world.", options: [{ id: "a", text: "Dünyanın her yerinde İngilizce konuşulur", correct: true }, { id: "b", text: "İngilizce konuşmayı seviyorum", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Haberler henüz duyurulmadı.", correctAnswer: "The news hasn't been announced yet" },
            { id: 12, type: "SELECT", question: "Who performs the action in passive?", options: [{ id: "a", text: "Usually introduced by 'by'", correct: true }, { id: "b", text: "Subject", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The windows _____ (not / wash) for months.", options: [{ id: "a", text: "haven't been washed", correct: true }, { id: "b", text: "weren't washed", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yollar buzla kaplı.", correctAnswer: "The roads are covered with ice" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The problem will be solved soon.", options: [{ id: "a", text: "Sorun yakında çözülecek", correct: true }, { id: "b", text: "Sorunu çözdük", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is Past Perfect Passive?", options: [{ id: "a", text: "had been + V3", correct: true }, { id: "b", text: "was being + V3", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The thief _____ (catch) by the police.", options: [{ id: "a", text: "was caught", correct: true }, { id: "b", text: "caught", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Onu orada bulabilirsin.", correctAnswer: "It can be found there" },
            { id: 19, type: "SELECT", question: "Passive for Modals (can, must):", options: [{ id: "a", text: "modal + be + V3", correct: true }, { id: "b", text: "modal + V3", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "All the work _____ (do).", options: [{ id: "a", text: "must be done", correct: true }, { id: "b", text: "must do", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Two Objects / IT IS SAID)
            { id: 1, type: "SELECT", question: "Passive of 'They gave me a gift':", options: [{ id: "a", text: "I was given a gift.", correct: true }, { id: "b", text: "A gift given to me.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "It is _____ (believe) that the treasure is hidden here.", options: [{ id: "a", text: "believed", correct: true }, { id: "b", text: "believe", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Onun çok zengin olduğu söyleniyor.", correctAnswer: "He is said to be very rich" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She was offered a new job.", options: [{ id: "a", text: "Ona yeni bir iş teklif edildi", correct: true }, { id: "b", text: "Yeni bir iş arıyor", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is a personal passive structure?", options: [{ id: "a", text: "He is thought to be honest.", correct: true }, { id: "b", text: "It is thought that...", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We _____ (show) the way by a local.", options: [{ id: "a", text: "were shown", correct: true }, { id: "b", text: "showed", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, onlara bir şans verildi.", correctAnswer: "I know, they were given a chance" },
            { id: 8, type: "SELECT", question: "IT IS SAID vs HE IS SAID:", options: [{ id: "a", text: "Impersonal vs Personal passive", correct: true }, { id: "b", text: "Active vs Passive", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The suspect is alleged _____ (commit) the crime.", options: [{ id: "a", text: "to have committed", correct: true }, { id: "b", text: "committing", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It is rumored that they are getting married.", options: [{ id: "a", text: "Evlendikleri söyleniyor / rivayet ediliyor", correct: true }, { id: "b", text: "Evleneceklerini biliyorum", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Ona hikaye anlatıldı.", correctAnswer: "A story was told to her" },
            { id: 12, type: "SELECT", question: "Passive of 'They teach us English' (focus on US):", options: [{ id: "a", text: "We are taught English.", correct: true }, { id: "b", text: "English is taught us.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The building is expected _____ (finish) next month.", options: [{ id: "a", text: "to be finished", correct: true }, { id: "b", text: "finishing", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onun akıllı olduğu düşünülüyor.", correctAnswer: "She is thought to be smart" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I was sent a letter.", options: [{ id: "a", text: "Bana bir mektup gönderildi", correct: true }, { id: "b", text: "Mektubu ben gönderdim", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is formal?", options: [{ id: "a", text: "It is reported that the prices rose.", correct: true }, { id: "b", text: "They say prices rose.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "A lot of money was _____ (steal) from the bank.", options: [{ id: "a", text: "stolen", correct: true }, { id: "b", text: "stealed", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Ona gerçeğin söylenmesi gerekiyor.", correctAnswer: "She needs to be told the truth" },
            { id: 19, type: "SELECT", question: "Structure: 'Subject + be + V3 + to infinitive' is:", options: [{ id: "a", text: "Personal passive", correct: true }, { id: "b", text: "Active", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Are you _____ (allow) to go out?", options: [{ id: "a", text: "allowed", correct: true }, { id: "b", text: "allow", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Causatives)
            { id: 1, type: "SELECT", question: "Causative structure (HAVE):", options: [{ id: "a", text: "have + object + V3", correct: true }, { id: "b", text: "have + V3", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I had my hair _____ (cut) yesterday.", options: [{ id: "a", text: "cut", correct: true }, { id: "b", text: "cutting", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Arabamı tamir ettirdim.", correctAnswer: "I had my car repaired" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll get my brother to help us.", options: [{ id: "a", text: "Kardeşime yardım ettireceğim", correct: true }, { id: "b", text: "Kardeşim yardım etti", correct: false }] },
            { id: 5, type: "SELECT", question: "Causative structure (GET):", options: [{ id: "a", text: "get + person + to + V1", correct: true }, { id: "b", text: "get + person + V1", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She got her house _____ (paint) last week.", options: [{ id: "a", text: "painted", correct: true }, { id: "b", text: "paint", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, onu yaptıracağım.", correctAnswer: "I know, I will have it done" },
            { id: 8, type: "SELECT", question: "'Have someone do' vs 'Get someone to do':", options: [{ id: "a", text: "Infinitive without TO vs Infinitive with TO", correct: true }, { id: "b", text: "Same structure", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He made me _____ (cry).", options: [{ id: "a", text: "cry", correct: true }, { id: "b", text: "to cry", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Did you have your eyes tested?", options: [{ id: "a", text: "Gözlerini muayene ettirdin mi?", correct: true }, { id: "b", text: "Gözlerini gördün mü?", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Ona odayı temizlettirdim.", correctAnswer: "I had him clean the room" },
            { id: 12, type: "SELECT", question: "Meaning of 'Causative':", options: [{ id: "a", text: "Bir işi başkasına yaptırmak", correct: true }, { id: "b", text: "Bir işi kendin yapmak", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I'll _____ (have) the waiter bring some water.", options: [{ id: "a", text: "have", correct: true }, { id: "b", text: "get", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Dişimi çektirmek zorundayım.", correctAnswer: "I have to have my tooth pulled out" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Get the work finished by noon.", options: [{ id: "a", text: "İşi öğlene kadar bitirt (tamamlat)", correct: true }, { id: "b", text: "İş bitti", correct: false }] },
            { id: 16, type: "SELECT", question: "'Make someone do' implies:", options: [{ id: "a", text: "Force", correct: true }, { id: "b", text: "Request", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "We must get the document _____ (sign).", options: [{ id: "a", text: "signed", correct: true }, { id: "b", text: "sign", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Beni güldürüyorsun.", correctAnswer: "You make me laugh" },
            { id: 19, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "I have the letter typed.", correct: true }, { id: "b", text: "I have the letter type.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Let him _____ (go).", options: [{ id: "a", text: "go", correct: true }, { id: "b", text: "to go", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Infinitive/Gerund Passive)
            { id: 1, type: "SELECT", question: "Passive of 'I want to help' (focus on being helped):", options: [{ id: "a", text: "I want to be helped.", correct: true }, { id: "b", text: "I want to help.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I hate _____ (watch) when I'm working.", options: [{ id: "a", text: "being watched", correct: true }, { id: "b", text: "to watch", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Eleştirilmekten nefret ederim.", correctAnswer: "I hate being criticized" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The house needs cleaning.", options: [{ id: "a", text: "Evin temizlenmeye ihtiyacı var", correct: true }, { id: "b", text: "Ev temiz", correct: false }] },
            { id: 5, type: "SELECT", question: "'Needs cleaning' is equivalent to:", options: [{ id: "a", text: "Needs to be cleaned", correct: true }, { id: "b", text: "Needs to clean", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He expected _____ (invite) to the party.", options: [{ id: "a", text: "to be invited", correct: true }, { id: "b", text: "being invited", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Aldatılmaktan korkuyorum.", correctAnswer: "I am afraid of being cheated" },
            { id: 8, type: "SELECT", question: "Gerund Passive structure:", options: [{ id: "a", text: "being + V3", correct: true }, { id: "b", text: "to be + V3", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "There's no point in _____ (tell) again.", options: [{ id: "a", text: "being told", correct: true }, { id: "b", text: "to be told", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I remember being taken to the zoo.", options: [{ id: "a", text: "Hayvanat bahçesine götürüldüğümü hatırlıyorum", correct: true }, { id: "b", text: "Hayvanat bahçesine gittiğimi biliyorum", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bekletilmekten hoşlanmaz.", correctAnswer: "She doesn't like being kept waiting" },
            { id: 12, type: "SELECT", question: "Passive for 'having + V3' (Perfect Gerund):", options: [{ id: "a", text: "having been + V3", correct: true }, { id: "b", text: "having being + V3", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He apologized for _____ (not / inform).", options: [{ id: "a", text: "not having been informed", correct: true }, { id: "b", text: "not informing", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yeni bir araba alacak kadar şanslı.", correctAnswer: "He is lucky enough to be given a new car" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "To be or not to be.", options: [{ id: "a", text: "Olmak ya da olmamak", correct: true }, { id: "b", text: "Gitmek ya da gitmemek", correct: false }] },
            { id: 16, type: "SELECT", question: "Structure for 'enjoyed + Ving' (Passive):", options: [{ id: "a", text: "enjoyed being praised", correct: true }, { id: "b", text: "enjoyed to be praised", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I'm looking forward to _____ (promote).", options: [{ id: "a", text: "being promoted", correct: true }, { id: "b", text: "to be promoted", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Anlaşılmak istiyorum.", correctAnswer: "I want to be understood" },
            { id: 19, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "It needs doing.", correct: true }, { id: "b", text: "It needs done.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "She is too young _____ (allow) to drive.", options: [{ id: "a", text: "to be allowed", correct: true }, { id: "b", text: "being allowed", correct: false }] }
        ]
    },
    196: {
        1: [ // QUIZ 1: EASY (Conditionals Review)
            { id: 1, type: "SELECT", question: "If it rains, we ___ (stay) home.", options: [{ id: "a", text: "will stay", correct: true }, { id: "b", text: "stayed", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "If I _____ (be) you, I would take the job.", options: [{ id: "a", text: "were", correct: true }, { id: "b", text: "am", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Eğer param olsaydı yeni bir telefon alırdım.", correctAnswer: "If I had money, I would buy a new phone" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If you heat ice, it melts.", options: [{ id: "a", text: "Buzu ısıtırsan erir", correct: true }, { id: "b", text: "Buz ısınırsa soğur", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is a Type 1 conditional?", options: [{ id: "a", text: "If you study, you will pass.", correct: true }, { id: "b", text: "If you studied, you would pass.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Unless you _____ (hurry), you'll miss the bus.", options: [{ id: "a", text: "hurry", correct: true }, { id: "b", text: "don't hurry", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, gelirse gideriz.", correctAnswer: "I know, if he comes, we will go" },
            { id: 8, type: "SELECT", question: "Type 2 conditional is for:", options: [{ id: "a", text: "Imaginary present/future", correct: true }, { id: "b", text: "General truths", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "If I _____ (know) his number, I would call him.", options: [{ id: "a", text: "knew", correct: true }, { id: "b", text: "know", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "What would you do if you won the lottery?", options: [{ id: "a", text: "Piyangoyu kazansan ne yapardın?", correct: true }, { id: "b", text: "Piyangoyu ne zaman kazandın?", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Yardım edersen bitiririm.", correctAnswer: "If you help, I will finish" },
            { id: 12, type: "SELECT", question: "Which uses Type 0?", options: [{ id: "a", text: "Scientific facts", correct: true }, { id: "b", text: "Future possibilities", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "If I _____ (have) time tomorrow, I will visit you.", options: [{ id: "a", text: "have", correct: true }, { id: "b", text: "had", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onu görürsen bana söyle.", correctAnswer: "If you see him, tell me" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I would travel more if I were rich.", options: [{ id: "a", text: "Zengin olsaydım daha çok seyahat ederdim", correct: true }, { id: "b", text: "Zengin olduğumda seyahat ettim", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is more likely?", options: [{ id: "a", text: "Type 1", correct: true }, { id: "b", text: "Type 2", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "If she _____ (study) harder, she would succeed.", options: [{ id: "a", text: "studied", correct: true }, { id: "b", text: "studies", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gelmezsen başlarız.", correctAnswer: "If you don't come, we will start" },
            { id: 19, type: "SELECT", question: "Equivalent of 'Unless':", options: [{ id: "a", text: "If ... not", correct: true }, { id: "b", text: "Provided that", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "If you _____ (press) this button, the machine starts.", options: [{ id: "a", text: "press", correct: true }, { id: "b", text: "will press", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Type 3 & Mixed)
            { id: 1, type: "SELECT", question: "Type 3 refers to:", options: [{ id: "a", text: "Past regrets / Not possible anymore", correct: true }, { id: "b", text: "Future possibilities", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "If I _____ (see) you, I would have said hello.", options: [{ id: "a", text: "had seen", correct: true }, { id: "b", text: "saw", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Eğer çalışsaydım sınavı geçerdim.", correctAnswer: "If I had studied, I would have passed the exam" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If we had left earlier, we wouldn't have missed the flight.", options: [{ id: "a", text: "Daha erken ayrılsaydık uçağı kaçırmazdık", correct: true }, { id: "b", text: "Erken ayrıldık ama uçağı kaçırdık", correct: false }] },
            { id: 5, type: "SELECT", question: "Mixed Conditional: Past action, Present result:", options: [{ id: "a", text: "If I had taken the pill, I would be better now.", correct: true }, { id: "b", text: "If I took the pill, I would be better.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "If she _____ (not / forget) her keys, she wouldn't be locked out now.", options: [{ id: "a", text: "hadn't forgotten", correct: true }, { id: "b", text: "didn't forget", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, yardım etseydin bitirmiş olacaktım.", correctAnswer: "I know, if you had helped, I would have finished" },
            { id: 8, type: "SELECT", question: "Which is a Type 3 structure?", options: [{ id: "a", text: "If + had + V3, would + have + V3", correct: true }, { id: "b", text: "If + V2, would + V1", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "If I _____ (be) smarter, I wouldn't have made that mistake.", options: [{ id: "a", text: "were / had been (Mixed)", correct: true }, { id: "b", text: "am", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If you hadn't invited me, I wouldn't have come.", options: [{ id: "a", text: "Beni davet etmeseydin gelmezdim", correct: true }, { id: "b", text: "Davet etmeyi unuttun", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Erken kalsaydım yorgun olmazdım.", correctAnswer: "If I had slept earlier, I wouldn't be tired" },
            { id: 12, type: "SELECT", question: "Mixed Conditional: Present condition, Past result:", options: [{ id: "a", text: "If I weren't afraid of spiders, I would have picked it up.", correct: true }, { id: "b", text: "If I am not afraid, I pick it up.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "We _____ (arrive) on time if the traffic hadn't been so bad.", options: [{ id: "a", text: "would have arrived", correct: true }, { id: "b", text: "will arrive", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onu arasaydın gelirdi.", correctAnswer: "If you had called her, she would have come" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I would have told you if I had known.", options: [{ id: "a", text: "Bilseydim sana söylerdim", correct: true }, { id: "b", text: "Biliyordum ama söylemedim", correct: false }] },
            { id: 16, type: "SELECT", question: "Which sentence expresses a present result of a past condition?", options: [{ id: "a", text: "If I had saved money, I would be rich now.", correct: true }, { id: "b", text: "If I save money, I will be rich.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "If he _____ (not / lose) his job, he wouldn't be struggling.", options: [{ id: "a", text: "hadn't lost", correct: true }, { id: "b", text: "doesn't lose", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Dikkatli olsaydın kaza yapmazdın.", correctAnswer: "If you had been careful, you wouldn't have had an accident" },
            { id: 19, type: "SELECT", question: "Typical Type 3 consequence:", options: [{ id: "a", text: "Something that didn't happen", correct: true }, { id: "b", text: "Something that always happens", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "If it _____ (not / rain), we could have gone out.", options: [{ id: "a", text: "hadn't rained", correct: true }, { id: "b", text: "didn't rain", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Inversion)
            { id: 1, type: "SELECT", question: "Inversion of Type 1: 'Should you see him...' means:", options: [{ id: "a", text: "If you see him", correct: true }, { id: "b", text: "You should see him", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I known about the risk, I wouldn't have invested.", options: [{ id: "a", text: "Had", correct: true }, { id: "b", text: "If", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Daha fazla bilgiye ihtiyaç duyarsanız bizimle iletişime geçin.", correctAnswer: "Should you require further information, contact us" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had he worked harder, he would have succeeded.", options: [{ id: "a", text: "Daha çok çalışsaydı başarırdı", correct: true }, { id: "b", text: "Çok çalıştı ama başaramadı", correct: false }] },
            { id: 5, type: "SELECT", question: "Inversion of Type 2: 'Were I you...' means:", options: [{ id: "a", text: "If I were you", correct: true }, { id: "b", text: "I was you", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ it not for your help, I would have failed.", options: [{ id: "a", text: "Were", correct: true }, { id: "b", text: "Had", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Başkanı görseydim şaşırırdım.", correctAnswer: "Were I to see the president, I would be surprised" },
            { id: 8, type: "SELECT", question: "Which is the inversion of: 'If I had been there'?", options: [{ id: "a", text: "Had I been there", correct: true }, { id: "b", text: "Been I there", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ you change your mind, let us know.", options: [{ id: "a", text: "Should", correct: true }, { id: "b", text: "Were", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Were she here, she would know what to do.", options: [{ id: "a", text: "Burada olsa ne yapacağını bilirdi", correct: true }, { id: "b", text: "Buraya gelirse görecek", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "O olmasaydı ne yapardım?", correctAnswer: "Were it not for him, what would I do?" },
            { id: 12, type: "SELECT", question: "Negative inversion: 'If I hadn't gone' becomes:", options: [{ id: "a", text: "Had I not gone", correct: true }, { id: "b", text: "Hadn't I gone", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ you need any assistance, please call.", options: [{ id: "a", text: "Should", correct: true }, { id: "b", text: "Unless", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Senin yerinde olsaydım asla kabul etmezdim.", correctAnswer: "Were I in your shoes, I would never accept" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had I known, I would have come.", options: [{ id: "a", text: "Bilseydim gelirdim", correct: true }, { id: "b", text: "Biliyorum, geliyorum", correct: false }] },
            { id: 16, type: "SELECT", question: "Inversion of: 'If they were rich'?", options: [{ id: "a", text: "Were they rich", correct: true }, { id: "b", text: "They were rich", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ you win, what will you do?", options: [{ id: "a", text: "Should", correct: true }, { id: "b", text: "If", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Onun yardımı olmasaydı bitiremezdik.", correctAnswer: "Had it not been for his help, we couldn't have finished" },
            { id: 19, type: "SELECT", question: "Which is most formal?", options: [{ id: "a", text: "Inverted conditional", correct: true }, { id: "b", text: "Normal conditional", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ he to find out, he'd be furious.", options: [{ id: "a", text: "Were", correct: true }, { id: "b", text: "Had", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Nuances)
            { id: 1, type: "SELECT", question: "What does 'But for his help' mean?", options: [{ id: "a", text: "Yardımı olmasaydı", correct: true }, { id: "b", text: "Sadece yardımı için", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ you promise to be quiet, you can stay.", options: [{ id: "a", text: "Provided", correct: true }, { id: "b", text: "Unless", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Onun parası olmasaydı (but for).", correctAnswer: "But for his money" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Unless otherwise stated, the rules apply.", options: [{ id: "a", text: "Aksi belirtilmedikçe kurallar geçerlidir", correct: true }, { id: "b", text: "Kurallar belirtilmelidir", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'If only':", options: [{ id: "a", text: "Keşke / Güçlü dilek", correct: true }, { id: "b", text: "Sadece eğer", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I will go _____ it rains or not.", options: [{ id: "a", text: "whether", correct: true }, { id: "b", text: "if", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Zamanında varmamız şartıyla.", correctAnswer: "On condition that we arrive on time" },
            { id: 8, type: "SELECT", question: "Which indicates a condition?", options: [{ id: "a", text: "as long as", correct: true }, { id: "b", text: "due to", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ it rains, we'll have to cancel.", options: [{ id: "a", text: "Supposing", correct: true }, { id: "b", text: "Whereas", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Imagine what could happen if you failed.", options: [{ id: "a", text: "Başarısız olsan ne olabileceğini hayal et", correct: true }, { id: "b", text: "Başaracağını hayal et", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Aksi takdirde başın belaya girer.", correctAnswer: "Otherwise you will be in trouble" },
            { id: 12, type: "SELECT", question: "'Given that' vs 'If':", options: [{ id: "a", text: "Given that is more factual", correct: true }, { id: "b", text: "No difference", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ she were rich, she would buy a jet.", options: [{ id: "a", text: "If only", correct: true }, { id: "b", text: "But", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Senin varlığının dışında (but for your presence).", correctAnswer: "But for your presence" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Assuming that everything goes well.", options: [{ id: "a", text: "Her şeyin yolunda gittiğini varsayarsak", correct: true }, { id: "b", text: "Her şey bitti", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is a synonym for 'suppose'?", options: [{ id: "a", text: "assuming", correct: true }, { id: "b", text: "consequently", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ you say a word, I will leave.", options: [{ id: "a", text: "Should", correct: true }, { id: "b", text: "Unless", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Öyle olsa bile kabul etmezdim.", correctAnswer: "Even if that were the case, I wouldn't accept" },
            { id: 19, type: "SELECT", question: "'Whether ... or not' structure:", options: [{ id: "a", text: "Regardless of the condition", correct: true }, { id: "b", text: "Only if", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Take a jacket _____ it gets cold.", options: [{ id: "a", text: "in case", correct: true }, { id: "b", text: "if", correct: false }] }
        ]
    },
    198: {
        1: [ // QUIZ 1: EASY (Wish/If Only - Present)
            { id: 1, type: "SELECT", question: "I wish I ___ (be) rich.", options: [{ id: "a", text: "were", correct: true }, { id: "b", text: "am", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "If only I _____ (know) the answer now.", options: [{ id: "a", text: "knew", correct: true }, { id: "b", text: "know", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Keşke burada olsan.", correctAnswer: "I wish you were here" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If only it would stop raining.", options: [{ id: "a", text: "Keşke yağmur dursa", correct: true }, { id: "b", text: "Yağmur durdu", correct: false }] },
            { id: 5, type: "SELECT", question: "Wish for a future change:", options: [{ id: "a", text: "I wish he would come.", correct: true }, { id: "b", text: "I wish he came.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I wish I _____ (can) help you.", options: [{ id: "a", text: "could", correct: true }, { id: "b", text: "can", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Keşke daha çok zamanım olsa.", correctAnswer: "I wish I had more time" },
            { id: 8, type: "SELECT", question: "Structure of 'If only' (Present):", options: [{ id: "a", text: "If only + V2", correct: true }, { id: "b", text: "If only + will + V1", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He wishes he _____ (have) a better car.", options: [{ id: "a", text: "had", correct: true }, { id: "b", text: "has", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I wish you wouldn't shout.", options: [{ id: "a", text: "Keşke bağırmasan", correct: true }, { id: "b", text: "Bağırmanı istiyorum", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Keşke İngilizce bilsem.", correctAnswer: "I wish I knew English" },
            { id: 12, type: "SELECT", question: "When do we use 'would' with wish?", options: [{ id: "a", text: "To express annoyance / request change", correct: true }, { id: "b", text: "To express past regret", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "If only life _____ (be) like a movie.", options: [{ id: "a", text: "were", correct: true }, { id: "b", text: "is", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Keşke her gün tatil olsa.", correctAnswer: "I wish every day were a holiday" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If only I were taller.", options: [{ id: "a", text: "Keşke daha uzun olsaydım", correct: true }, { id: "b", text: "Uzun olduğumu biliyorum", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "I wish I were you.", correct: true }, { id: "b", text: "I wish I am you.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She wishes she _____ (not / have to) work.", options: [{ id: "a", text: "didn't have to", correct: true }, { id: "b", text: "not has to", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Keşke doğruyu söylesen.", correctAnswer: "I wish you would tell the truth" },
            { id: 19, type: "SELECT", question: "Equivalent of 'Keşke':", options: [{ id: "a", text: "I wish / If only", correct: true }, { id: "b", text: "Rather", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "If only I _____ (be) there.", options: [{ id: "a", text: "were", correct: true }, { id: "b", text: "am", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Wish/If Only - Past Regret)
            { id: 1, type: "SELECT", question: "I wish I ___ (not / eat) so much.", options: [{ id: "a", text: "hadn't eaten", correct: true }, { id: "b", text: "didn't eat", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "If only we _____ (leave) earlier.", options: [{ id: "a", text: "had left", correct: true }, { id: "b", text: "left", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Keşke onu arasaydım.", correctAnswer: "I wish I had called him" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I wish I had been more careful.", options: [{ id: "a", text: "Keşke daha dikkatli olsaydım", correct: true }, { id: "b", text: "Dikkatliydim", correct: false }] },
            { id: 5, type: "SELECT", question: "Past regret structure:", options: [{ id: "a", text: "wish + had + V3", correct: true }, { id: "b", text: "wish + V2", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "If only I _____ (not / say) that.", options: [{ id: "a", text: "hadn't said", correct: true }, { id: "b", text: "didn't say", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, keşke çalışsaydın.", correctAnswer: "I know, I wish you had studied" },
            { id: 8, type: "SELECT", question: "Which refers to the past?", options: [{ id: "a", text: "I wish the weather had been better.", correct: true }, { id: "b", text: "I wish the weather were better.", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She wishes she _____ (listen) to her parents.", options: [{ id: "a", text: "had listened", correct: true }, { id: "b", text: "listened", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If only they had told us the truth.", options: [{ id: "a", text: "Keşke bize doğruyu söyleselerdi", correct: true }, { id: "b", text: "Doğruyu biliyoruz", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Keşke yağmur yağmasaydı.", correctAnswer: "I wish it hadn't rained" },
            { id: 12, type: "SELECT", question: "Which indicates a finished action?", options: [{ id: "a", text: "I wish I had seen the movie.", correct: true }, { id: "b", text: "I wish I were seeing the movie.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I wish I _____ (be) there with you last night.", options: [{ id: "a", text: "had been", correct: true }, { id: "b", text: "were", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Keşke o kadar para harcamasaydım.", correctAnswer: "I wish I hadn't spent so much money" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If only I had known.", options: [{ id: "a", text: "Keşke bilseydim", correct: true }, { id: "b", text: "Biliyordum", correct: false }] },
            { id: 16, type: "SELECT", question: "Is Type 3 conditional related to Wish?", options: [{ id: "a", text: "Yes, both use had + V3 for past", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "They wish they _____ (buy) the house earlier.", options: [{ id: "a", text: "had bought", correct: true }, { id: "b", text: "bought", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Keşke daha erken kalsaydım.", correctAnswer: "I wish I had woken up earlier" },
            { id: 19, type: "SELECT", question: "Annoyance about the past:", options: [{ id: "a", text: "Not possible with 'would'", correct: true }, { id: "b", text: "Use would have", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "If only I _____ (not / lose) my passport.", options: [{ id: "a", text: "hadn't lost", correct: true }, { id: "b", text: "didn't lose", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (It's time / Would rather)
            { id: 1, type: "SELECT", question: "It's time we ___ (go) home.", options: [{ id: "a", text: "went", correct: true }, { id: "b", text: "go", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I'd rather you _____ (not / smoke) here.", options: [{ id: "a", text: "didn't smoke", correct: true }, { id: "b", text: "don't smoke", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gitmene vakti geldi.", correctAnswer: "It's time you left" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I would rather stay at home than go out.", options: [{ id: "a", text: "Dışarı çıkmaktansa evde kalmayı tercih ederim", correct: true }, { id: "b", text: "Evde kalmadım", correct: false }] },
            { id: 5, type: "SELECT", question: "'It's high time' is ___ than 'It's time'.", options: [{ id: "a", text: "more emphatic / slightly critical", correct: true }, { id: "b", text: "weaker", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "It's high time he _____ (find) a job.", options: [{ id: "a", text: "found", correct: true }, { id: "b", text: "finds", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Senin yerinde olmayı tercih ederdim (geçmiş).", correctAnswer: "I would rather have been in your shoes" },
            { id: 8, type: "SELECT", question: "I'd rather + Subject + ___:", options: [{ id: "a", text: "V2 (for present/future)", correct: true }, { id: "b", text: "V1", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I'd rather _____ (sleep) now.", options: [{ id: "a", text: "sleep (no subject context)", correct: true }, { id: "b", text: "slept", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's high time we started working.", options: [{ id: "a", text: "Çalışmaya başlamamızın vakti çoktan geldi", correct: true }, { id: "b", text: "Çalıştık", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Keşke bana sorsaydın (tercih ederdim).", correctAnswer: "I'd rather you had asked me" },
            { id: 12, type: "SELECT", question: "I'd rather + ___ (Past regret with different subject):", options: [{ id: "a", text: "had + V3", correct: true }, { id: "b", text: "V2", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It's time you _____ (tell) the truth.", options: [{ id: "a", text: "told", correct: true }, { id: "b", text: "tell", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Zevk almaktansa ölmeyi tercih ederim.", correctAnswer: "I would rather die than enjoy (contextual drama)" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'd rather not talk about it.", options: [{ id: "a", text: "Onun hakkında konuşmamayı tercih ederim", correct: true }, { id: "b", text: "Konuşalım", correct: false }] },
            { id: 16, type: "SELECT", question: "It's time + ___:", options: [{ id: "a", text: "is always followed by V2 or 'to + V1'", correct: true }, { id: "b", text: "never takes V2", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "You'd better _____ (go) now.", options: [{ id: "a", text: "go", correct: true }, { id: "b", text: "went", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Karar vermenizin vakti geldi.", correctAnswer: "It's time you made a decision" },
            { id: 19, type: "SELECT", question: "'Had better' implies:", options: [{ id: "a", text: "Advice / Warning", correct: true }, { id: "b", text: "Preference", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I'd rather _____ (have / stay) at home last night.", options: [{ id: "a", text: "have stayed", correct: true }, { id: "b", text: "stayed", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Suppose / As if)
            { id: 1, type: "SELECT", question: "Suppose you ___ (win) the lottery, what would you do?", options: [{ id: "a", text: "won", correct: true }, { id: "b", text: "win", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She talks as if she _____ (know) everything.", options: [{ id: "a", text: "knew", correct: true }, { id: "b", text: "knows (factual context)", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Sanki hayalet görmüş gibi görünüyor.", correctAnswer: "He looks as if he had seen a ghost" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Suppose we had lost the way.", options: [{ id: "a", text: "Farzet ki yolu kaybetmiştik", correct: true }, { id: "b", text: "Yolu bulduk", correct: false }] },
            { id: 5, type: "SELECT", question: "'As though' is a synonym for:", options: [{ id: "a", text: "As if", correct: true }, { id: "b", text: "Unless", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Imagine we _____ (live) on the moon.", options: [{ id: "a", text: "lived", correct: true }, { id: "b", text: "living", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Sanki hiçbir şey olmamış gibi davrandı.", correctAnswer: "He acted as though nothing had happened" },
            { id: 8, type: "SELECT", question: "Difference between 'as if + V2' and 'as if + had + V3':", options: [{ id: "a", text: "Present imaginary vs Past imaginary", correct: true }, { id: "b", text: "No difference", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Suppose he _____ (ask) you to marry him.", options: [{ id: "a", text: "asked", correct: true }, { id: "b", text: "asks", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He treats me as if I were a child.", options: [{ id: "a", text: "Bana bir çocukmuşum gibi davranıyor", correct: true }, { id: "b", text: "Bana iyi davranıyor", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Farzet ki (diyelim ki) o burada.", correctAnswer: "Suppose he is here / Suppose he were here" },
            { id: 12, type: "SELECT", question: "When 'as if' indicates a likely possibility:", options: [{ id: "a", text: "Use present tense", correct: true }, { id: "b", text: "Use past tense", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It looks as if it _____ (rain).", options: [{ id: "a", text: "is going to rain", correct: true }, { id: "b", text: "rained", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Sanki bir milyoner gibi harcıyor.", correctAnswer: "He spends money as if he were a millionaire" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't look at me as though I were guilty.", options: [{ id: "a", text: "Bana suçluymuşum gibi bakma", correct: true }, { id: "b", text: "Suçlu değilim", correct: false }] },
            { id: 16, type: "SELECT", question: "'Assuming' vs 'Suppose':", options: [{ id: "a", text: "Both can start a hypothetical question", correct: true }, { id: "b", text: "Assuming is only for future", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Imagine _____ (not / have) a phone.", options: [{ id: "a", text: "not having / if we didn't have", correct: true }, { id: "b", text: "to not have", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Sihirli bir değneğin olduğunu farzet.", correctAnswer: "Suppose you had a magic wand" },
            { id: 19, type: "SELECT", question: "'Would rather' (past ref for self):", options: [{ id: "a", text: "I'd rather have done it.", correct: true }, { id: "b", text: "I'd rather I did it.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "She wept as though her heart _____ (break).", options: [{ id: "a", text: "were breaking / would break (Past unreal)", correct: true }, { id: "b", text: "breaks", correct: false }] }
        ]
    },
    199: {
        1: [ // QUIZ 1: EASY (Reporting Verbs Review)
            { id: 1, type: "SELECT", question: "She told me she ___ (be) tired.", options: [{ id: "a", text: "was", correct: true }, { id: "b", text: "is", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (say) that he loved the movie.", options: [{ id: "a", text: "said", correct: true }, { id: "b", text: "told", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bana yalan söylediğini söyledi.", correctAnswer: "He told me he was lying" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She asked if I was coming.", options: [{ id: "a", text: "Gelip gelmeyeceğimi sordu", correct: true }, { id: "b", text: "Geldiğimi söyledi", correct: false }] },
            { id: 5, type: "SELECT", question: "'Tell' must be followed by:", options: [{ id: "a", text: "An object (person)", correct: true }, { id: "b", text: "That clause directly", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "They asked _____ I had seen the keys.", options: [{ id: "a", text: "if / whether", correct: true }, { id: "b", text: "that", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Nerede olduğunu sordu.", correctAnswer: "He asked where I was" },
            { id: 8, type: "SELECT", question: "Reported: 'I will help you' -> He said he ___ help me.", options: [{ id: "a", text: "would", correct: true }, { id: "b", text: "will", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (suggest) going to the park.", options: [{ id: "a", text: "suggested", correct: true }, { id: "b", text: "told", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He mentioned that he might be late.", options: [{ id: "a", text: "Geç kalabileceğini belirtti", correct: true }, { id: "b", text: "Geç kalmayacağını söyledi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Gitmemiz gerektiğini söyledi.", correctAnswer: "He said we should go" },
            { id: 12, type: "SELECT", question: "Reported: 'I am working' -> She said she ___.", options: [{ id: "a", text: "was working", correct: true }, { id: "b", text: "is working", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (explain) that the car was broken.", options: [{ id: "a", text: "explained", correct: true }, { id: "b", text: "told", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yardım edeceğine söz verdi.", correctAnswer: "He promised to help" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The doctor advised me to rest.", options: [{ id: "a", text: "Doktor dinlenmemi tavsiye etti", correct: true }, { id: "b", text: "Doktor dinlenmeyecek", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "He said me hello.", correct: false }, { id: "b", text: "He said hello to me.", correct: true }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (invite) him to the dinner.", options: [{ id: "a", text: "invited", correct: true }, { id: "b", text: "said", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gitmek isteyip istemediğimi sordu.", correctAnswer: "He asked if I wanted to go" },
            { id: 19, type: "SELECT", question: "Reported: 'I have seen it' -> He said he ___.", options: [{ id: "a", text: "had seen it", correct: true }, { id: "b", text: "has seen it", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (admit) making a mistake.", options: [{ id: "a", text: "admitted", correct: true }, { id: "b", text: "told", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Advanced Reporting Verbs)
            { id: 1, type: "SELECT", question: "He ___ (deny) stealing the money.", options: [{ id: "a", text: "denied", correct: true }, { id: "b", text: "refused", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "They _____ (threaten) to call the police.", options: [{ id: "a", text: "threatened", correct: true }, { id: "b", text: "warned", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Onu yapmayı reddetti.", correctAnswer: "He refused to do it" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The witness claimed to have seen the suspect.", options: [{ id: "a", text: "Tanık şüpheliyi gördüğünü iddia etti", correct: true }, { id: "b", text: "Tanık şüpheleniyordu", correct: false }] },
            { id: 5, type: "SELECT", question: "Structure of 'Warn':", options: [{ id: "a", text: "warn + person + (not) + to-infinitive", correct: true }, { id: "b", text: "warn + Ving", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (remind) me to buy milk.", options: [{ id: "a", text: "reminded", correct: true }, { id: "b", text: "remembered", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Müdür beni beklememi söyledi (re-stated).", correctAnswer: "The manager told me to wait" },
            { id: 8, type: "SELECT", question: "Which takes Ving?", options: [{ id: "a", text: "suggest", correct: true }, { id: "b", text: "offer", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (accuse) her of lying.", options: [{ id: "a", text: "accused", correct: true }, { id: "b", text: "blamed", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He apologized for being late.", options: [{ id: "a", text: "Geç kaldığı için özür diledi", correct: true }, { id: "b", text: "Geç kalacak", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Onu bitirmekte ısrar etti.", correctAnswer: "He insisted on finishing it" },
            { id: 12, type: "SELECT", question: "'Boast' means:", options: [{ id: "a", text: "Böbürlenmek", correct: true }, { id: "b", text: "Şikayet etmek", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (complain) about the service.", options: [{ id: "a", text: "complained", correct: true }, { id: "b", text: "boasted", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Sessiz kalmamız için yalvardı.", correctAnswer: "He begged us to stay quiet" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The company announced a new merger.", options: [{ id: "a", text: "Şirket yeni bir birleşme duyurdu", correct: true }, { id: "b", text: "Şirket battı", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is the reporting verb for a secret?", options: [{ id: "a", text: "whisper / reveal", correct: true }, { id: "b", text: "shout", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (encourage) me to apply for the job.", options: [{ id: "a", text: "encouraged", correct: true }, { id: "b", text: "prevented", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gerçeği itiraf etti.", correctAnswer: "He confessed the truth" },
            { id: 19, type: "SELECT", question: "Accuse + object + ___:", options: [{ id: "a", text: "of + Ving", correct: true }, { id: "b", text: "for + Ving", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (forbid) you to go out.", options: [{ id: "a", text: "forbid", correct: true }, { id: "b", text: "allow", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Narrative Sequence)
            { id: 1, type: "SELECT", question: "When reporting a past event in the past:", options: [{ id: "a", text: "Use Past Perfect", correct: true }, { id: "b", text: "Use Simple Past", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He said he _____ (arrive) an hour before.", options: [{ id: "a", text: "had arrived", correct: true }, { id: "b", text: "arrived", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Dün geleceğini söylemişti.", correctAnswer: "He said he would come yesterday" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They informed us that the flight had been cancelled.", options: [{ id: "a", text: "Uçağın iptal edildiğini bize bildirdiler", correct: true }, { id: "b", text: "Uçak kalktı", correct: false }] },
            { id: 5, type: "SELECT", question: "'The day before' is reporting for:", options: [{ id: "a", text: "Yesterday", correct: true }, { id: "b", text: "Tomorrow", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He asked where I _____ (be) the previous night.", options: [{ id: "a", text: "had been", correct: true }, { id: "b", text: "was", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Yorgun olduğumu varsaydı.", correctAnswer: "He assumed that I was tired" },
            { id: 8, type: "SELECT", question: "Reporting 'now' becomes:", options: [{ id: "a", text: "then", correct: true }, { id: "b", text: "that time", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The teacher _____ (conclude) that the test was hard.", options: [{ id: "a", text: "concluded", correct: true }, { id: "b", text: "thought", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He confirmed that he had received the email.", options: [{ id: "a", text: "E-postayı aldığını onayladı", correct: true }, { id: "b", text: "E-posta göndermedi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Gelecek hafta döneceğini söyledi.", correctAnswer: "He said he would return the following week" },
            { id: 12, type: "SELECT", question: "Backshift is NOT necessary if:", options: [{ id: "a", text: "The statement is still true", correct: true }, { id: "b", text: "It's formal", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (point out) that we were wrong.", options: [{ id: "a", text: "pointed out", correct: true }, { id: "b", text: "told", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, her şeyin bittiğini söyledi.", correctAnswer: "I know, he said it was all over" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She admitted having made a mistake.", options: [{ id: "a", text: "Hata yaptığını itiraf etti", correct: true }, { id: "b", text: "Hata yapmadığını söyledi", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is a synonym for 'The next day'?", options: [{ id: "a", text: "The following day", correct: true }, { id: "b", text: "The before day", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "They argued whether they _____ (should) leave.", options: [{ id: "a", text: "should", correct: true }, { id: "b", text: "shall", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Nasıl yapacağımı sordu.", correctAnswer: "He asked how I would do it" },
            { id: 19, type: "SELECT", question: "Reported 'Must' often becomes:", options: [{ id: "a", text: "had to", correct: true }, { id: "b", text: "must (stay the same)", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (wonder) why she was crying.", options: [{ id: "a", text: "wondered", correct: true }, { id: "b", text: "asked", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Reporting Modals/Conditionals)
            { id: 1, type: "SELECT", question: "Reported Type 2: 'If I were rich, I'd travel' -> He said if he were rich, he ___.", options: [{ id: "a", text: "would travel", correct: true }, { id: "b", text: "will travel", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She said she _____ (can) swim when she was five.", options: [{ id: "a", text: "could", correct: true }, { id: "b", text: "can", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gelmeyebileceğini belirtti.", correctAnswer: "He indicated that he might not come" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The lawyer advised that the contract be signed.", options: [{ id: "a", text: "Avukat sözleşmenin imzalanmasını tavsiye etti (Subjunctive)", correct: true }, { id: "b", text: "Avukat imzaladı", correct: false }] },
            { id: 5, type: "SELECT", question: "Reporting 'Shall' for suggestions:", options: [{ id: "a", text: "He suggested that we (should) go.", correct: true }, { id: "b", text: "He said we shall go.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (urge) us to be careful.", options: [{ id: "a", text: "urged", correct: true }, { id: "b", text: "told", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bana yalan söylemiş olabileceğini iddia etti.", correctAnswer: "He claimed that I might have lied" },
            { id: 8, type: "SELECT", question: "Reported: 'You should see a doctor' -> He advised me ___ a doctor.", options: [{ id: "a", text: "to see", correct: true }, { id: "b", text: "seeing", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (pledge) to support the cause.", options: [{ id: "a", text: "pledged", correct: true }, { id: "b", text: "said", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The report suggested that the economy was recovering.", options: [{ id: "a", text: "Rapor ekonominin düzeldiğini öne sürdü", correct: true }, { id: "b", text: "Ekonomi battı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Onu yapmamı yasakladı.", correctAnswer: "He forbade me to do it" },
            { id: 12, type: "SELECT", question: "Reporting 'Could' (Past ability):", options: [{ id: "a", text: "Stays 'could'", correct: true }, { id: "b", text: "Becomes 'had been able to'", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "They _____ (stipulate) that the work must be done by noon.", options: [{ id: "a", text: "stipulated", correct: true }, { id: "b", text: "said", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Sanki hiçbir şey olmamış gibi davrandı.", correctAnswer: "He acted as if nothing had happened" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He remarked on how much she had grown.", options: [{ id: "a", text: "Ne kadar büyüdüğü hakkında yorum yaptı", correct: true }, { id: "b", text: "Büyüdüğünü gördü", correct: false }] },
            { id: 16, type: "SELECT", question: "Reported Type 3: 'If I had known, I would have told you' -> He said ___.", options: [{ id: "a", text: "No change in tenses", correct: true }, { id: "b", text: "Change to past perfect", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (vow) never to return.", options: [{ id: "a", text: "vowed", correct: true }, { id: "b", text: "promised", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gerektiğinde yardım edeceğine söz verdi.", correctAnswer: "He promised to help when necessary" },
            { id: 19, type: "SELECT", question: "Reporting 'May' (Possibility):", options: [{ id: "a", text: "might", correct: true }, { id: "b", text: "may", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The judge _____ (ruling) that the evidence was inadmissible.", options: [{ id: "a", text: "ruled", correct: true }, { id: "b", text: "said", correct: false }] }
        ]
    },
    200: {
        1: [ // QUIZ 1: EASY (Review 191-193)
            { id: 1, type: "SELECT", question: "Which is Past Perfect Continuous?", options: [{ id: "a", text: "had been working", correct: true }, { id: "b", text: "will have worked", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "By next month, I _____ (finish) the course.", options: [{ id: "a", text: "will have finished", correct: true }, { id: "b", text: "had finished", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Baklayı ağzından çıkar.", correctAnswer: "Let the cat out of the bag" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He had been waiting for an hour.", options: [{ id: "a", text: "Bir saattir bekliyordu", correct: true }, { id: "b", text: "Bir saat sonra bekleyecek", correct: false }] },
            { id: 5, type: "SELECT", question: "Future Perfect use:", options: [{ id: "a", text: "Action finished before a future point", correct: true }, { id: "b", text: "Continuous action in past", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (drive) since 8 AM when I saw the accident.", options: [{ id: "a", text: "had been driving", correct: true }, { id: "b", text: "would drive", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Gelecek yıla kadar mezun olmuş olacağım.", correctAnswer: "I will have graduated by next year" },
            { id: 8, type: "SELECT", question: "'Elephant in the room' means:", options: [{ id: "a", text: "A big problem everyone ignores", correct: true }, { id: "b", text: "A large animal", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (study) for hours before she fell asleep.", options: [{ id: "a", text: "had been studying", correct: true }, { id: "b", text: "has studied", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't count your chickens.", options: [{ id: "a", text: "Dereyi görmeden paçaları sıvama", correct: true }, { id: "b", text: "Tavukları saymak zordur", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Yarın bu vakitte uyuyor olacağım (Process).", correctAnswer: "I will be sleeping at this time tomorrow" },
            { id: 12, type: "SELECT", question: "Which denotes a completed future result?", options: [{ id: "a", text: "Future Perfect", correct: true }, { id: "b", text: "Future Continuous", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The ground was wet; it _____ (rain).", options: [{ id: "a", text: "had been raining", correct: true }, { id: "b", text: "will have rained", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "O bir fare kadar sessiz.", correctAnswer: "She is as quiet as a mouse" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Will you have arrived by then?", options: [{ id: "a", text: "O vakte kadar varmış olacak mısın?", correct: true }, { id: "b", text: "Ne zaman varacaksın?", correct: false }] },
            { id: 16, type: "SELECT", question: "Past Perfect Continuous structure:", options: [{ id: "a", text: "had been + Ving", correct: true }, { id: "b", text: "has been + Ving", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "By the end of the year, they _____ (live) here for a decade.", options: [{ id: "a", text: "will have been living", correct: true }, { id: "b", text: "live", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bekliyordum (geçmişte süreç).", correctAnswer: "I had been waiting" },
            { id: 19, type: "SELECT", question: "Which idiom means 'rarely'?", options: [{ id: "a", text: "Once in a blue moon", correct: true }, { id: "b", text: "Piece of cake", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "It's raining cats and _____.", options: [{ id: "a", text: "dogs", correct: true }, { id: "b", text: "frogs", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Review 194-196)
            { id: 1, type: "SELECT", question: "'Give up' means:", options: [{ id: "a", text: "Quit", correct: true }, { id: "b", text: "Climb", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ it was raining, we went for a walk.", options: [{ id: "a", text: "Although / Even though", correct: true }, { id: "b", text: "Despite", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Eğer yerinde olsaydım giderdim.", correctAnswer: "If I were you, I would go" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'm looking forward to meeting you.", options: [{ id: "a", text: "Seninle tanışmayı dört gözle bekliyorum", correct: true }, { id: "b", text: "Görüşmek üzere", correct: false }] },
            { id: 5, type: "SELECT", question: "Which passive is correct for 'They are building a school'?", options: [{ id: "a", text: "A school is being built.", correct: true }, { id: "b", text: "A school is built.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I ran _____ of time.", options: [{ id: "a", text: "out", correct: true }, { id: "b", text: "off", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Hava soğuk olmasına rağmen dışarı çıktık.", correctAnswer: "Even though it was cold, we went out" },
            { id: 8, type: "SELECT", question: "Type 3 Case: If I ___ (know), I ___ (tell) you.", options: [{ id: "a", text: "had known / would have told", correct: true }, { id: "b", text: "knew / would tell", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The book was _____ (write) by a famous author.", options: [{ id: "a", text: "written", correct: true }, { id: "b", text: "write", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Take off your coat.", options: [{ id: "a", text: "Ceketini çıkar", correct: true }, { id: "b", text: "Ceketini giy", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, her şey tamir edildi.", correctAnswer: "I know, everything was repaired" },
            { id: 12, type: "SELECT", question: "Which conjunction indicates result?", options: [{ id: "a", text: "Therefore / Consequently", correct: true }, { id: "b", text: "However", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "She doesn't like coffee, _____ does she like tea.", options: [{ id: "a", text: "nor", correct: true }, { id: "b", text: "or", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onu uydurdun.", correctAnswer: "You made it up" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Despite the fact that he was tired.", options: [{ id: "a", text: "Yorgun olmasına rağmen", correct: true }, { id: "b", text: "Yorgunluk bir gerçek", correct: false }] },
            { id: 16, type: "SELECT", question: "If I _____ (be) you, I'd stay.", options: [{ id: "a", text: "were", correct: true }, { id: "b", text: "am", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "We must put _____ the meeting.", options: [{ id: "a", text: "off", correct: true }, { id: "b", text: "up", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Ona güvenemezsin.", correctAnswer: "You can't count on him" },
            { id: 19, type: "SELECT", question: "Passive for 'He will fix it':", options: [{ id: "a", text: "It will be fixed.", correct: true }, { id: "b", text: "It will fix.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Neither John _____ Mary arrived.", options: [{ id: "a", text: "nor", correct: true }, { id: "b", text: "or", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Review 197-198)
            { id: 1, type: "SELECT", question: "Causative structure: 'I had my car ___ (repair).'", options: [{ id: "a", text: "repaired", correct: true }, { id: "b", text: "repair", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I wish I _____ (know) the truth before.", options: [{ id: "a", text: "had known", correct: true }, { id: "b", text: "knew", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Sanki hayalet görmüş gibi görünüyor.", correctAnswer: "He looks as if he had seen a ghost" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had I known, I would have warned you.", options: [{ id: "a", text: "Bilseydim seni uyarırdım (Inversion)", correct: true }, { id: "b", text: "Uyarıyı duydun mu?", correct: false }] },
            { id: 5, type: "SELECT", question: "Personal passive: 'He is said ___ (be) rich.'", options: [{ id: "a", text: "to be", correct: true }, { id: "b", text: "being", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I got him _____ (sign) the contract.", options: [{ id: "a", text: "to sign", correct: true }, { id: "b", text: "sign", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Keşke burada olsaydı (geçmiş).", correctAnswer: "I wish he had been here" },
            { id: 8, type: "SELECT", question: "Inversion of 'If you need help':", options: [{ id: "a", text: "Should you need help", correct: true }, { id: "b", text: "Need you help", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I'd rather you _____ (not / go) out tonight.", options: [{ id: "a", text: "didn't go", correct: true }, { id: "b", text: "don't go", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's high time you found a job.", options: [{ id: "a", text: "İş bulmanın vakti çoktan geldi", correct: true }, { id: "b", text: "Yüksek bir iş buldun", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Evi boyattım.", correctAnswer: "I had the house painted" },
            { id: 12, type: "SELECT", question: "Which is a causative with 'get'?", options: [{ id: "a", text: "get someone to do something", correct: true }, { id: "b", text: "get someone do something", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "If only she _____ (listen) to me then.", options: [{ id: "a", text: "had listened", correct: true }, { id: "b", text: "listened", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Sihirli bir değneğin olduğunu farzet.", correctAnswer: "Suppose you had a magic wand" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Were I you, I wouldn't do it.", options: [{ id: "a", text: "Sen olsaydım yapmazdım", correct: true }, { id: "b", text: "Sen yapamazsın", correct: false }] },
            { id: 16, type: "SELECT", question: "Passive of 'I hate people laughing at me':", options: [{ id: "a", text: "I hate being laughed at.", correct: true }, { id: "b", text: "I hate laughed at.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The building is alleged _____ (be) haunted.", options: [{ id: "a", text: "to be", correct: true }, { id: "b", text: "being", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gözlerimi muayene ettirmem lazım.", correctAnswer: "I need to have my eyes tested" },
            { id: 19, type: "SELECT", question: "Which indicates past regret in wish?", options: [{ id: "a", text: "wish + had + V3", correct: true }, { id: "b", text: "wish + V2", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "It's time we _____ (leave).", options: [{ id: "a", text: "left", correct: true }, { id: "b", text: "go", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Review & Integration)
            { id: 1, type: "SELECT", question: "Reported: 'I will go' -> He said he ___ go.", options: [{ id: "a", text: "would", correct: true }, { id: "b", text: "will", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (accuse) me of stealing.", options: [{ id: "a", text: "accused", correct: true }, { id: "b", text: "denied", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Geç kaldığı için özür diledi.", correctAnswer: "He apologized for being late" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She denied having seen the document.", options: [{ id: "a", text: "Dokümanı gördüğünü reddetti", correct: true }, { id: "b", text: "Dokümanı gördüğünü itiraf etti", correct: false }] },
            { id: 5, type: "SELECT", question: "Reported 'Must' often becomes:", options: [{ id: "a", text: "had to", correct: true }, { id: "b", text: "should", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "They suggested _____ (go) to the cinema.", options: [{ id: "a", text: "going", correct: true }, { id: "b", text: "to go", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Nereye gittiğimi sordu.", correctAnswer: "He asked where I was going" },
            { id: 8, type: "SELECT", question: "Mixed Conditional: If I ___ (be) you, I ___ (accept) it yesterday.", options: [{ id: "a", text: "were / would have accepted", correct: true }, { id: "b", text: "had been / would accept", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (remind) me to call my mom.", options: [{ id: "a", text: "reminded", correct: true }, { id: "b", text: "recalled", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He claimed that he was innocent.", options: [{ id: "a", text: "Masum olduğunu iddia etti", correct: true }, { id: "b", text: "Suçlu olduğunu söyledi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum, her şeyin bittiğini fısıldadı.", correctAnswer: "I know, he whispered that it was all over" },
            { id: 12, type: "SELECT", question: "Reported 'this' becomes:", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "this", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (threaten) to leave.", options: [{ id: "a", text: "threatened", correct: true }, { id: "b", text: "begged", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Gitmek isteyip istemediğimi sordu.", correctAnswer: "He asked if I wanted to go" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The report pointed out several errors.", options: [{ id: "a", text: "Rapor birkaç hataya işaret etti", correct: true }, { id: "b", text: "Rapor hatasızdı", correct: false }] },
            { id: 16, type: "SELECT", question: "Inversion for Type 3:", options: [{ id: "a", text: "Had I known...", correct: true }, { id: "b", text: "Known had I...", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (promise) to be there.", options: [{ id: "a", text: "promised", correct: true }, { id: "b", text: "promise", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Sanki beni tanımıyormuş gibi görünüyor.", correctAnswer: "He looks as if he didn't know me" },
            { id: 19, type: "SELECT", question: "Which is most formal?", options: [{ id: "a", text: "He revealed the truth.", correct: true }, { id: "b", text: "He said the truth.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "By the end of the day, I _____ (work) for 10 hours.", options: [{ id: "a", text: "will have been working", correct: true }, { id: "b", text: "worked", correct: false }] }
        ]
    }
};
