import { Question } from '../../questions';

export const u201_205: Record<number, Record<number, Question[]>> = {
    201: {
        1: [ // QUIZ 1: EASY (Relative Pronouns: Who/Which/That)
            { id: 1, type: "SELECT", question: "The man ___ lives next door is a doctor.", options: [{ id: "a", text: "who", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The book _____ I bought yesterday is interesting.", options: [{ id: "a", text: "which / that", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bana yardım eden kadın öğretmen.", correctAnswer: "The woman who helped me is a teacher" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The car that he sold was old.", options: [{ id: "a", text: "Sattığı araba eskiydi", correct: true }, { id: "b", text: "Arabayı satacak", correct: false }] },
            { id: 5, type: "SELECT", question: "Use 'which' for:", options: [{ id: "a", text: "Things", correct: true }, { id: "b", text: "People", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The movie _____ we saw was great.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Burada çalışan adamı tanıyor musun?", correctAnswer: "Do you know the man who works here?" },
            { id: 8, type: "SELECT", question: "Relative pronoun for people:", options: [{ id: "a", text: "who", correct: true }, { id: "b", text: "where", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The house _____ is on the corner belongs to me.", options: [{ id: "a", text: "which / that", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I found the keys which I had lost.", options: [{ id: "a", text: "Kaybettiğim anahtarları buldum", correct: true }, { id: "b", text: "Anahtarları kaybettim", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Konuşan çocuk kardeşim.", correctAnswer: "The boy who is speaking is my brother" },
            { id: 12, type: "SELECT", question: "Can 'that' replace 'who' in defining clauses?", options: [{ id: "a", text: "Yes", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The restaurant _____ we visited was expensive.", options: [{ id: "a", text: "which", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Masadaki kalem benim.", correctAnswer: "The pen which is on the table is mine" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "People who exercise live longer.", options: [{ id: "a", text: "Egzersiz yapan insanlar daha uzun yaşar", correct: true }, { id: "b", text: "İnsanlar egzersiz yapmalı", correct: false }] },
            { id: 16, type: "SELECT", question: "The laptop ___ I use is new.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "whom", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The girl _____ is standing there is my cousin.", options: [{ id: "a", text: "who", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bozulan bilgisayarı tamir ettim.", correctAnswer: "I fixed the computer which broke down" },
            { id: 19, type: "SELECT", question: "Relative pronoun for a subject person:", options: [{ id: "a", text: "who", correct: true }, { id: "b", text: "whose", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "This is the cat _____ stole the fish.", options: [{ id: "a", text: "that / which", correct: true }, { id: "b", text: "who", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Whose/Whom/Where/When)
            { id: 1, type: "SELECT", question: "The boy ___ bike was stolen is crying.", options: [{ id: "a", text: "whose", correct: true }, { id: "b", text: "whom", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "That's the school _____ I studied.", options: [{ id: "a", text: "where", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Kimin arabası olduğunu bilmiyorum.", correctAnswer: "I don't know whose car it is" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The man to whom I was speaking was very kind.", options: [{ id: "a", text: "Konuştuğum adam çok nazikti", correct: true }, { id: "b", text: "Konuşacak birini buldum", correct: false }] },
            { id: 5, type: "SELECT", question: "Use 'whose' for:", options: [{ id: "a", text: "Possession", correct: true }, { id: "b", text: "Place", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I remember the day _____ we met.", options: [{ id: "a", text: "when", correct: true }, { id: "b", text: "where", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Annesi doktor olan çocuk geldi.", correctAnswer: "The boy whose mother is a doctor arrived" },
            { id: 8, type: "SELECT", question: "Relative pronoun for time:", options: [{ id: "a", text: "when", correct: true }, { id: "b", text: "why", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "This is the reason _____ I am late.", options: [{ id: "a", text: "why", correct: true }, { id: "b", text: "where", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Summer is the season when people go on holiday.", options: [{ id: "a", text: "Yaz, insanların tatile gittiği mevsimdir", correct: true }, { id: "b", text: "Yazın tatile gideceğiz", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Doğduğum şehri seviyorum.", correctAnswer: "I love the city where I was born" },
            { id: 12, type: "SELECT", question: "'Whom' is used for:", options: [{ id: "a", text: "Object person (formal/after prep)", correct: true }, { id: "b", text: "Subject person", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The building _____ they live is old.", options: [{ id: "a", text: "where", correct: true }, { id: "b", text: "whose", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Kiminle konuştuğunu biliyorum.", correctAnswer: "I know with whom you were speaking" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is the author whose books are famous.", options: [{ id: "a", text: "O, kitapları ünlü olan yazardır", correct: true }, { id: "b", text: "Kitapları yazan odur", correct: false }] },
            { id: 16, type: "SELECT", question: "The lady ___ dog is barking is my neighbor.", options: [{ id: "a", text: "whose", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "That was the time _____ I felt happiest.", options: [{ id: "a", text: "when", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bu, neden gitmemiz gerektiği (re-stated).", correctAnswer: "This is why we should go" },
            { id: 19, type: "SELECT", question: "Relative pronoun for places:", options: [{ id: "a", text: "where", correct: true }, { id: "b", text: "when", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "To _____ was this letter written?", options: [{ id: "a", text: "whom", correct: true }, { id: "b", text: "who", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Defining vs Non-defining)
            { id: 1, type: "SELECT", question: "Which relative clause uses commas?", options: [{ id: "a", text: "Non-defining", correct: true }, { id: "b", text: "Defining", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "My brother, _____ lives in London, is an artist.", options: [{ id: "a", text: "who", correct: true }, { id: "b", text: "that (incorrect with commas)", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Londra, ki İngiltere'nin başkentidir, büyük bir şehirdir.", correctAnswer: "London, which is the capital of England, is a big city" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The car, which cost a fortune, is now broken.", options: [{ id: "a", text: "Bir servete mal olan araba şimdi bozuk", correct: true }, { id: "b", text: "Arabayı tamir ettim", correct: false }] },
            { id: 5, type: "SELECT", question: "In which case can you NOT use 'that'?", options: [{ id: "a", text: "Non-defining relative clauses", correct: true }, { id: "b", text: "Defining relative clauses", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "His latest book, _____ I haven't read, is a bestseller.", options: [{ id: "a", text: "which", correct: true }, { id: "b", text: "that", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Dün gördüğümüz adam yardımseverdi.", correctAnswer: "The man (who/whom) we saw yesterday was helpful" },
            { id: 8, type: "SELECT", question: "When can a relative pronoun be omitted?", options: [{ id: "a", text: "When it is the object of the clause (Defining only)", correct: true }, { id: "b", text: "Always", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The hotel _____ we stayed at was very comfortable.", options: [{ id: "a", text: "which / that / (blank)", correct: true }, { id: "b", text: "where", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "My uncle, whose house was destroyed, is staying with us.", options: [{ id: "a", text: "Evi yıkılan amcam bizimle kalıyor", correct: true }, { id: "b", text: "Amcamın evi çok güzel", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu, tanıştığım en iyi insan.", correctAnswer: "This is the best person that I've met" },
            { id: 12, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "Everything that he said was true.", correct: true }, { id: "b", text: "Everything which he said was true.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The only thing _____ matters is honesty.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "what", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Ona her şeyi anlattım, ki bu bir hataydı.", correctAnswer: "I told him everything, which was a mistake" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He failed the exam, which surprised everyone.", options: [{ id: "a", text: "Sınavda kaldı, ki bu herkesi şaşırttı", correct: true }, { id: "b", text: "Herkes şaşırdı", correct: false }] },
            { id: 16, type: "SELECT", question: "Relative pronoun referring to a whole sentence:", options: [{ id: "a", text: "which", correct: true }, { id: "b", text: "that", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Rome, _____ is a beautiful city, attracts many tourists.", options: [{ id: "a", text: "which", correct: true }, { id: "b", text: "that", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Hakkında konuştuğumuz kitap bu.", correctAnswer: "This is the book (which) we were talking about" },
            { id: 19, type: "SELECT", question: "Commas in: 'My mother ___ is 60 travels a lot.'", options: [{ id: "a", text: ", who is 60, (Non-defining)", correct: true }, { id: "b", text: "who is 60 (Defining)", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The reason _____ she left is unknown.", options: [{ id: "a", text: "why", correct: true }, { id: "b", text: "which", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Reduced Relative Clauses)
            { id: 1, type: "SELECT", question: "Reduced: 'The man talking to her is my boss' = 'The man ___ is talking...'", options: [{ id: "a", text: "who", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The items _____ (send) yesterday arrived today.", options: [{ id: "a", text: "sent", correct: true }, { id: "b", text: "sending", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Dışarıda bekleyen insanlar sabırsızlanıyor.", correctAnswer: "The people waiting outside are getting impatient" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The letter, written in haste, contained many errors.", options: [{ id: "a", text: "Aceleyle yazılan mektup birçok hata içeriyordu", correct: true }, { id: "b", text: "Mektubu aceleyle yazdım", correct: false }] },
            { id: 5, type: "SELECT", question: "Reduction: Use Ving for:", options: [{ id: "a", text: "Active meanings", correct: true }, { id: "b", text: "Passive meanings", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Most of the people _____ (invite) to the party didn't come.", options: [{ id: "a", text: "invited", correct: true }, { id: "b", text: "inviting", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Okunan kitap çok eskiydi.", correctAnswer: "The book being read was very old" },
            { id: 8, type: "SELECT", question: "Reduction: Use Past Participle (V3) for:", options: [{ id: "a", text: "Passive meanings", correct: true }, { id: "b", text: "Active meanings", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The candidates _____ (apply) for the job were interviewed.", options: [{ id: "a", text: "applying", correct: true }, { id: "b", text: "applied", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The car parked in front of the house is mine.", options: [{ id: "a", text: "Evin önüne park edilmiş araba benim", correct: true }, { id: "b", text: "Arabayı park ettim", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu konuda yapılan çalışmalar kısıtlı.", correctAnswer: "The studies carried out on this subject are limited" },
            { id: 12, type: "SELECT", question: "Complete: 'A woman ___ (wear) a red dress came in.'", options: [{ id: "a", text: "wearing", correct: true }, { id: "b", text: "wore", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The building _____ (construct) now will be a school.", options: [{ id: "a", text: "being constructed", correct: true }, { id: "b", text: "constructing", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Toplantıda sunulan fikirler ilginçti.", correctAnswer: "The ideas presented at the meeting were interesting" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "None of the people contacted were interested.", options: [{ id: "a", text: "İletişime geçilen kişilerin hiçbirinin ilgisi yoktu", correct: true }, { id: "b", text: "İletişim kuramadık", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is a correct reduction?", options: [{ id: "a", text: "The man standing there.", correct: true }, { id: "b", text: "The man stand there.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The task _____ (complete) by him was difficult.", options: [{ id: "a", text: "completed", correct: true }, { id: "b", text: "completing", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Kullanılan malzemeler kaliteli.", correctAnswer: "The materials used are of high quality" },
            { id: 19, type: "SELECT", question: "Reduced form of 'The students who are working hard':", options: [{ id: "a", text: "The students working hard", correct: true }, { id: "b", text: "The students worked hard", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The girl _____ (win) the race is my sister.", options: [{ id: "a", text: "winning", correct: true }, { id: "b", text: "won", correct: false }] }
        ]
    },
    202: {
        1: [ // QUIZ 1: EASY (Clauses of Purpose: so that, in order to)
            { id: 1, type: "SELECT", question: "I went to the bank ___ get some money.", options: [{ id: "a", text: "to / in order to", correct: true }, { id: "b", text: "for", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He turned off the TV _____ he could sleep.", options: [{ id: "a", text: "so that", correct: true }, { id: "b", text: "to", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Unutmamak için not aldım.", correctAnswer: "I took notes so as not to forget" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She studied hard in order to pass the exam.", options: [{ id: "a", text: "Sınavı geçmek için sıkı çalıştı", correct: true }, { id: "b", text: "Sınavı geçti", correct: false }] },
            { id: 5, type: "SELECT", question: "Negative purpose: 'I left early ___ be late.'", options: [{ id: "a", text: "so as not to", correct: true }, { id: "b", text: "to not", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I'll lend you the book _____ you can read it.", options: [{ id: "a", text: "so that", correct: true }, { id: "b", text: "in order to", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Kilo vermek için diyete başladı.", correctAnswer: "She started a diet to lose weight" },
            { id: 8, type: "SELECT", question: "'So that' is usually followed by:", options: [{ id: "a", text: "A subject + modal verb (can/could)", correct: true }, { id: "b", text: "An infinitive", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I wore a coat _____ not to catch a cold.", options: [{ id: "a", text: "so as", correct: true }, { id: "b", text: "so that", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He whispered so that no one would hear him.", options: [{ id: "a", text: "Kimse duymasın diye fısıldadı", correct: true }, { id: "b", text: "Kimse duymadı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Seni görmek için geldim.", correctAnswer: "I came in order to see you" },
            { id: 12, type: "SELECT", question: "Which is correct for 'for'?", options: [{ id: "a", text: "for + Ving (function/purpose of a thing)", correct: true }, { id: "b", text: "for + to + V1", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "This knife is _____ cutting bread.", options: [{ id: "a", text: "for", correct: true }, { id: "b", text: "to", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Daha iyi duymak için yaklaştı.", correctAnswer: "He moved closer so that he could hear better" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They hurried so as not to miss the train.", options: [{ id: "a", text: "Tren kaçırmamak için acele ettiler", correct: true }, { id: "b", text: "Tren kaçtı", correct: false }] },
            { id: 16, type: "SELECT", question: "I'm saving money ___ buy a car.", options: [{ id: "a", text: "to / for the purpose of buying", correct: true }, { id: "b", text: "so as", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Speak clearly _____ everyone can understand.", options: [{ id: "a", text: "so that", correct: true }, { id: "b", text: "to", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Yağmur yağar diye şemsiye aldım (purpose-like).", correctAnswer: "I took an umbrella in case it rains" },
            { id: 19, type: "SELECT", question: "Purpose with different subjects:", options: [{ id: "a", text: "Use 'so that'", correct: true }, { id: "b", text: "Use 'to + infinitive'", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He stayed at home _____ avoid the crowd.", options: [{ id: "a", text: "to / in order to", correct: true }, { id: "b", text: "so that", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Clauses of Result: so...that, such...that)
            { id: 1, type: "SELECT", question: "He was ___ tired that he fell asleep instantly.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "It was _____ a cold day that we stayed inside.", options: [{ id: "a", text: "such", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Öyle hızlı koştu ki onu yakalayamadım.", correctAnswer: "He ran so fast that I couldn't catch him" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They are such nice people that everyone loves them.", options: [{ id: "a", text: "Öyle nazik insanlar ki herkes onları seviyor", correct: true }, { id: "b", text: "Onları sevmeyen yok", correct: false }] },
            { id: 5, type: "SELECT", question: "Structure of 'Such':", options: [{ id: "a", text: "such + (a/an) + adjective + noun + that", correct: true }, { id: "b", text: "such + adjective + that", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "There was _____ much noise that I couldn't concentrate.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "O kadar çok yedi ki midesi ağrıdı.", correctAnswer: "He ate so much that his stomach hurt" },
            { id: 8, type: "SELECT", question: "Structure of 'So':", options: [{ id: "a", text: "so + adjective/adverb + that", correct: true }, { id: "b", text: "so + noun + that", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "It is _____ a beautiful dress that I will buy it.", options: [{ id: "a", text: "such", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The music was so loud that we couldn't talk.", options: [{ id: "a", text: "Müzik o kadar yüksekti ki konuşamadık", correct: true }, { id: "b", text: "Müzik çok güzeldi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Öyle büyük bir kutuydu ki kimse taşıyamadı.", correctAnswer: "It was such a big box that no one could carry it" },
            { id: 12, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "The movie was so boring that we left.", correct: true }, { id: "b", text: "The movie was such boring that we left.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "She has _____ little time that she can't watch TV.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Öyle harika bir fikir ki bu!", correctAnswer: "It is such a wonderful idea" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I had so many things to do that I forgot to call you.", options: [{ id: "a", text: "Yapacak o kadar çok şeyim vardı ki seni aramayı unuttum", correct: true }, { id: "b", text: "Senin için çok şey yaptım", correct: false }] },
            { id: 16, type: "SELECT", question: "___ + many/few/much/little + noun + that:", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It was _____ a small room that there was no space for a bed.", options: [{ id: "a", text: "such", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Hava o kadar sıcaktı ki dışarı çıkamadık.", correctAnswer: "The weather was so hot that we couldn't go out" },
            { id: 19, type: "SELECT", question: "Result with 'Therefore':", options: [{ id: "a", text: "It rained; therefore, the game was cancelled.", correct: true }, { id: "b", text: "Therefore it rained.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The book was _____ interesting that I finished it in one day.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Clauses of Reason: because of, due to)
            { id: 1, type: "SELECT", question: "We didn't go out ___ the rain.", options: [{ id: "a", text: "because of", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The accident was _____ to the ice on the road.", options: [{ id: "a", text: "due", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gürültü yüzünden uyuyamadım.", correctAnswer: "I couldn't sleep because of the noise" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Owing to lack of money, the project was halted.", options: [{ id: "a", text: "Para eksikliği nedeniyle proje durduruldu", correct: true }, { id: "b", text: "Para eksik değildi", correct: false }] },
            { id: 5, type: "SELECT", question: "Which must be followed by a full clause (subject + verb)?", options: [{ id: "a", text: "because / since / as", correct: true }, { id: "b", text: "because of / due to", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ to heavy traffic, I was late.", options: [{ id: "a", text: "Due / Owing", correct: true }, { id: "b", text: "Because", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Dürüstlüğü için ona teşekkür ettim.", correctAnswer: "I thanked him for his honesty" },
            { id: 8, type: "SELECT", question: "Which is more formal?", options: [{ id: "a", text: "Owing to / Due to", correct: true }, { id: "b", text: "Because of", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I stayed at home _____ I was sick.", options: [{ id: "a", text: "because", correct: true }, { id: "b", text: "because of", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "On account of his illness, he couldn't attend.", options: [{ id: "a", text: "Hastalığı sebebiyle katılamadı", correct: true }, { id: "b", text: "Hastalığı geçti", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Yoğun sis nedeniyle uçuşlar iptal edildi.", correctAnswer: "Flights were cancelled due to heavy fog" },
            { id: 12, type: "SELECT", question: "Use 'Considering' for:", options: [{ id: "a", text: "Giving a reason based on circumstances", correct: true }, { id: "b", text: "Purpose", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ that he is only ten, he plays the piano very well.", options: [{ id: "a", text: "Considering / Seeing", correct: true }, { id: "b", text: "Due to", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Para harcadığım (re-stated as reason).", correctAnswer: "The reason (why) I spent money" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The match was delayed because of the player's injury.", options: [{ id: "a", text: "Oyuncunun sakatlanması nedeniyle maç ertelendi", correct: true }, { id: "b", text: "Oyuncu sakatlandı", correct: false }] },
            { id: 16, type: "SELECT", question: "___ + Noun Phrase:", options: [{ id: "a", text: "Due to", correct: true }, { id: "b", text: "Since", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The failure was _____ (attribute) to negligence.", options: [{ id: "a", text: "attributed", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Çabalarından dolayı ödül aldı.", correctAnswer: "He received an award on account of his efforts" },
            { id: 19, type: "SELECT", question: "Which is a synonym for 'since' as reason?", options: [{ id: "a", text: "as / because", correct: true }, { id: "b", text: "so that", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He was punished _____ breaking the rules.", options: [{ id: "a", text: "for", correct: true }, { id: "b", text: "with", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Reason/Result Review & Mixed)
            { id: 1, type: "SELECT", question: "___ it was a holiday, the shops were closed.", options: [{ id: "a", text: "Since / As / Because", correct: true }, { id: "b", text: "Due to", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The shop was closed _____ the holiday.", options: [{ id: "a", text: "because of", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Herkesin bildiği üzere, dünya yuvarlaktır (as reason-like).", correctAnswer: "As everyone knows, the earth is round" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Seeing that you are busy, I'll come back later.", options: [{ id: "a", text: "Meşgul olduğunuzu gördüğüme göre sonra geleceğim", correct: true }, { id: "b", text: "Sizi bekleyemem", correct: false }] },
            { id: 5, type: "SELECT", question: "Which result clause is most formal?", options: [{ id: "a", text: "Consequently / As a result", correct: true }, { id: "b", text: "So", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He worked hard; _____, he passed the exam.", options: [{ id: "a", text: "therefore / consequently", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "O kadar nazik bir adam ki herkes ona güvenir.", correctAnswer: "He is such a kind man that everyone trusts him" },
            { id: 8, type: "SELECT", question: "Clause of purpose with 'for fear that':", options: [{ id: "a", text: "He hid the money for fear that it would be stolen.", correct: true }, { id: "b", text: "He hid the money for steal.", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I didn't buy the shoes, _____ they were too small.", options: [{ id: "a", text: "for / since / as", correct: true }, { id: "b", text: "so that", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "In view of the circumstances, we must act now.", options: [{ id: "a", text: "Şartlar göz önüne alındığında şimdi harekete geçmeliyiz", correct: true }, { id: "b", text: "Şartlar değişecek", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "O kadar çok parası var ki ne yapacağını bilmiyor.", correctAnswer: "He has so much money that he doesn't know what to do" },
            { id: 12, type: "SELECT", question: "'For' as a conjunction (formal reason):", options: [{ id: "a", text: "I kept silent, for I didn't want to argue.", correct: true }, { id: "b", text: "I kept silent for argument.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The delay was _____ to a strike.", options: [{ id: "a", text: "due / owing", correct: true }, { id: "b", text: "on account", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Kendi iyiliğin için yapıyorsun.", correctAnswer: "You are doing it for your own sake" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is such a good student that he never misses a class.", options: [{ id: "a", text: "O kadar iyi bir öğrenci ki hiçbir dersi kaçırmaz", correct: true }, { id: "b", text: "Dersi kaçırdı", correct: false }] },
            { id: 16, type: "SELECT", question: "Which expresses purpose?", options: [{ id: "a", text: "with a view to + Ving", correct: true }, { id: "b", text: "with a view of + Ving", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She studied hard _____ (lest) she should fail.", options: [{ id: "a", text: "lest", correct: true }, { id: "b", text: "that", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Görüşmek amacıyla aradı.", correctAnswer: "He called with the intention of meeting" },
            { id: 19, type: "SELECT", question: "Reason with 'by virtue of':", options: [{ id: "a", text: "He has the job by virtue of his experience.", correct: true }, { id: "b", text: "He has the job by his experience.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I went to the store _____ get some milk.", options: [{ id: "a", text: "to / for", correct: true }, { id: "b", text: "to", correct: false }] }
        ]
    },
    203: {
        1: [ // QUIZ 1: EASY (Present Deduction: Must, Can't)
            { id: 1, type: "SELECT", question: "The phone is ringing. It ___ be my mother; she promised to call.", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He's been working for 12 hours. He _____ be very tired.", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu doğru olamaz.", correctAnswer: "This can't be true" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "You must be joking!", options: [{ id: "a", text: "Şaka yapıyor olmalısın!", correct: true }, { id: "b", text: "Şaka yapma", correct: false }] },
            { id: 5, type: "SELECT", question: "Which modal is used for a strong negative deduction?", options: [{ id: "a", text: "can't", correct: true }, { id: "b", text: "mustn't", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She has three cars. She _____ be rich.", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Burnumun dibinde olmalı.", correctAnswer: "It must be under my nose" },
            { id: 8, type: "SELECT", question: "If something is impossible, use:", options: [{ id: "a", text: "can't", correct: true }, { id: "b", text: "might not", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "You _____ be serious! That's impossible.", options: [{ id: "a", text: "can't", correct: true }, { id: "b", text: "must", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They must live near here; they are always in this cafe.", options: [{ id: "a", text: "Buralarda yaşıyor olmalılar; her zaman bu kafedeler", correct: true }, { id: "b", text: "Burada yaşamıyorlar", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Onu tanıyor olmalı.", correctAnswer: "He must know her" },
            { id: 12, type: "SELECT", question: "Which is used for a strong logical positive deduction?", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "should", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ be at home; his car is in the driveway.", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onun kardeşi olamaz, hiç benzemiyorlar.", correctAnswer: "She can't be his sister, they don't look alike at all" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "That must be the postman at the door.", options: [{ id: "a", text: "Kapıdaki postacı olmalı", correct: true }, { id: "b", text: "Postacı geldi", correct: false }] },
            { id: 16, type: "SELECT", question: "It ___ be cold outside; everyone is wearing coats.", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "You _____ be hungry; you haven't eaten all day.", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bu anahtar senin olamaz.", correctAnswer: "This key can't be yours" },
            { id: 19, type: "SELECT", question: "Positive deduction:", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "mustn't", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "It _____ be 10 o'clock already! Time flies.", options: [{ id: "a", text: "can't", correct: true }, { id: "b", text: "must", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Past Deduction: Must have, Can't have)
            { id: 1, type: "SELECT", question: "I can't find my keys. I ___ left them at home.", options: [{ id: "a", text: "must have", correct: true }, { id: "b", text: "can't have", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (be) very happy when he heard the news.", options: [{ id: "a", text: "must have been", correct: true }, { id: "b", text: "can't have been", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Onu yapmış olamaz.", correctAnswer: "He can't have done it" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "You must have seen the movie; it's so famous.", options: [{ id: "a", text: "Filmi görmüş olmalısın; çok ünlü", correct: true }, { id: "b", text: "Filmi izle", correct: false }] },
            { id: 5, type: "SELECT", question: "Past deduction formula:", options: [{ id: "a", text: "modal + have + V3", correct: true }, { id: "b", text: "modal + V2", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (forget) about the meeting.", options: [{ id: "a", text: "must have forgotten", correct: true }, { id: "b", text: "can't have forgotten", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Beni duymuş olmalı.", correctAnswer: "He must have heard me" },
            { id: 8, type: "SELECT", question: "Which implies 'I'm sure it DIDN'T happen'?", options: [{ id: "a", text: "can't have", correct: true }, { id: "b", text: "mightn't have", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The streets are wet. It _____ (rain) last night.", options: [{ id: "a", text: "must have rained", correct: true }, { id: "b", text: "can't have rained", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She can't have been at work; the office was closed.", options: [{ id: "a", text: "İşte olmuş olamaz; ofis kapalıydı", correct: true }, { id: "b", text: "İşten geldi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Uyuyakalmış olmalıyım.", correctAnswer: "I must have fallen asleep" },
            { id: 12, type: "SELECT", question: "___ + have + V3 (Negative deduction):", options: [{ id: "a", text: "can't / couldn't", correct: true }, { id: "b", text: "mustn't", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (arrive) yet; he only left 10 minutes ago.", options: [{ id: "a", text: "can't have arrived", correct: true }, { id: "b", text: "must have arrived", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Hata yapmış olmalısın.", correctAnswer: "You must have made a mistake" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They must have enjoyed the party.", options: [{ id: "a", text: "Partiden keyif almış olmalılar", correct: true }, { id: "b", text: "Partiye gittiler", correct: false }] },
            { id: 16, type: "SELECT", question: "I didn't hear the doorbell. I ___ been asleep.", options: [{ id: "a", text: "must have", correct: true }, { id: "b", text: "should have", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "You _____ (lose) your passport! Look again.", options: [{ id: "a", text: "can't have lost", correct: true }, { id: "b", text: "must have lost", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Başka bir şey söylemiş olmalı.", correctAnswer: "He must have said something else" },
            { id: 19, type: "SELECT", question: "Strong probability in the past:", options: [{ id: "a", text: "must have", correct: true }, { id: "b", text: "could have", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (see) her there, but I'm not sure.", options: [{ id: "a", text: "might have seen", correct: true }, { id: "b", text: "must have seen", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Possibility: May, Might, Could)
            { id: 1, type: "SELECT", question: "I'm not sure where he is. He ___ be at the library.", options: [{ id: "a", text: "might / could / may", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Take an umbrella. It _____ rain later.", options: [{ id: "a", text: "might", correct: true }, { id: "b", text: "must", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Daha sonra gelebilirler.", correctAnswer: "They may come later" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He might have forgotten the appointment.", options: [{ id: "a", text: "Randevuyu unutmuş olabilir", correct: true }, { id: "b", text: "Randevuyu unuttu", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is used for theoretical possibility (general)?", options: [{ id: "a", text: "could", correct: true }, { id: "b", text: "may", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "If you work hard, you _____ succeed.", options: [{ id: "a", text: "might / may / could", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Yalan söylüyor olabilir.", correctAnswer: "He could be lying" },
            { id: 8, type: "SELECT", question: "Negative possibility (50/50):", options: [{ id: "a", text: "may not / might not", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ not go to the exhibition if it's too expensive.", options: [{ id: "a", text: "may / might", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The restaurant could be full tonight.", options: [{ id: "a", text: "Restoran bu gece dolu olabilir", correct: true }, { id: "b", text: "Restoran doluydu", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Yardım edebilirlerdi (re-state possibility).", correctAnswer: "They could have helped" },
            { id: 12, type: "SELECT", question: "Might have + V3 indicates:", options: [{ id: "a", text: "Past possibility", correct: true }, { id: "b", text: "Past certainty", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He is late. He _____ (miss) the bus.", options: [{ id: "a", text: "might have missed", correct: true }, { id: "b", text: "can't have missed", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Belki haklıdır.", correctAnswer: "He might be right" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "This could lead to a serious problem.", options: [{ id: "a", text: "Bu ciddi bir soruna yol açabilir", correct: true }, { id: "b", text: "Ciddi bir sorun var", correct: false }] },
            { id: 16, type: "SELECT", question: "___ + NOT (Lack of possibility):", options: [{ id: "a", text: "might not", correct: true }, { id: "b", text: "can not (impossible)", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ visit you tomorrow if I have time.", options: [{ id: "a", text: "may / might", correct: true }, { id: "b", text: "must", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Daha kötü olabilirdi.", correctAnswer: "It could have been worse" },
            { id: 19, type: "SELECT", question: "Very remote possibility:", options: [{ id: "a", text: "might", correct: true }, { id: "b", text: "can", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The keys _____ be in the drawer.", options: [{ id: "a", text: "could / might / may", correct: true }, { id: "b", text: "must", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Should have, Needn't have)
            { id: 1, type: "SELECT", question: "I have a terrible headache. I ___ drunk so much coffee.", options: [{ id: "a", text: "shouldn't have", correct: true }, { id: "b", text: "mustn't have", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "You _____ (water) the plants. It's already raining.", options: [{ id: "a", text: "needn't have watered", correct: true }, { id: "b", text: "must have watered", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bana söylemen gerekirdi.", correctAnswer: "You should have told me" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "You ought to have known better.", options: [{ id: "a", text: "Daha iyisini bilmeliydin", correct: true }, { id: "b", text: "Daha iyi biliyorsun", correct: false }] },
            { id: 5, type: "SELECT", question: "Needn't have vs Didn't need to:", options: [{ id: "a", text: "Needn't have (done, but unnecessary)", correct: true }, { id: "b", text: "Didn't need to (not done because unnecessary)", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (bring) an umbrella, but I didn't know it would rain.", options: [{ id: "a", text: "should have brought", correct: true }, { id: "b", text: "might have brought", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bu kadar erken gelmene gerek yoktu (ama geldin).", correctAnswer: "You needn't have come so early" },
            { id: 8, type: "SELECT", question: "Which is used for an unfulfilled obligation in the past?", options: [{ id: "a", text: "should have", correct: true }, { id: "b", text: "must have", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "They _____ (not / leave) without a map.", options: [{ id: "a", text: "shouldn't have left", correct: true }, { id: "b", text: "couldn't have left", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I needn't have bought bread; there was plenty at home.", options: [{ id: "a", text: "Ekmek almama gerek yoktu (ama aldım)", correct: true }, { id: "b", text: "Ekmek almadım", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Onu davet etmeliydik.", correctAnswer: "We should have invited him" },
            { id: 12, type: "SELECT", question: "Formal substitute for 'should have':", options: [{ id: "a", text: "ought to have", correct: true }, { id: "b", text: "must have", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "You _____ (waste) all that money.", options: [{ id: "a", text: "shouldn't have wasted", correct: true }, { id: "b", text: "can't have wasted", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yardım etmiş olabilirlerdi (ama etmediler).", correctAnswer: "They could have helped" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He should have arrived by now.", options: [{ id: "a", text: "Şimdiye kadar varmış olmalıydı", correct: true }, { id: "b", text: "Varmak üzere", correct: false }] },
            { id: 16, type: "SELECT", question: "Which denotes a missed opportunity?", options: [{ id: "a", text: "could have", correct: true }, { id: "b", text: "must have", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (call) earlier if she wanted to come.", options: [{ id: "a", text: "should have called", correct: true }, { id: "b", text: "might have called", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Daha dikkatli olmalıydın.", correctAnswer: "You should have been more careful" },
            { id: 19, type: "SELECT", question: "'Needn't have' vs 'Must have':", options: [{ id: "a", text: "Both use have + V3", correct: true }, { id: "b", text: "One uses V2", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (listen) to your advice.", options: [{ id: "a", text: "should have listened", correct: true }, { id: "b", text: "must have listened", correct: false }] }
        ]
    },
    204: {
        1: [ // QUIZ 1: EASY (Noun Suffixes: -ation, -ment, -ness, -ity)
            { id: 1, type: "SELECT", question: "Noun form of 'Inform':", options: [{ id: "a", text: "Information", correct: true }, { id: "b", text: "Informing", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (move) of the dancers was beautiful.", options: [{ id: "a", text: "movement", correct: true }, { id: "b", text: "moving", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Mutluluk bir seçimdir.", correctAnswer: "Happiness is a choice" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The expansion of the company was successful.", options: [{ id: "a", text: "Şirketin genişlemesi başarılıydı", correct: true }, { id: "b", text: "Şirket başarılı oldu", correct: false }] },
            { id: 5, type: "SELECT", question: "Suffix to turn 'Kind' into a noun:", options: [{ id: "a", text: "-ness", correct: true }, { id: "b", text: "-ity", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "There is no _____ (similar) between the two twins.", options: [{ id: "a", text: "similarity", correct: true }, { id: "b", text: "similar", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Önemini anlamıyorum.", correctAnswer: "I don't understand the importance" },
            { id: 8, type: "SELECT", question: "Noun form of 'Develop':", options: [{ id: "a", text: "Development", correct: true }, { id: "b", text: "Developing", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (agree) was signed by the President.", options: [{ id: "a", text: "agreement", correct: true }, { id: "b", text: "agree", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We need more creativity in this project.", options: [{ id: "a", text: "Bu projede daha fazla yaratıcılığa ihtiyacımız var", correct: true }, { id: "b", text: "Yaratıcı bir proje", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Zayıflığını gösterme.", correctAnswer: "Don't show your weakness" },
            { id: 12, type: "SELECT", question: "Noun form of 'Argue':", options: [{ id: "a", text: "Argument", correct: true }, { id: "b", text: "Arguing", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Her _____ (blind) didn't stop her from playing music.", options: [{ id: "a", text: "blindness", correct: true }, { id: "b", text: "blinding", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Katılım zorunlu değil.", correctAnswer: "Participation is not mandatory" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The reality of the situation is grim.", options: [{ id: "a", text: "Durumun gerçeği vahim", correct: true }, { id: "b", text: "Gerçek bir çözüm bul", correct: false }] },
            { id: 16, type: "SELECT", question: "Suffix to turn 'Dark' into a noun:", options: [{ id: "a", text: "-ness", correct: true }, { id: "b", text: "-ity", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (equip) arrived late.", options: [{ id: "a", text: "equipment", correct: true }, { id: "b", text: "equipping", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Varlığını hissetmedim.", correctAnswer: "I didn't feel your presence" },
            { id: 19, type: "SELECT", question: "Noun form of 'Prepare':", options: [{ id: "a", text: "Preparation", correct: true }, { id: "b", text: "Preparing", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I value our _____ (friend).", options: [{ id: "a", text: "friendship", correct: true }, { id: "b", text: "friend", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Adjective Suffixes: -able, -ive, -ous, -ful, -less)
            { id: 1, type: "SELECT", question: "Adjective form of 'Reason':", options: [{ id: "a", text: "Reasonable", correct: true }, { id: "b", text: "Reasoning", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The situation was _____ (hope). Nothing could be done.", options: [{ id: "a", text: "hopeless", correct: true }, { id: "b", text: "hopeful", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Tehlikeli bir yolculuk.", correctAnswer: "A dangerous journey" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She is a very creative person.", options: [{ id: "a", text: "O çok yaratıcı bir insan", correct: true }, { id: "b", text: "Yaratıcı biri", correct: false }] },
            { id: 5, type: "SELECT", question: "Suffix to turn 'Wonder' into an adjective (full of):", options: [{ id: "a", text: "-ful", correct: true }, { id: "b", text: "-less", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The child was _____ (fear). He wasn't afraid of anything.", options: [{ id: "a", text: "fearless", correct: true }, { id: "b", text: "fearful", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Lezzetli bir yemek.", correctAnswer: "A delicious meal" },
            { id: 8, type: "SELECT", question: "Adjective form of 'Attract':", options: [{ id: "a", text: "Attractive", correct: true }, { id: "b", text: "Attraction", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "This offer is very _____ (accept).", options: [{ id: "a", text: "acceptable", correct: true }, { id: "b", text: "accepting", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Be careful when you cross the street.", options: [{ id: "a", text: "Caddeyi geçerken dikkatli ol", correct: true }, { id: "b", text: "Dikkatli geçtin", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Faydalı bir tavsiye.", correctAnswer: "A useful piece of advice" },
            { id: 12, type: "SELECT", question: "Adjective form of 'Mystery':", options: [{ id: "a", text: "Mysterious", correct: true }, { id: "b", text: "Mistery", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He is a very _____ (ambition) young man.", options: [{ id: "a", text: "ambitious", correct: true }, { id: "b", text: "ambition", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Gereksiz bir tartışma.", correctAnswer: "An unnecessary argument" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The ending of the book was predictable.", options: [{ id: "a", text: "Kitabın sonu tahmin edilebilirdi", correct: true }, { id: "b", text: "Kitabın sonu güzeldi", correct: false }] },
            { id: 16, type: "SELECT", question: "Suffix to turn 'Success' into an adjective:", options: [{ id: "a", text: "-ful", correct: true }, { id: "b", text: "-ive", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "This tool is _____ (use). I can't do anything with it.", options: [{ id: "a", text: "useless", correct: true }, { id: "b", text: "useful", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Aktif bir yaşam tarzı.", correctAnswer: "An active lifestyle" },
            { id: 19, type: "SELECT", question: "Adjective form of 'Value':", options: [{ id: "a", text: "Valuable", correct: true }, { id: "b", text: "Valuing", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The water was _____ (poison).", options: [{ id: "a", text: "poisonous", correct: true }, { id: "b", text: "poisoned", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Verb and Adverb Suffixes: -ize, -en, -ly)
            { id: 1, type: "SELECT", question: "Verb form of 'Modern':", options: [{ id: "a", text: "Modernize", correct: true }, { id: "b", text: "Modernness", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "You need to _____ (sharp) your pencil.", options: [{ id: "a", text: "sharpen", correct: true }, { id: "b", text: "sharp", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu süreci basitleştirmeliyiz.", correctAnswer: "We must simplify this process" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He apologized sincerely for his mistake.", options: [{ id: "a", text: "Hatası için içtenlikle özür diledi", correct: true }, { id: "b", text: "Özür diledi", correct: false }] },
            { id: 5, type: "SELECT", question: "Suffix to turn 'Broad' into a verb:", options: [{ id: "a", text: "-en", correct: true }, { id: "b", text: "-ify", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We must _____ (length) the deadline.", options: [{ id: "a", text: "lengthen", correct: true }, { id: "b", text: "length", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Hızlıca karar verdik.", correctAnswer: "We decided quickly" },
            { id: 8, type: "SELECT", question: "Verb form of 'Clean' (make clear):", options: [{ id: "a", text: "Clarify", correct: true }, { id: "b", text: "Cleansing", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "They want to industrialize the region.", options: [{ id: "a", text: "Bölgeyi endüstriyelleştirmek istiyorlar", correct: true }, { id: "b", text: "Bölgede sanayi var", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Düzenli olarak spor yapıyor.", correctAnswer: "He exercises regularly" },
            { id: 12, type: "SELECT", question: "Verb form of 'Apology':", options: [{ id: "a", text: "Apologize", correct: true }, { id: "b", text: "Apologizing", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Her eyes _____ (bright) when she heard the news.", options: [{ id: "a", text: "brightened", correct: true }, { id: "b", text: "brightening", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Aniden durdu.", correctAnswer: "He stopped suddenly" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The government decided to privatize the industry.", options: [{ id: "a", text: "Hükümet sektörü özelleştirmeye karar verdi", correct: true }, { id: "b", text: "Sektör özel", correct: false }] },
            { id: 16, type: "SELECT", question: "Prefix to turn 'Strong' into a verb:", options: [{ id: "a", text: "Strength (noun) -> Strengthen (verb)", correct: true }, { id: "b", text: "Strongize", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The sugar will _____ (sweet) the tea.", options: [{ id: "a", text: "sweeten", correct: true }, { id: "b", text: "sweetening", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Neredeyse bitti.", correctAnswer: "It's almost finished" },
            { id: 19, type: "SELECT", question: "Suffix to turn 'Final' into a verb:", options: [{ id: "a", text: "-ize (finalize)", correct: true }, { id: "b", text: "-ify", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He spoke _____ (quiet) so as not to wake the baby.", options: [{ id: "a", text: "quietly", correct: true }, { id: "b", text: "quiet", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Negative Prefixes: un-, in-, im-, ir-, il-)
            { id: 1, type: "SELECT", question: "Opposite of 'Happy':", options: [{ id: "a", text: "Unhappy", correct: true }, { id: "b", text: "Imhappy", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "His behaviour was very _____ (mature).", options: [{ id: "a", text: "immature", correct: true }, { id: "b", text: "unmature", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "İmkansız bir görev.", correctAnswer: "An impossible task" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "His handwriting is completely illegible.", options: [{ id: "a", text: "El yazısı tamamen okunaksız", correct: true }, { id: "b", text: "El yazısı kötü", correct: false }] },
            { id: 5, type: "SELECT", question: "Prefix for 'Responsible':", options: [{ id: "a", text: "ir-", correct: true }, { id: "b", text: "un-", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The data you provided is _____ (accurate).", options: [{ id: "a", text: "inaccurate", correct: true }, { id: "b", text: "unaccurate", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Sabırsız olma.", correctAnswer: "Don't be impatient" },
            { id: 8, type: "SELECT", question: "Opposite of 'Legal':", options: [{ id: "a", text: "Illegal", correct: true }, { id: "b", text: "Unlegal", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "It is _____ (possible) to finish this today.", options: [{ id: "a", text: "impossible", correct: true }, { id: "b", text: "unpossible", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "His arguments were irrelevant to the topic.", options: [{ id: "a", text: "Argümanları konuyla alakasızdı", correct: true }, { id: "b", text: "Argümanları yanlıştı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Mantıksız bir karar.", correctAnswer: "An illogical decision" },
            { id: 12, type: "SELECT", question: "Prefix for 'Comfortable':", options: [{ id: "a", text: "un-", correct: true }, { id: "b", text: "in-", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "She is _____ (capable) of doing such a thing.", options: [{ id: "a", text: "incapable", correct: true }, { id: "b", text: "uncapable", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Maalesef gelemiyorum.", correctAnswer: "Unfortunately I can't come" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The player was disqualified for irregular conduct.", options: [{ id: "a", text: "Oyuncu kural dışı davranışları nedeniyle diskalifiye edildi", correct: true }, { id: "b", text: "Oyuncu cezalı", correct: false }] },
            { id: 16, type: "SELECT", question: "Prefix for 'Patient':", options: [{ id: "a", text: "im-", correct: true }, { id: "b", text: "in-", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "This is a very _____ (usual) situation.", options: [{ id: "a", text: "unusual", correct: true }, { id: "b", text: "inusual", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Görünmez adam.", correctAnswer: "The invisible man" },
            { id: 19, type: "SELECT", question: "Prefix for 'Formal':", options: [{ id: "a", text: "in-", correct: true }, { id: "b", text: "un-", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He is always _____ (polite) to his teachers.", options: [{ id: "a", text: "impolite", correct: true }, { id: "b", text: "depolite", correct: false }] }
        ]
    },
    205: {
        1: [ // QUIZ 1: EASY (Relative Clauses & Purpose Review)
            { id: 1, type: "SELECT", question: "The man ___ called was my uncle.", options: [{ id: "a", text: "who", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I went to the store _____ get some eggs.", options: [{ id: "a", text: "to / in order to", correct: true }, { id: "b", text: "for", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Sattığın ev çok güzeldi.", correctAnswer: "The house (which/that) you sold was very beautiful" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He studied all night so that he wouldn't fail.", options: [{ id: "a", text: "Kalmamak için bütün gece çalıştı", correct: true }, { id: "b", text: "Çalıştı ve geçti", correct: false }] },
            { id: 5, type: "SELECT", question: "Relative pronoun for a place:", options: [{ id: "a", text: "where", correct: true }, { id: "b", text: "when", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The book _____ I am reading is very long.", options: [{ id: "a", text: "which / that / (blank)", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Geç kalmamak için acele etti.", correctAnswer: "He hurried so as not to be late" },
            { id: 8, type: "SELECT", question: "Which is used for people in defining clauses?", options: [{ id: "a", text: "who / that", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Tell me the time _____ the train arrives.", options: [{ id: "a", text: "when", correct: true }, { id: "b", text: "where", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The woman whose bag was stolen is crying.", options: [{ id: "a", text: "Çantası çalınan kadın ağlıyor", correct: true }, { id: "b", text: "Kadın çantasını kaybetti", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Anlamak için tekrar okudu.", correctAnswer: "He read it again in order to understand" },
            { id: 12, type: "SELECT", question: "Omission: In which case can we drop 'who'?", options: [{ id: "a", text: "The man who I saw (Object)", correct: true }, { id: "b", text: "The man who saw me (Subject)", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The reason _____ I'm calling is to invite you.", options: [{ id: "a", text: "why", correct: true }, { id: "b", text: "where", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bu, tanıştığım en zeki adam.", correctAnswer: "This is the most intelligent man that I've met" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll give you a key so that you can get in.", options: [{ id: "a", text: "İçeri girebilmen için sana bir anahtar vereceğim", correct: true }, { id: "b", text: "Anahtarı al", correct: false }] },
            { id: 16, type: "SELECT", question: "Non-defining clause: 'My car ___ is red is new.'", options: [{ id: "a", text: ", which is red, (with commas)", correct: true }, { id: "b", text: "which is red (without commas)", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He came here _____ (see) us.", options: [{ id: "a", text: "to see / for the purpose of seeing", correct: true }, { id: "b", text: "for see", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Doğruyu söylemek gerekirse (purpose-like).", correctAnswer: "To tell the truth" },
            { id: 19, type: "SELECT", question: "Can 'that' be used after a comma?", options: [{ id: "a", text: "No", correct: true }, { id: "b", text: "Yes", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The building _____ they are working is new.", options: [{ id: "a", text: "where / in which", correct: true }, { id: "b", text: "which", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Result & Reason Review)
            { id: 1, type: "SELECT", question: "It was ___ a loud noise that I woke up.", options: [{ id: "a", text: "such", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He was _____ tired that he couldn't speak.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Yağmur yüzünden geç kaldım.", correctAnswer: "I was late because of the rain" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The flight was cancelled due to the strike.", options: [{ id: "a", text: "Grev nedeniyle uçuş iptal edildi", correct: true }, { id: "b", text: "Uçuş ertelendi", correct: false }] },
            { id: 5, type: "SELECT", question: "Structure: '___ + adjective + that'", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I stayed home _____ I didn't feel well.", options: [{ id: "a", text: "because / since / as", correct: true }, { id: "b", text: "because of", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Öyle güzel bir gündü ki!", correctAnswer: "It was such a beautiful day" },
            { id: 8, type: "SELECT", question: "Which should be followed by a noun phrase?", options: [{ id: "a", text: "due to / because of / owing to", correct: true }, { id: "b", text: "because / since", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "There were _____ many people that we couldn't sit.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "such", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "On account of the fog, the traffic was heavy.", options: [{ id: "a", text: "Sis sebebiyle trafik yoğundu", correct: true }, { id: "b", text: "Sis vardı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Öyle hızlı yazdı ki okuyamadım.", correctAnswer: "He wrote so fast that I couldn't read it" },
            { id: 12, type: "SELECT", question: "Which is most formal for result?", options: [{ id: "a", text: "Consequently / Therefore", correct: true }, { id: "b", text: "So", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The game was postponed _____ the player's injury.", options: [{ id: "a", text: "because of / due to", correct: true }, { id: "b", text: "because", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Meşgul olduğunu gördüğüme göre (reason-like).", correctAnswer: "Seeing that you are busy" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He has such a lot of books that he needs more shelves.", options: [{ id: "a", text: "O kadar çok kitabı var ki yeni raflara ihtiyacı var", correct: true }, { id: "b", text: "Kitapları rafa dizdi", correct: false }] },
            { id: 16, type: "SELECT", question: "'As' and 'Since' can mean 'Because'.", options: [{ id: "a", text: "True", correct: true }, { id: "b", text: "False", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It was _____ a difficult exam that no one passed.", options: [{ id: "a", text: "such", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Korktuğu için bir şey söylemedi.", correctAnswer: "He didn't say anything because he was afraid" },
            { id: 19, type: "SELECT", question: "Structure: 'so + ___ + that'", options: [{ id: "a", text: "much / many / few / little", correct: true }, { id: "b", text: "a lot of", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I couldn't hear him _____ the noise.", options: [{ id: "a", text: "because of", correct: true }, { id: "b", text: "because", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Deduction & Speculation Review)
            { id: 1, type: "SELECT", question: "He has a lot of money. He ___ be rich.", options: [{ id: "a", text: "must", correct: true }, { id: "b", text: "can't", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (be) at the party, but I didn't see her.", options: [{ id: "a", text: "might have been", correct: true }, { id: "b", text: "can't have been", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Onu çoktan yapmış olmalı.", correctAnswer: "He must have done it already" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "You can't have seen him; he's in France.", options: [{ id: "a", text: "Onu görmüş olamazsın; o Fransa'da", correct: true }, { id: "b", text: "Onu Fransa'da gör", correct: false }] },
            { id: 5, type: "SELECT", question: "Which modal is used for a missed opportunity?", options: [{ id: "a", text: "could have (+ V3)", correct: true }, { id: "b", text: "must have", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (listen) to my doctor's advice, but I didn't.", options: [{ id: "a", text: "should have listened", correct: true }, { id: "b", text: "might have listened", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Anahtarları unutmuş olmalıydı (speculation).", correctAnswer: "He must have forgotten the keys" },
            { id: 8, type: "SELECT", question: "Strong negative deduction in the past:", options: [{ id: "a", text: "can't have / couldn't have", correct: true }, { id: "b", text: "mustn't have", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The floor is wet. Someone _____ (spill) water.", options: [{ id: "a", text: "must have spilled", correct: true }, { id: "b", text: "should have spilled", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "You needn't have brought any food; we have plenty.", options: [{ id: "a", text: "Yemek getirmene gerek yoktu (ama getirdin)", correct: true }, { id: "b", text: "Yemek getirmelisin", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Daha dikkatli olmalıydı (criticism).", correctAnswer: "He should have been more careful" },
            { id: 12, type: "SELECT", question: "Meaning of 'ought to have':", options: [{ id: "a", text: "Same as 'should have'", correct: true }, { id: "b", text: "Same as 'must have'", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "They _____ (not / hear) the phone; they were outside.", options: [{ id: "a", text: "might not have heard / can't have heard", correct: true }, { id: "b", text: "shouldn't have heard", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Daha kötü olabilirdi.", correctAnswer: "It could have been worse" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She must be having a meeting right now.", options: [{ id: "a", text: "Şu an toplantı yapıyor olmalı", correct: true }, { id: "b", text: "Toplantısı var", correct: false }] },
            { id: 16, type: "SELECT", question: "Which modal shows present possibility?", options: [{ id: "a", text: "may / might / could", correct: true }, { id: "b", text: "should", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I don't know where my phone is. I _____ (leave) it at the office.", options: [{ id: "a", text: "might have left", correct: true }, { id: "b", text: "can't have left", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bize söylemen gerekirdi.", correctAnswer: "You should have told us" },
            { id: 19, type: "SELECT", question: "Positive deduction in present:", options: [{ id: "a", text: "must be", correct: true }, { id: "b", text: "can be", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (be) serious! It's a joke.", options: [{ id: "a", text: "can't be", correct: true }, { id: "b", text: "must be", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Word Formation & Mixed Review)
            { id: 1, type: "SELECT", question: "Noun form of 'Succeed':", options: [{ id: "a", text: "Success", correct: true }, { id: "b", text: "Successfully", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "His failure was _____ (predict).", options: [{ id: "a", text: "predictable", correct: true }, { id: "b", text: "prediction", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Maalesef treni kaçırdık.", correctAnswer: "Unfortunately we missed the train" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We need to simplify the instructions.", options: [{ id: "a", text: "Talimatları sadeleştirmemiz gerekiyor", correct: true }, { id: "b", text: "Talimatlar sade", correct: false }] },
            { id: 5, type: "SELECT", question: "Opposite of 'Regular':", options: [{ id: "a", text: "Irregular", correct: true }, { id: "b", text: "Unregular", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She spoke very _____ (sincere) at the meeting.", options: [{ id: "a", text: "sincerely", correct: true }, { id: "b", text: "sincere", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Hayal gücünü kullan.", correctAnswer: "Use your imagination" },
            { id: 8, type: "SELECT", question: "Verb form of 'Long':", options: [{ id: "a", text: "Lengthen", correct: true }, { id: "b", text: "Longitude", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The player was _____ (disqualify) for cheating.", options: [{ id: "a", text: "disqualified", correct: true }, { id: "b", text: "unqualified", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The expansion of the city is rapid.", options: [{ id: "a", text: "Şehrin genişlemesi hızlıdır", correct: true }, { id: "b", text: "Şehir hızlıdır", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Önemli bir karar.", correctAnswer: "An important decision" },
            { id: 12, type: "SELECT", question: "Suffix for Noun from 'Agree':", options: [{ id: "a", text: "-ment", correct: true }, { id: "b", text: "-ation", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "This offer is _____ (resist).", options: [{ id: "a", text: "irresistible", correct: true }, { id: "b", text: "unresistible", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Verimliliği artırmalıyız.", correctAnswer: "We must increase efficiency" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is an ambitious young lawyer.", options: [{ id: "a", text: "O hırslı genç bir avukat", correct: true }, { id: "b", text: "Avukat hırslıydı", correct: false }] },
            { id: 16, type: "SELECT", question: "Suffix to turn 'Beauty' into a verb:", options: [{ id: "a", text: "Beautify", correct: true }, { id: "b", text: "Beautifulize", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He gave me some _____ (value) advice.", options: [{ id: "a", text: "valuable", correct: true }, { id: "b", text: "value", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Sabırsızlıkla bekliyorum.", correctAnswer: "I am waiting impatiently" },
            { id: 19, type: "SELECT", question: "Adjective form of 'Mystery':", options: [{ id: "a", text: "Mysterious", correct: true }, { id: "b", text: "Misterial", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "We must _____ (strength) our defense.", options: [{ id: "a", text: "strengthen", correct: true }, { id: "b", text: "strong", correct: false }] }
        ]
    },
};
