import { Question } from '../../questions';

export const u206_210: Record<number, Record<number, Question[]>> = {
    206: {
        1: [ // QUIZ 1: EASY (Subjunctive Mood)
            { id: 1, type: "SELECT", question: "It is essential that he ___ here on time.", options: [{ id: "a", text: "be", correct: true }, { id: "b", text: "is", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The doctor recommended that she _____ (take) a holiday.", options: [{ id: "a", text: "take", correct: true }, { id: "b", text: "takes", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gitmeni öneririm (Subjunctive).", correctAnswer: "I suggest that you go" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It is vital that everyone be informed.", options: [{ id: "a", text: "Herkesin bilgilendirilmesi hayati önem taşıyor", correct: true }, { id: "b", text: "Herkes bilgilendirildi", correct: false }] },
            { id: 5, type: "SELECT", question: "Which verb is often followed by the subjunctive?", options: [{ id: "a", text: "Insist", correct: true }, { id: "b", text: "Hope", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "It is important that she _____ (not / forget) the keys.", options: [{ id: "a", text: "not forget", correct: true }, { id: "b", text: "doesn't forget", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Onun kalmasında ısrar ediyoruz.", correctAnswer: "We insist that he stay" },
            { id: 8, type: "SELECT", question: "Subjunctive form of 'to be' for all subjects:", options: [{ id: "a", text: "be", correct: true }, { id: "b", text: "were (in if clauses)", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I propose that the meeting _____ (postpone).", options: [{ id: "a", text: "be postponed", correct: true }, { id: "b", text: "is postponed", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "God save the Queen!", options: [{ id: "a", text: "Tanrı Kraliçeyi korusun!", correct: true }, { id: "b", text: "Kraliçeyi kurtar", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Hazır olman şart.", correctAnswer: "It is mandatory that you be ready" },
            { id: 12, type: "SELECT", question: "Which is correct in formal British English?", options: [{ id: "a", text: "I suggest that he should go.", correct: true }, { id: "b", text: "I suggest him to go.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Heaven _____ (help) us!", options: [{ id: "a", text: "help", correct: true }, { id: "b", text: "helps", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onunla konuşmasını talep etti.", correctAnswer: "He demanded that she speak with him" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Long live the King!", options: [{ id: "a", text: "Kral çok yaşasın!", correct: true }, { id: "b", text: "Kral yaşıyor", correct: false }] },
            { id: 16, type: "SELECT", question: "Is the subjunctive common in modern informal English?", options: [{ id: "a", text: "No, indicative is more common.", correct: true }, { id: "b", text: "Yes, it is always used.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It is desirable that the contract _____ (sign) today.", options: [{ id: "a", text: "be signed", correct: true }, { id: "b", text: "is signed", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Keşke buraya gelmese (modal-like subjunctive).", correctAnswer: "I'd rather he didn't come here" },
            { id: 19, type: "SELECT", question: "Subjunctive after 'It is time':", options: [{ id: "a", text: "It is time we went home.", correct: true }, { id: "b", text: "It is time we go home.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I suggest that he _____ (read) the report.", options: [{ id: "a", text: "read", correct: true }, { id: "b", text: "reads", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Inversion with Negative Adverbials)
            { id: 1, type: "SELECT", question: "Never ___ I seen such a beautiful sunset.", options: [{ id: "a", text: "have", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Rarely _____ we go out these days.", options: [{ id: "a", text: "do", correct: true }, { id: "b", text: "are", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bunu asla yapmamalıydın.", correctAnswer: "Never should you have done that" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Seldom does he complain about his work.", options: [{ id: "a", text: "İşi hakkında nadiren şikayet eder", correct: true }, { id: "b", text: "Hiç şikayet etmez", correct: false }] },
            { id: 5, type: "SELECT", question: "Inversion structure:", options: [{ id: "a", text: "Negative Word + Auxiliary + Subject", correct: true }, { id: "b", text: "Negative Word + Subject + Auxiliary", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Little _____ he know about the surprise.", options: [{ id: "a", text: "did", correct: true }, { id: "b", text: "was", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Neredeyse hiç zamanım yok.", correctAnswer: "Hardly do I have any time" },
            { id: 8, type: "SELECT", question: "Which adverbial triggers inversion?", options: [{ id: "a", text: "Under no circumstances", correct: true }, { id: "b", text: "Sometimes", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Hardly _____ I entered the room when the phone rang.", options: [{ id: "a", text: "had", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "No sooner had he left than it started to rain.", options: [{ id: "a", text: "O çıkar çıkmaz yağmur yağmaya başladı", correct: true }, { id: "b", text: "Yağmur yağınca çıktı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Hiçbir koşulda kapıyı açma.", correctAnswer: "Under no circumstances should you open the door" },
            { id: 12, type: "SELECT", question: "Correct pair for 'Hardly':", options: [{ id: "a", text: "Hardly ... when", correct: true }, { id: "b", text: "Hardly ... than", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Scarcely _____ the play started when there was an interruption.", options: [{ id: "a", text: "had", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Sadece o zaman gerçeği anladım.", correctAnswer: "Only then did I understand the truth" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Nowhere could we find a cheaper hotel.", options: [{ id: "a", text: "Hiçbir yerde daha ucuz bir otel bulamadık", correct: true }, { id: "b", text: "Ucuz otel bulduk", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "Not only is he smart, but also kind.", correct: true }, { id: "b", text: "Not only he is smart...", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "In no way _____ I responsible for this.", options: [{ id: "a", text: "am", correct: true }, { id: "b", text: "I am", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Daha önce böyle bir şey görmemiştim.", correctAnswer: "Never before had I seen such a thing" },
            { id: 19, type: "SELECT", question: "Only when triggering inversion:", options: [{ id: "a", text: "Only when she called did I find out.", correct: true }, { id: "b", text: "Only when did she call...", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "In vain _____ they try to convince him.", options: [{ id: "a", text: "did", correct: true }, { id: "b", text: "tried", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Inversion with Only / Not only)
            { id: 1, type: "SELECT", question: "Only after the match ___ we realize we had lost.", options: [{ id: "a", text: "did", correct: true }, { id: "b", text: "have", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Not only _____ she sing, but she also plays the piano.", options: [{ id: "a", text: "does", correct: true }, { id: "b", text: "is", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Ancak o zaman ağladığını fark ettim.", correctAnswer: "Only then did I notice she was crying" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Not only did he arrive late, but he also forgot his notes.", options: [{ id: "a", text: "Sadece geç kalmakla kalmadı, notlarını da unuttu", correct: true }, { id: "b", text: "Notlarını unuttu", correct: false }] },
            { id: 5, type: "SELECT", question: "Inversion with 'Not until':", options: [{ id: "a", text: "Not until I saw him did I believe it.", correct: true }, { id: "b", text: "Not until did I see him...", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Only by working hard _____ you succeed.", options: [{ id: "a", text: "will", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bunu sadece o biliyor (No inversion here).", correctAnswer: "Only he knows this" },
            { id: 8, type: "SELECT", question: "When does 'Only' NOT trigger inversion?", options: [{ id: "a", text: "When it modifies the subject at the beginning.", correct: true }, { id: "b", text: "Always", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Not until recently _____ I discover the truth.", options: [{ id: "a", text: "did", correct: true }, { id: "b", text: "I", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Only if you pay can you enter.", options: [{ id: "a", text: "Ancak ödeme yaparsan girebilirsin", correct: true }, { id: "b", text: "Girmek için öde", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "O sadece akıllı değil (re-stated).", correctAnswer: "Not only is he smart" },
            { id: 12, type: "SELECT", question: "Where is the inversion in a 'Not until' sentence?", options: [{ id: "a", text: "In the main clause", correct: true }, { id: "b", text: "In the 'until' clause", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Only once _____ I had a chance to meet him.", options: [{ id: "a", text: "did", correct: true }, { id: "b", text: "I", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Sadece bittikten sonra dinlenebiliriz.", correctAnswer: "Only after it's finished can we rest" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Not only were they tired, but they were also hungry.", options: [{ id: "a", text: "Sadece yorgun değillerdi, aynı zamanda açtılar", correct: true }, { id: "b", text: "Aç ve yorgundular", correct: false }] },
            { id: 16, type: "SELECT", question: "Correct: 'Only in this way ___ we win.'", options: [{ id: "a", text: "can", correct: true }, { id: "b", text: "we", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Only later _____ I realize the danger.", options: [{ id: "a", text: "did", correct: true }, { id: "b", text: "had", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Sadece bu kitap ilginç.", correctAnswer: "Only this book is interesting" },
            { id: 19, type: "SELECT", question: "Which triggers inversion?", options: [{ id: "a", text: "Only in the morning", correct: true }, { id: "b", text: "One morning", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Not only _____ he late, but his car also broke down.", options: [{ id: "a", text: "was", correct: true }, { id: "b", text: "is", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Inversion in Conditionals)
            { id: 1, type: "SELECT", question: "___ you need any help, please let me know.", options: [{ id: "a", text: "Should", correct: true }, { id: "b", text: "If", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I known about the party, I would have come.", options: [{ id: "a", text: "Had", correct: true }, { id: "b", text: "Have", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Senin yerinde olsam (Inversion).", correctAnswer: "Were I in your shoes / Were I you" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Had we arrived earlier, we wouldn't have missed it.", options: [{ id: "a", text: "Daha erken varsaydık, onu kaçırmazdık", correct: true }, { id: "b", text: "Erken vardık", correct: false }] },
            { id: 5, type: "SELECT", question: "Inversion for Type 1 (Possible):", options: [{ id: "a", text: "Should + subject + V1", correct: true }, { id: "b", text: "Could + subject + V1", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ he to win the lottery, he would buy a yacht.", options: [{ id: "a", text: "Were", correct: true }, { id: "b", text: "Was", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Yağmur yağarsa, evde kalırız (Inversion).", correctAnswer: "Should it rain, we will stay at home" },
            { id: 8, type: "SELECT", question: "Inversion for Type 3 (Past):", options: [{ id: "a", text: "Had + subject + V3", correct: true }, { id: "b", text: "Has + subject + V3", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ you change your mind, give me a call.", options: [{ id: "a", text: "Should", correct: true }, { id: "b", text: "If you should", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Were he my son, I'd be very proud.", options: [{ id: "a", text: "Oğlum olsaydı çok gurur duyardım", correct: true }, { id: "b", text: "Oğlumla gurur duyuyorum", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bilseydim söylerdim (Inversion).", correctAnswer: "Had I known, I would have told" },
            { id: 12, type: "SELECT", question: "Negative inversion in conditionals:", options: [{ id: "a", text: "Should he not call...", correct: true }, { id: "b", text: "Shouldn't he call...", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I to tell him the truth, he would be angry.", options: [{ id: "a", text: "Were", correct: true }, { id: "b", text: "Had", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yardım etselerdi (Inversion).", correctAnswer: "Had they helped" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Should anything happen, call the police.", options: [{ id: "a", text: "Bir şey olursa polisi ara", correct: true }, { id: "b", text: "Polisi aradık", correct: false }] },
            { id: 16, type: "SELECT", question: "Is 'Were I you' more formal than 'If I were you'?", options: [{ id: "a", text: "Yes", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ he been here, he could have helped us.", options: [{ id: "a", text: "Had", correct: true }, { id: "b", text: "Has", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Teklif etseydi kabul ederdim (Inversion).", correctAnswer: "Had he offered, I would have accepted" },
            { id: 19, type: "SELECT", question: "Inversion with 'If it were not for':", options: [{ id: "a", text: "Were it not for his help...", correct: true }, { id: "b", text: "Was it not for...", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ it to snow, the match would be cancelled.", options: [{ id: "a", text: "Were", correct: true }, { id: "b", text: "Should", correct: false }] }
        ]
    },
    207: {
        1: [ // QUIZ 1: EASY (Quantifiers: All, Both, Whole)
            { id: 1, type: "SELECT", question: "___ of my brothers are teachers.", options: [{ id: "a", text: "Both", correct: true }, { id: "b", text: "All", correct: false }, { id: "c", text: "Every", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I spent the _____ week at home.", options: [{ id: "a", text: "whole", correct: true }, { id: "b", text: "all", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bütün gün uyudu.", correctAnswer: "He slept all day / the whole day" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Both candidates were very impressive.", options: [{ id: "a", text: "Her iki aday da çok etkileyiciydi", correct: true }, { id: "b", text: "Bütün adaylar etkileyiciydi", correct: false }] },
            { id: 5, type: "SELECT", question: "Use 'whole' mainly with:", options: [{ id: "a", text: "Singular countable nouns", correct: true }, { id: "b", text: "Uncountable nouns", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ the students passed the test.", options: [{ id: "a", text: "All", correct: true }, { id: "b", text: "Both", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Elmaların hepsi çürük.", correctAnswer: "All the apples are rotten" },
            { id: 8, type: "SELECT", question: "Can we use 'the' before 'whole'?", options: [{ id: "a", text: "Yes (the whole time)", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I've eaten _____ of the pizza.", options: [{ id: "a", text: "half / all", correct: true }, { id: "b", text: "both", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She has been working all her life.", options: [{ id: "a", text: "Tüm hayatı boyunca çalışıyor", correct: true }, { id: "b", text: "Hayatı değişti", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "İkimiz de mutluyuz.", correctAnswer: "We are both happy / Both of us are happy" },
            { id: 12, type: "SELECT", question: "'All' vs 'Whole' with plural nouns:", options: [{ id: "a", text: "Use 'all'", correct: true }, { id: "b", text: "Use 'whole'", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "They have _____ (be) invited.", options: [{ id: "a", text: "all been", correct: true }, { id: "b", text: "whole been", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bütün dünya izliyor.", correctAnswer: "The whole world is watching" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I read all the books you lent me.", options: [{ id: "a", text: "Bana ödünç verdiğin tüm kitapları okudum", correct: true }, { id: "b", text: "Kitapları okuyacağım", correct: false }] },
            { id: 16, type: "SELECT", question: "___ of us were late.", options: [{ id: "a", text: "All / Both", correct: true }, { id: "b", text: "Every", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ town was destroyed.", options: [{ id: "a", text: "whole", correct: true }, { id: "b", text: "all", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "İki elini de kaldırdı.", correctAnswer: "He raised both hands" },
            { id: 19, type: "SELECT", question: "Position of 'both':", options: [{ id: "a", text: "They both laughed.", correct: true }, { id: "b", text: "They laughed both.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ my parents are doctors.", options: [{ id: "a", text: "Both", correct: true }, { id: "b", text: "All", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Each, Every, Either, Neither)
            { id: 1, type: "SELECT", question: "___ child was given a toy.", options: [{ id: "a", text: "Each / Every", correct: true }, { id: "b", text: "All", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Neither of the answers _____ (be) correct.", options: [{ id: "a", text: "is / was", correct: true }, { id: "b", text: "are (informal)", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "İkisini de istemiyorum.", correctAnswer: "I want neither of them / I don't want either of them" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Either of you can do the job.", options: [{ id: "a", text: "İkinizden biri işi yapabilir", correct: true }, { id: "b", text: "İkiniz de yapmalısınız", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is used for more than two people, thinking of them collectively?", options: [{ id: "a", text: "Every", correct: true }, { id: "b", text: "Each", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ student has a different opinion.", options: [{ id: "a", text: "Each", correct: true }, { id: "b", text: "All", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Her gün spor yaparım.", correctAnswer: "I exercise every day" },
            { id: 8, type: "SELECT", question: "Neither ... ___", options: [{ id: "a", text: "nor", correct: true }, { id: "b", text: "or", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I don't like _____ of these shirts.", options: [{ id: "a", text: "either", correct: true }, { id: "b", text: "neither", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She gave each child a piece of cake.", options: [{ id: "a", text: "Her çocuğa bir dilim kek verdi", correct: true }, { id: "b", text: "Çocuklara kek verdi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Ne babası ne de annesi oradaydı.", correctAnswer: "Neither his father nor his mother was there" },
            { id: 12, type: "SELECT", question: "Either ... ___", options: [{ id: "a", text: "or", correct: true }, { id: "b", text: "nor", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "You can take _____ road; both lead to the city.", options: [{ id: "a", text: "either", correct: true }, { id: "b", text: "neither", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Her iki taraf da kabul etti.", correctAnswer: "Both sides agreed / Each side agreed" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I've told you every single detail.", options: [{ id: "a", text: "Sana her bir detayı anlattım", correct: true }, { id: "b", text: "Detayları anlattım", correct: false }] },
            { id: 16, type: "SELECT", question: "___ of the buildings was damaged.", options: [{ id: "a", text: "Each", correct: true }, { id: "b", text: "Every", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Neither side _____ (be) happy with the result.", options: [{ id: "a", text: "was", correct: true }, { id: "b", text: "were", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "İkisinden birini seç.", correctAnswer: "Choose either of them" },
            { id: 19, type: "SELECT", question: "Does 'Every' take a singular verb?", options: [{ id: "a", text: "Yes", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Each of the players _____ (have) to sign.", options: [{ id: "a", text: "has", correct: true }, { id: "b", text: "have", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (None, No, Any, Some)
            { id: 1, type: "SELECT", question: "___ of the money was spent.", options: [{ id: "a", text: "None", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "There is _____ milk left.", options: [{ id: "a", text: "no", correct: true }, { id: "b", text: "none", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Hiçbir arkadaşım aramadı.", correctAnswer: "None of my friends called" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "None of the information is correct.", options: [{ id: "a", text: "Bilgilerin hiçbirisi doğru değil", correct: true }, { id: "b", text: "Bilgi yanlış", correct: false }] },
            { id: 5, type: "SELECT", question: "'No' vs 'None':", options: [{ id: "a", text: "No + noun", correct: true }, { id: "b", text: "None + noun", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I have _____ (some) work to do.", options: [{ id: "a", text: "some", correct: true }, { id: "b", text: "any", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Hiç şansın yok.", correctAnswer: "You have no chance" },
            { id: 8, type: "SELECT", question: "Use 'any' in:", options: [{ id: "a", text: "Negative and Interrogative sentences", correct: true }, { id: "b", text: "Affirmative sentences", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Is there _____ bread?", options: [{ id: "a", text: "any", correct: true }, { id: "b", text: "some", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Any person can join the club.", options: [{ id: "a", text: "Herkes (herhangi biri) kulübe katılabilir", correct: true }, { id: "b", text: "Bazı kişiler katılabilir", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Hiçbirimiz görmedik.", correctAnswer: "None of us saw it" },
            { id: 12, type: "SELECT", question: "Can 'some' be used in questions?", options: [{ id: "a", text: "Yes, for offers and requests", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I don't have _____ friends here.", options: [{ id: "a", text: "any", correct: true }, { id: "b", text: "some", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Biraz su alabilir miyim?", correctAnswer: "Can I have some water?" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "No one told me about the change.", options: [{ id: "a", text: "Değişikliği kimse bana söylemedi", correct: true }, { id: "b", text: "Bana söylediler", correct: false }] },
            { id: 16, type: "SELECT", question: "'Any' in affirmative means:", options: [{ id: "a", text: "it doesn't matter which", correct: true }, { id: "b", text: "a small amount", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I've seen _____ of these movies.", options: [{ id: "a", text: "none", correct: true }, { id: "b", text: "no", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Hiç para kalmadı.", correctAnswer: "There is no money left" },
            { id: 19, type: "SELECT", question: "None of + plural noun + ___ verb:", options: [{ id: "a", text: "Singular (Formal) / Plural (Informal)", correct: true }, { id: "b", text: "Always Plural", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Take _____ book you like.", options: [{ id: "a", text: "any", correct: true }, { id: "b", text: "some", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Much, Many, Little, Few)
            { id: 1, type: "SELECT", question: "I don't have ___ time.", options: [{ id: "a", text: "much", correct: true }, { id: "b", text: "many", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He has _____ (few) friends.", options: [{ id: "a", text: "few", correct: true }, { id: "b", text: "little", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Çok az umut var.", correctAnswer: "There is very little hope" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "A few people came to the meeting.", options: [{ id: "a", text: "Toplantıya birkaç kişi geldi", correct: true }, { id: "b", text: "Az kişi geldi", correct: false }] },
            { id: 5, type: "SELECT", question: "'Few' vs 'A few':", options: [{ id: "a", text: "A few (enough) / Few (not enough)", correct: true }, { id: "b", text: "A few (none) / Few (some)", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We have _____ (little) water left.", options: [{ id: "a", text: "a little", correct: true }, { id: "b", text: "a few", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "O kadar çok hatası var ki!", correctAnswer: "It has so many errors!" },
            { id: 8, type: "SELECT", question: "Which is used with uncountable nouns?", options: [{ id: "a", text: "much / little", correct: true }, { id: "b", text: "many / few", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "How _____ luggage do you have?", options: [{ id: "a", text: "much", correct: true }, { id: "b", text: "many", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Very little work was done today.", options: [{ id: "a", text: "Bugün çok az iş yapıldı", correct: true }, { id: "b", text: "Bugün hiç iş yapılmadı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Biraz sabra ihtiyacın var.", correctAnswer: "You need a little patience" },
            { id: 12, type: "SELECT", question: "Does 'Too many' take a plural noun?", options: [{ id: "a", text: "Yes", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "There aren't _____ (many) options.", options: [{ id: "a", text: "many", correct: true }, { id: "b", text: "much", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Çok paran var mı?", correctAnswer: "Do you have much money? / a lot of money?" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Few people live to be 100.", options: [{ id: "a", text: "Çok az insan 100 yaşına kadar yaşar", correct: true }, { id: "b", text: "Biraz insan yaşar", correct: false }] },
            { id: 16, type: "SELECT", question: "Quantifier for 'Information':", options: [{ id: "a", text: "much / a lot of", correct: true }, { id: "b", text: "many", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He made _____ (few) mistakes.", options: [{ id: "a", text: "few", correct: true }, { id: "b", text: "little", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Biraz ekmek yer misin?", correctAnswer: "Would you like some bread / a little bread?" },
            { id: 19, type: "SELECT", question: "'Quite a few' means:", options: [{ id: "a", text: "A large number", correct: true }, { id: "b", text: "A very small number", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "There's _____ (little) chance of success.", options: [{ id: "a", text: "little", correct: true }, { id: "b", text: "few", correct: false }] }
        ]
    },
    208: {
        1: [ // QUIZ 1: EASY (It-clefts: It was X who/that...)
            { id: 1, type: "SELECT", question: "It was Jack ___ stole the cookie.", options: [{ id: "a", text: "who / that", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "It was in 1969 _____ man first walked on the moon.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "when", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Seni her şeyden çok seven benim.", correctAnswer: "It is I who love you more than anything" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It is money that he wants, not fame.", options: [{ id: "a", text: "İstediği şey para, şöhret değil", correct: true }, { id: "b", text: "Para istiyor", correct: false }] },
            { id: 5, type: "SELECT", question: "Goal of an It-cleft:", options: [{ id: "a", text: "To emphasize a specific part of the sentence", correct: true }, { id: "b", text: "To ask a question", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "It was _____ (Peter) who broke the vase.", options: [{ id: "a", text: "Peter", correct: true }, { id: "b", text: "to Peter", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Sana yardım eden Ali'ydi.", correctAnswer: "It was Ali who helped you" },
            { id: 8, type: "SELECT", question: "Correct: 'It is the climate ___ I don't like.'", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "It is tonight _____ the show starts.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "where", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It was only yesterday that I heard the news.", options: [{ id: "a", text: "Haberi sadece dün duydum (vurgulu)", correct: true }, { id: "b", text: "Haberi dün duydum", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu kararı veren benim.", correctAnswer: "It is I who made this decision / It is me who made this decision" },
            { id: 12, type: "SELECT", question: "It-cleft for a place: 'It's in Paris ___ they live.'", options: [{ id: "a", text: "that / where", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It was my sister _____ (not me) who called you.", options: [{ id: "a", text: "who / that", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bozulan bilgisayardı.", correctAnswer: "It was the computer that broke down" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's the smell of coffee that I love.", options: [{ id: "a", text: "Sevdiğim şey kahve kokusu", correct: true }, { id: "b", text: "Kahveyi seviyorum", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is emphasized: 'It was for you that I did it.'", options: [{ id: "a", text: "for you", correct: true }, { id: "b", text: "I did it", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It is his honesty _____ I admire most.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Beni sinirlendiren senin tavrın.", correctAnswer: "It is your attitude that makes me angry" },
            { id: 19, type: "SELECT", question: "Cleft of: 'I love you.'", options: [{ id: "a", text: "It is you that I love.", correct: true }, { id: "b", text: "It is love you.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "It was from him _____ I learned the secret.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "who", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Pseudo-clefts: What-clefts)
            { id: 1, type: "SELECT", question: "___ I need is a holiday.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "That", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ he said surprised me.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "It was", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "İstediğim şey sadece biraz sessizlik.", correctAnswer: "What I want is just some silence" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "What happened was that we got lost.", options: [{ id: "a", text: "Olan şey kaybolmamızdı", correct: true }, { id: "b", text: "Kaybolduk", correct: false }] },
            { id: 5, type: "SELECT", question: "What-cleft for an action: '___ I did was (to) call her.'", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "That", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I hate most is being late.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "It", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Söylediği şey doğru değil.", correctAnswer: "What he said is not true" },
            { id: 8, type: "SELECT", question: "Structure: 'What + clause + ___ + emphasized part'", options: [{ id: "a", text: "is / was", correct: true }, { id: "b", text: "did / does", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ she needs is more confidence.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "It was", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "What I like about her is her sense of humor.", options: [{ id: "a", text: "Onun hakkında sevdiğim şey mizah anlayışı", correct: true }, { id: "b", text: "O çok komik", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Yapmamız gereken şey çalışmak.", correctAnswer: "What we need to do is study" },
            { id: 12, type: "SELECT", question: "Can 'What' be replaced by 'The thing that'?", options: [{ id: "a", text: "Yes", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I want to know is the truth.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "That", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onu üzen şey sınav sonuçlarıydı.", correctAnswer: "What upset him was the exam results" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "What you need is a good night's sleep.", options: [{ id: "a", text: "İhtiyacın olan şey iyi bir gece uykusu", correct: true }, { id: "b", text: "Uyumalısın", correct: false }] },
            { id: 16, type: "SELECT", question: "Reverse pseudo-cleft: 'A holiday is ___ I need.'", options: [{ id: "a", text: "what", correct: true }, { id: "b", text: "that", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I didn't like was the food.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "It was", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Önemli olan senin ne düşündüğün.", correctAnswer: "What matters is what you think" },
            { id: 19, type: "SELECT", question: "Emphasis on 'The price':", options: [{ id: "a", text: "What surprised me was the price.", correct: true }, { id: "b", text: "The price surprised me.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I have to say won't take long.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "That", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Emphatic 'do' / Emphatic Adverbs)
            { id: 1, type: "SELECT", question: "I ___ believe you, even if you don't think so.", options: [{ id: "a", text: "do", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (know) the answer, she's just shy.", options: [{ id: "a", text: "does know", correct: true }, { id: "b", text: "knows", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Seni gerçekten seviyorum (vurgulu).", correctAnswer: "I do love you / I really do love you" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I do hope you can come to my party.", options: [{ id: "a", text: "Partime gelebilmeni gerçekten umuyorum", correct: true }, { id: "b", text: "Umarım gelirsin", correct: false }] },
            { id: 5, type: "SELECT", question: "Use 'do/does/did' for emphasis in:", options: [{ id: "a", text: "Affirmative sentences (Present Simple / Past Simple)", correct: true }, { id: "b", text: "Negative sentences", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (tell) me about it, I just forgot.", options: [{ id: "a", text: "did tell", correct: true }, { id: "b", text: "told", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Ona (gerçekten) inanıyorum.", correctAnswer: "I do believe him" },
            { id: 8, type: "SELECT", question: "Emphatic adverb: 'The trip was ___ exhausted.'", options: [{ id: "a", text: "utterly / completely", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (invite) him, but he didn't come.", options: [{ id: "a", text: "did invite", correct: true }, { id: "b", text: "invited", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "If she does call, tell her I'm out.", options: [{ id: "a", text: "Olur da ararsa, dışarıda olduğumu söyle", correct: true }, { id: "b", text: "Ararsa söyle", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum (vurgulu).", correctAnswer: "I do know / I indeed know" },
            { id: 12, type: "SELECT", question: "Which is more emphatic?", options: [{ id: "a", text: "I do apologize.", correct: true }, { id: "b", text: "I apologize.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (try) my best.", options: [{ id: "a", text: "did try", correct: true }, { id: "b", text: "tried", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Gerçekten (do) üzgünüm.", correctAnswer: "I do feel sorry / I am really sorry" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He does work hard, despite what people say.", options: [{ id: "a", text: "İnsanların ne dediğine bakılırsa, o gerçekten sıkı çalışıyor", correct: true }, { id: "b", text: "Sıkı çalışıyor", correct: false }] },
            { id: 16, type: "SELECT", question: "Emphatic 'do' is used in:", options: [{ id: "a", text: "Imperatives (Do sit down!)", correct: true }, { id: "b", text: "Past Perfect", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ be quiet!", options: [{ id: "a", text: "Do", correct: true }, { id: "b", text: "Is", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Onu (gerçekten) gördüm.", correctAnswer: "I did see him" },
            { id: 19, type: "SELECT", question: "Emphatic expression for certainty:", options: [{ id: "a", text: "By all means", correct: true }, { id: "b", text: "Maybe", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (have) the receipt somewhere.", options: [{ id: "a", text: "do have", correct: true }, { id: "b", text: "have", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (All-clefts & Other Emphatic Structures)
            { id: 1, type: "SELECT", question: "___ I want is a sandwich.", options: [{ id: "a", text: "All", correct: true }, { id: "b", text: "That", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ you need is love.", options: [{ id: "a", text: "All", correct: true }, { id: "b", text: "It", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Tek yaptığım (All) hatırlatmaktı.", correctAnswer: "All I did was remind you" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The person who called was Mary.", options: [{ id: "a", text: "Arayan kişi Mary'ydi", correct: true }, { id: "b", text: "Mary aradı", correct: false }] },
            { id: 5, type: "SELECT", question: "Structure: 'The person/place/time ___ + clause + is...'", options: [{ id: "a", text: "who/where/when", correct: true }, { id: "b", text: "that", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I like most about autumn is the colors.", options: [{ id: "a", text: "What / One thing that", correct: true }, { id: "b", text: "It", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Gitmek istediğim yer Londra.", correctAnswer: "The place (where) I want to go is London" },
            { id: 8, type: "SELECT", question: "Goal of an All-cleft (All I want is...):", options: [{ id: "a", text: "To show that only one thing is involved", correct: true }, { id: "b", text: "To show everything", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I last saw him was in Paris.", options: [{ id: "a", text: "Where", correct: true }, { id: "b", text: "What", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The reason why I am here is to help.", options: [{ id: "a", text: "Burada olma sebebim yardım etmektir", correct: true }, { id: "b", text: "Yardım için geldim", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Tek ihtiyacım olan bir şans.", correctAnswer: "All I need is a chance" },
            { id: 12, type: "SELECT", question: "Which is NOT a cleft sentence?", options: [{ id: "a", text: "I just need a car.", correct: true }, { id: "b", text: "What I need is a car.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I saw was a big black dog.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "It was", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onu (vurgulu) ben yaptım.", correctAnswer: "I did it myself / It was I who did it" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Never have I been so insulted.", options: [{ id: "a", text: "Hiç bu kadar hakarete uğramamıştım", correct: true }, { id: "b", text: "Hakaret ettiler", correct: false }] },
            { id: 16, type: "SELECT", question: "Emphasis on 'The book':", options: [{ id: "a", text: "The book is what I lost.", correct: true }, { id: "b", text: "I lost the book.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "All _____ (be) said and done.", options: [{ id: "a", text: "is", correct: true }, { id: "b", text: "has", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Onunla konuştuğum yer burasıydı.", correctAnswer: "The place where I spoke with him was here" },
            { id: 19, type: "SELECT", question: "Which is correctly emphasized?", options: [{ id: "a", text: "What it is I want to say is...", correct: false }, { id: "b", text: "What I want to say is...", correct: true }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ matters is results.", options: [{ id: "a", text: "All that / What", correct: true }, { id: "b", text: "That", correct: false }] }
        ]
    },
    209: {
        1: [ // QUIZ 1: EASY (Adjective Order)
            { id: 1, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "A beautiful large old brown house", correct: true }, { id: "b", text: "A brown old large beautiful house", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She bought a _____ (silk / blue / beautiful) dress.", options: [{ id: "a", text: "beautiful blue silk", correct: true }, { id: "b", text: "blue beautiful silk", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Küçük siyah bir kedi.", correctAnswer: "A small black cat" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It was a huge, ancient, wooden door.", options: [{ id: "a", text: "Devasa, antik, ahşap bir kapıydı", correct: true }, { id: "b", text: "Eski bir kapıydı", correct: false }] },
            { id: 5, type: "SELECT", question: "General Adjective Order:", options: [{ id: "a", text: "Opinion-Size-Age-Shape-Color-Origin-Material-Purpose", correct: true }, { id: "b", text: "Color-Size-Opinion-Age", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He drives an _____ (Italian / expensive / red) car.", options: [{ id: "a", text: "expensive red Italian", correct: true }, { id: "b", text: "Italian expensive red", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Eski bir deri çanta.", correctAnswer: "An old leather bag" },
            { id: 8, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "A long sharp metal knife", correct: true }, { id: "b", text: "A metal sharp long knife", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She found a _____ (square / tiny / silver) box.", options: [{ id: "a", text: "tiny square silver", correct: true }, { id: "b", text: "silver square tiny", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We stayed in a charming little French village.", options: [{ id: "a", text: "Büyüleyici küçük bir Fransız köyünde kaldık", correct: true }, { id: "b", text: "Fransız köyü güzeldi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Büyük mavi gözleri var.", correctAnswer: "She has big blue eyes" },
            { id: 12, type: "SELECT", question: "Adjective for Purpose (last in order):", options: [{ id: "a", text: "A walking stick", correct: true }, { id: "b", text: "A stick walking", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I lost my _____ (new / red / favorite) sunglasses.", options: [{ id: "a", text: "favorite new red", correct: true }, { id: "b", text: "red favorite new", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Yuvarlak bir yemek masası.", correctAnswer: "A round dining table" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's a wonderful, sunny day.", options: [{ id: "a", text: "Harika, güneşli bir gün", correct: true }, { id: "b", text: "Güneşli bir gün", correct: false }] },
            { id: 16, type: "SELECT", question: "Which goes first?", options: [{ id: "a", text: "Opinion", correct: true }, { id: "b", text: "Material", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "They live in a _____ (modern / large / white) apartment.", options: [{ id: "a", text: "large modern white", correct: true }, { id: "b", text: "modern white large", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Genç, akıllı bir adam.", correctAnswer: "A smart young man" },
            { id: 19, type: "SELECT", question: "Correct: 'A ___ hat.'", options: [{ id: "a", text: "funny green cotton", correct: true }, { id: "b", text: "cotton green funny", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I bought some _____ (Swedish / delicious / red) apples.", options: [{ id: "a", text: "delicious red Swedish", correct: true }, { id: "b", text: "red delicious Swedish", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Gradable vs Non-gradable Adjectives)
            { id: 1, type: "SELECT", question: "Which adverb can modify 'cold' (gradable)?", options: [{ id: "a", text: "very", correct: true }, { id: "b", text: "absolutely", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The movie was _____ (absolutely) brilliant.", options: [{ id: "a", text: "absolutely", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Tamamen bitti.", correctAnswer: "It's completely / absolutely finished" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The food was quite delicious.", options: [{ id: "a", text: "Yemek oldukça lezzetliydi", correct: true }, { id: "b", text: "Yemek çok güzeldi", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is a non-gradable (extreme) adjective?", options: [{ id: "a", text: "Freezing", correct: true }, { id: "b", text: "Cold", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I'm _____ hungry.", options: [{ id: "a", text: "very / extremely", correct: true }, { id: "b", text: "absolutely", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "O kesinlikle haklı.", correctAnswer: "He is absolutely right" },
            { id: 8, type: "SELECT", question: "Adverb for non-gradable adjectives:", options: [{ id: "a", text: "utterly / absolutely / completely", correct: true }, { id: "b", text: "fairly", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "That's an _____ (impossible) task.", options: [{ id: "a", text: "absolutely", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The room was totally empty.", options: [{ id: "a", text: "Oda tamamen boştu", correct: true }, { id: "b", text: "Oda boştu", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Hava çok sıcak.", correctAnswer: "The weather is very hot" },
            { id: 12, type: "SELECT", question: "___ + exhausted:", options: [{ id: "a", text: "absolutely", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It was _____ (terrifying).", options: [{ id: "a", text: "absolutely", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Fikir tamamen saçma.", correctAnswer: "The idea is completely ridiculous" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I was extremely surprised by the result.", options: [{ id: "a", text: "Sonuç beni son derece şaşırttı", correct: true }, { id: "b", text: "Şaşırdım", correct: false }] },
            { id: 16, type: "SELECT", question: "'Quite' with non-gradable adjectives means:", options: [{ id: "a", text: "Completely", correct: true }, { id: "b", text: "Fairly", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He is _____ (intelligent).", options: [{ id: "a", text: "highly / very", correct: true }, { id: "b", text: "absolutely", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bina devasa.", correctAnswer: "The building is huge / enormous" },
            { id: 19, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "very big", correct: true }, { id: "b", text: "very enormous", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The exam was _____ (difficult).", options: [{ id: "a", text: "rather / very", correct: true }, { id: "b", text: "absolutely", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Advanced Comparison)
            { id: 1, type: "SELECT", question: "The harder you work, ___ you become.", options: [{ id: "a", text: "the more successful", correct: true }, { id: "b", text: "most successful", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "This is _____ (good) movie I've ever seen.", options: [{ id: "a", text: "the best", correct: true }, { id: "b", text: "a best", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Ne kadar erken, o kadar iyi.", correctAnswer: "The earlier, the better" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is twice as old as I am.", options: [{ id: "a", text: "O benim iki katım yaşında", correct: true }, { id: "b", text: "O benden yaşlı", correct: false }] },
            { id: 5, type: "SELECT", question: "Comparison with 'nowhere near':", options: [{ id: "a", text: "This car is nowhere near as fast as yours.", correct: true }, { id: "b", text: "This car is not near fast.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She is _____ (less) interested in sports than her brother.", options: [{ id: "a", text: "less", correct: true }, { id: "b", text: "least", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Beklediğimden daha zordu.", correctAnswer: "It was more difficult than I had expected" },
            { id: 8, type: "SELECT", question: "Repeated comparative: 'It's getting ___.'", options: [{ id: "a", text: "warmer and warmer", correct: true }, { id: "b", text: "more warm", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He is _____ (easily) the best player in the team.", options: [{ id: "a", text: "easily / by far", correct: true }, { id: "b", text: "more", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The more I know him, the more I like him.", options: [{ id: "a", text: "Onu ne kadar çok tanırsam, o kadar çok seviyorum", correct: true }, { id: "b", text: "Onu seviyorum", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "O, gruptaki açık ara en yetenekli kişi.", correctAnswer: "He is by far the most talented person in the group" },
            { id: 12, type: "SELECT", question: "Comparison: 'He is almost ___ as his father.'", options: [{ id: "a", text: "as tall", correct: true }, { id: "b", text: "tallest", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "This way is much _____ (long).", options: [{ id: "a", text: "longer", correct: true }, { id: "b", text: "as long", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Ev ne kadar büyükse, o kadar pahalıdır.", correctAnswer: "The bigger the house, the more expensive it is" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It was slightly more expensive than I thought.", options: [{ id: "a", text: "Düşündüğümden biraz daha pahalıydı", correct: true }, { id: "b", text: "Pahalıydı", correct: false }] },
            { id: 16, type: "SELECT", question: "Comparison of adverbs: 'He runs ___ than I do.'", options: [{ id: "a", text: "faster", correct: true }, { id: "b", text: "more fastly", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He works _____ (just) as hard as his colleague.", options: [{ id: "a", text: "just", correct: true }, { id: "b", text: "even", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Dünden çok daha iyi hissediyorum.", correctAnswer: "I feel much better than yesterday" },
            { id: 19, type: "SELECT", question: "Superlative with 'ever':", options: [{ id: "a", text: "The best experience I've ever had.", correct: true }, { id: "b", text: "The better experience I ever had.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "This plan is far _____ (good).", options: [{ id: "a", text: "better", correct: true }, { id: "b", text: "good", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Adverbs of Degree & Manner)
            { id: 1, type: "SELECT", question: "She sings ___ beautifully.", options: [{ id: "a", text: "incredibly / very", correct: true }, { id: "b", text: "too much", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (hardly) worked at all.", options: [{ id: "a", text: "hardly", correct: true }, { id: "b", text: "hard", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "O çok hızlı konuşur.", correctAnswer: "She speaks very fast" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He clearly explained the situation.", options: [{ id: "a", text: "Durumu net bir şekilde açıkladı", correct: true }, { id: "b", text: "Durumu açıkladı", correct: false }] },
            { id: 5, type: "SELECT", question: "Manner adverb: 'He drives ___.'", options: [{ id: "a", text: "carefully", correct: true }, { id: "b", text: "careful", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The book was _____ (fairly) interesting.", options: [{ id: "a", text: "fairly", correct: true }, { id: "b", text: "extremely", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Tamamen unutmuşum.", correctAnswer: "I've completely / entirely forgotten" },
            { id: 8, type: "SELECT", question: "Adverb of degree: 'I'm ___ tired.'", options: [{ id: "a", text: "exhausted / very / extremely", correct: true }, { id: "b", text: "badly", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (barely) made it on time.", options: [{ id: "a", text: "barely", correct: true }, { id: "b", text: "bare", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She performed the dance flawlessly.", options: [{ id: "a", text: "Dansı kusursuzca sergiledi", correct: true }, { id: "b", text: "Dans etti", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu oldukça (rather) zor.", correctAnswer: "This is rather difficult" },
            { id: 12, type: "SELECT", question: "'Well' as an adverb of manner:", options: [{ id: "a", text: "He plays guitar well.", correct: true }, { id: "b", text: "He plays guitar good.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The water is _____ (too) hot to drink.", options: [{ id: "a", text: "too", correct: true }, { id: "b", text: "enough", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Ciddi şekilde yaralandı.", correctAnswer: "He was seriously injured" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is remarkably talented.", options: [{ id: "a", text: "O dikkate değer şekilde yetenekli", correct: true }, { id: "b", text: "O yetenekli", correct: false }] },
            { id: 16, type: "SELECT", question: "Position of 'enough':", options: [{ id: "a", text: "fast enough", correct: true }, { id: "b", text: "enough fast", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (eventually) arrived.", options: [{ id: "a", text: "eventually", correct: true }, { id: "b", text: "eventual", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gerçekten naziksin.", correctAnswer: "You are truly kind / You are really kind" },
            { id: 19, type: "SELECT", question: "Adverb of manner for 'Happy':", options: [{ id: "a", text: "happily", correct: true }, { id: "b", text: "happy", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (actually) liked the movie.", options: [{ id: "a", text: "actually", correct: true }, { id: "b", text: "actual", correct: false }] }
        ]
    },
    210: {
        1: [ // QUIZ 1: EASY (Subjunctive & Inversion Review)
            { id: 1, type: "SELECT", question: "It is vital that he ___ here.", options: [{ id: "a", text: "be", correct: true }, { id: "b", text: "is", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Never _____ I seen such a mess.", options: [{ id: "a", text: "have", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gitmeni öneririm (Subjunctive).", correctAnswer: "I suggest that you go" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Should you need help, just call.", options: [{ id: "a", text: "Yardıma ihtiyacın olursa ara", correct: true }, { id: "b", text: "Yardım ettik", correct: false }] },
            { id: 5, type: "SELECT", question: "Inversion with 'Rarely':", options: [{ id: "a", text: "Rarely does he visit us.", correct: true }, { id: "b", text: "Rarely he visits us.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "It is important that she _____ (not / tell) him.", options: [{ id: "a", text: "not tell", correct: true }, { id: "b", text: "doesn't tell", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Ancak o zaman anladım.", correctAnswer: "Only then did I understand" },
            { id: 8, type: "SELECT", question: "Subjunctive: 'I insist that he ___.'", options: [{ id: "a", text: "stay", correct: true }, { id: "b", text: "stays", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Had I known, I _____ (help) you.", options: [{ id: "a", text: "would have helped", correct: true }, { id: "b", text: "will help", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Not only is he smart, but also kind.", options: [{ id: "a", text: "Sadece zeki değil, aynı zamanda naziktir", correct: true }, { id: "b", text: "Zeki ve nazik", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Senin yerinde olsam (Inversion).", correctAnswer: "Were I you / Were I in your shoes" },
            { id: 12, type: "SELECT", question: "Negative inversion after 'Under no circumstances':", options: [{ id: "a", text: "Under no circumstances should you go.", correct: true }, { id: "b", text: "Under no circumstances you should go.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It is essential that everyone _____ (be) present.", options: [{ id: "a", text: "be", correct: true }, { id: "b", text: "is", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Hiçbir yerde onu bulamadık.", correctAnswer: "Nowhere could we find him" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Scarcely had we finished when the bell rang.", options: [{ id: "a", text: "Biz bitirir bitirmez zil çaldı", correct: true }, { id: "b", text: "Zil çalınca bitirdik", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "I suggest that she read the book.", correct: true }, { id: "b", text: "I suggest she reads the book.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Only after he left _____ I realize my mistake.", options: [{ id: "a", text: "did", correct: true }, { id: "b", text: "had", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Yağmur yağarsa (Inversion).", correctAnswer: "Should it rain" },
            { id: 19, type: "SELECT", question: "Inversion with 'Little':", options: [{ id: "a", text: "Little did he know.", correct: true }, { id: "b", text: "Little he knew.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I propose that the plan _____ (change).", options: [{ id: "a", text: "be changed", correct: true }, { id: "b", text: "is changed", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Quantifiers Review)
            { id: 1, type: "SELECT", question: "___ of the students passed.", options: [{ id: "a", text: "All / Both / Each", correct: true }, { id: "b", text: "Every", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Neither of them _____ (know) the answer.", options: [{ id: "a", text: "knows / know", correct: true }, { id: "b", text: "known", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bütün gün çalıştım.", correctAnswer: "I worked all day / the whole day" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Either of the colors will look good.", options: [{ id: "a", text: "Her iki renk de güzel görünecek", correct: true }, { id: "b", text: "Renkler güzel", correct: false }] },
            { id: 5, type: "SELECT", question: "'None of' + singular/plural verb:", options: [{ id: "a", text: "None of the books is/are ready.", correct: true }, { id: "b", text: "None of the books was.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I have _____ (little) patience for this.", options: [{ id: "a", text: "little / very little", correct: true }, { id: "b", text: "few", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Her bir detayı biliyorum.", correctAnswer: "I know every single detail / each detail" },
            { id: 8, type: "SELECT", question: "Quantifier for 'Information':", options: [{ id: "a", text: "some / any / much", correct: true }, { id: "b", text: "many", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Is there _____ (any) sugar left?", options: [{ id: "a", text: "any", correct: true }, { id: "b", text: "many", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Both of them were happy.", options: [{ id: "a", text: "İkisi de mutluydu", correct: true }, { id: "b", text: "Hepsi mutluydu", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "İkisini de sevmiyorum.", correctAnswer: "I don't like either of them / I like neither of them" },
            { id: 12, type: "SELECT", question: "Quite a ___ (meaning a lot):", options: [{ id: "a", text: "few", correct: true }, { id: "b", text: "little", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "They ate the _____ cake.", options: [{ id: "a", text: "whole", correct: true }, { id: "b", text: "all", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Çok az insan biliyor.", correctAnswer: "Very few people know" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Every student must bring a pen.", options: [{ id: "a", text: "Her öğrenci bir kalem getirmeli", correct: true }, { id: "b", text: "Tüm öğrenciler kalem getirdi", correct: false }] },
            { id: 16, type: "SELECT", question: "Each of + plural noun + ___ verb:", options: [{ id: "a", text: "Singular", correct: true }, { id: "b", text: "Plural", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "There are _____ (no) apples in the basket.", options: [{ id: "a", text: "no", correct: true }, { id: "b", text: "none", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Hiçbirimiz gitmedik.", correctAnswer: "None of us went" },
            { id: 19, type: "SELECT", question: "Meaning of 'Few':", options: [{ id: "a", text: "Not enough / Very small number", correct: true }, { id: "b", text: "A good number", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I have _____ (a few) questions.", options: [{ id: "a", text: "a few", correct: true }, { id: "b", text: "few", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Emphatic Structures Review)
            { id: 1, type: "SELECT", question: "It is you ___ I love.", options: [{ id: "a", text: "that / whom / (blank)", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "What I need _____ (be) a cup of tea.", options: [{ id: "a", text: "is", correct: true }, { id: "b", text: "was", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Seni gerçekten (do) anlıyorum.", correctAnswer: "I do understand you" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "All I want is to be happy.", options: [{ id: "a", text: "Tek istediğim mutlu olmak", correct: true }, { id: "b", text: "Mutlu olmak istiyorum", correct: false }] },
            { id: 5, type: "SELECT", question: "Cleft of 'She left yesterday':", options: [{ id: "a", text: "It was yesterday that she left.", correct: true }, { id: "b", text: "Yesterday was when she left.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ I hate is waiting.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "It", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Yardım eden babamdı.", correctAnswer: "It was my father who helped" },
            { id: 8, type: "SELECT", question: "Emphatic adverb: 'I am ___ tired.'", options: [{ id: "a", text: "truly / utterly", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (invite) him to the party.", options: [{ id: "a", text: "did invite", correct: true }, { id: "b", text: "invited", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The place where we met was Paris.", options: [{ id: "a", text: "Tanıştığımız yer Paris'ti", correct: true }, { id: "b", text: "Paris'te tanıştık", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Beni üzen senin yalanlarındı.", correctAnswer: "It was your lies that upset me / What upset me was your lies" },
            { id: 12, type: "SELECT", question: "Emphatic imperative:", options: [{ id: "a", text: "Do be careful!", correct: true }, { id: "b", text: "Be careful!", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "All I did _____ (be) ask a question.", options: [{ id: "a", text: "was", correct: true }, { id: "b", text: "is", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "İstediği şey (All) sadece sessizlik.", correctAnswer: "All she wants is just silence" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "What she said was quite interesting.", options: [{ id: "a", text: "Söylediği şey oldukça ilginçti", correct: true }, { id: "b", text: "İlginç konuştu", correct: false }] },
            { id: 16, type: "SELECT", question: "Pseudo-cleft of 'He works hard':", options: [{ id: "a", text: "What he does is work hard.", correct: true }, { id: "b", text: "He works hard.", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It was his attitude _____ I disliked.", options: [{ id: "a", text: "that", correct: true }, { id: "b", text: "who", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum (vurgulu).", correctAnswer: "I do know" },
            { id: 19, type: "SELECT", question: "Which is a cleft sentence?", options: [{ id: "a", text: "The person who saw me was Ali.", correct: true }, { id: "b", text: "Ali saw me.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ matters is honesty.", options: [{ id: "a", text: "What", correct: true }, { id: "b", text: "It", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Adjectives & Adverbs Review)
            { id: 1, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "A beautiful old wooden box", correct: true }, { id: "b", text: "A wooden old beautiful box", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The movie was _____ (absolutely) awful.", options: [{ id: "a", text: "absolutely / utterly", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Ne kadar erken, o kadar iyi.", correctAnswer: "The earlier, the better" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The building was remarkably high.", options: [{ id: "a", text: "Bina dikkat çekici şekilde yüksekti", correct: true }, { id: "b", text: "Bina yüksekti", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is a non-gradable adjective?", options: [{ id: "a", text: "Freezing", correct: true }, { id: "b", text: "Cold", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He is _____ (by far) the best candidate.", options: [{ id: "a", text: "by far / easily", correct: true }, { id: "b", text: "more", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Hava gittikçe soğuyor.", correctAnswer: "The weather is getting colder and colder" },
            { id: 8, type: "SELECT", question: "Adverb of manner for 'Fast':", options: [{ id: "a", text: "fast", correct: true }, { id: "b", text: "fastly", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I am _____ (quite) finished.", options: [{ id: "a", text: "quite / almost / absolutely", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The more you study, the more you learn.", options: [{ id: "a", text: "Ne kadar çok çalışırsan o kadar çok öğrenirsin", correct: true }, { id: "b", text: "Çalış ve öğren", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Kesinlikle muhteşem.", correctAnswer: "Absolutely / Truly wonderful / magnificent" },
            { id: 12, type: "SELECT", question: "Position of 'Enough':", options: [{ id: "a", text: "tall enough", correct: true }, { id: "b", text: "enough tall", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It was _____ (slightly) more expensive.", options: [{ id: "a", text: "slightly", correct: true }, { id: "b", text: "slight", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Küçük, mavi, kare bir kutu.", correctAnswer: "A small square blue box" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He barely escaped the accident.", options: [{ id: "a", text: "Kazadan kıl payı kurtuldu", correct: true }, { id: "b", text: "Kaza yaptı", correct: false }] },
            { id: 16, type: "SELECT", question: "Extreme version of 'scared':", options: [{ id: "a", text: "terrified", correct: true }, { id: "b", text: "very scared", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She is twice _____ (old) as him.", options: [{ id: "a", text: "as old", correct: true }, { id: "b", text: "older", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gerçekten dikkate değer bir başarı.", correctAnswer: "A truly remarkable achievement" },
            { id: 19, type: "SELECT", question: "Modifier for comparative: '___ better.'", options: [{ id: "a", text: "Much / Even / Far", correct: true }, { id: "b", text: "Very", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (actually) enjoyed the play.", options: [{ id: "a", text: "actually", correct: true }, { id: "b", text: "actual", correct: false }] }
        ]
    },
};
