import { Question } from '../../questions';

export const u211_215: Record<number, Record<number, Question[]>> = {
    211: {
        1: [ // QUIZ 1: EASY (Phrasal Verbs with 'Get')
            { id: 1, type: "SELECT", question: "I really get ___ with my sister.", options: [{ id: "a", text: "along", correct: true }, { id: "b", text: "over", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "It took him a long time to get _____ (recover from) the flu.", options: [{ id: "a", text: "over", correct: true }, { id: "b", text: "up", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Nasıl geçiniyorsun (get by)?", correctAnswer: "How are you getting by?" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't worry, we'll get through this.", options: [{ id: "a", text: "Endişelenme, bunu atlatacağız", correct: true }, { id: "b", text: "Bunu yapacağız", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'Get away with':", options: [{ id: "a", text: "To escape punishment", correct: true }, { id: "b", text: "To leave a place", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I need to get _____ (leave/escape) for a few days.", options: [{ id: "a", text: "away", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Mesajı veremedim (get across).", correctAnswer: "I couldn't get the message across" },
            { id: 8, type: "SELECT", question: "Which means 'to start work/business'?", options: [{ id: "a", text: "Get down to", correct: true }, { id: "b", text: "Get out of", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She gets _____ (avoid) doing her homework.", options: [{ id: "a", text: "out of", correct: true }, { id: "b", text: "on with", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He's getting on well at his new job.", options: [{ id: "a", text: "Yeni işinde iyi ilerliyor", correct: true }, { id: "b", text: "İşe gidiyor", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "İşe koyulalım.", correctAnswer: "Let's get down to work / business" },
            { id: 12, type: "SELECT", question: "Opposite of 'Get on' (a bus):", options: [{ id: "a", text: "Get off", correct: true }, { id: "b", text: "Get out", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I can't get _____ (reach) him on the phone.", options: [{ id: "a", text: "through to", correct: true }, { id: "b", text: "on with", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Onu (get over) unuttu mu?", correctAnswer: "Has she gotten over him?" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We need to get together soon.", options: [{ id: "a", text: "Yakında bir araya gelmeliyiz", correct: true }, { id: "b", text: "Gidiyoruz", correct: false }] },
            { id: 16, type: "SELECT", question: "Meaning of 'Get at':", options: [{ id: "a", text: "To imply or suggest", correct: true }, { id: "b", text: "To look at", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "They are getting _____ (succeeding) in life.", options: [{ id: "a", text: "ahead", correct: true }, { id: "b", text: "after", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Otobüsten indik.", correctAnswer: "We got off the bus" },
            { id: 19, type: "SELECT", question: "Which means 'to find time for'?", options: [{ id: "a", text: "Get round to", correct: true }, { id: "b", text: "Get by", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Stop talking and get _____ (continue) your work.", options: [{ id: "a", text: "on with", correct: true }, { id: "b", text: "over", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Phrasal Verbs with 'Take')
            { id: 1, type: "SELECT", question: "The plane will take ___ in ten minutes.", options: [{ id: "a", text: "off", correct: true }, { id: "b", text: "up", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He takes _____ (resembles) his father.", options: [{ id: "a", text: "after", correct: true }, { id: "b", text: "on", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Yeni bir hobi edindim (take up).", correctAnswer: "I've taken up a new hobby" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The company was taken over by a rival.", options: [{ id: "a", text: "Şirket bir rakip tarafından devralındı", correct: true }, { id: "b", text: "Şirket kapandı", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'Take on':", options: [{ id: "a", text: "To employ or accept a challenge", correct: true }, { id: "b", text: "To remove clothing", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I need to take these shoes _____ (return) to the shop.", options: [{ id: "a", text: "back", correct: true }, { id: "b", text: "away", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Sözlerimi geri alıyorum.", correctAnswer: "I take back my words" },
            { id: 8, type: "SELECT", question: "Which means 'to dismantle'?", options: [{ id: "a", text: "Take apart", correct: true }, { id: "b", text: "Take down", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Don't be taken _____ (deceived) by his lies.", options: [{ id: "a", text: "in", correct: true }, { id: "b", text: "out", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Let's take out the trash.", options: [{ id: "a", text: "Çöpü dışarı çıkaralım", correct: true }, { id: "b", text: "Çöpü at", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Ceketini çıkar.", correctAnswer: "Take off your jacket" },
            { id: 12, type: "SELECT", question: "Meaning of 'Take out' (insurance/money):", options: [{ id: "a", text: "To obtain officially", correct: true }, { id: "b", text: "To throw away", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The meeting took _____ (occupied) three hours.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "over", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Not al (take down).", correctAnswer: "Take down some notes" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The new product has really taken off.", options: [{ id: "a", text: "Yeni ürün gerçekten tutuldu (başarılı oldu)", correct: true }, { id: "b", text: "Ürün kalktı", correct: false }] },
            { id: 16, type: "SELECT", question: "Which means 'to start to like'?", options: [{ id: "a", text: "Take to", correct: true }, { id: "b", text: "Take for", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I take him _____ (consider) an honest man.", options: [{ id: "a", text: "for", correct: true }, { id: "b", text: "after", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Seni eve götüreceğim.", correctAnswer: "I'll take you home" },
            { id: 19, type: "SELECT", question: "Meaning of 'Take aside':", options: [{ id: "a", text: "To speak to someone privately", correct: true }, { id: "b", text: "To throw away", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He was taken _____ (surprised) by the news.", options: [{ id: "a", text: "aback", correct: true }, { id: "b", text: "away", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Phrasal Verbs with 'Look')
            { id: 1, type: "SELECT", question: "I'm looking ___ to my holiday.", options: [{ id: "a", text: "forward", correct: true }, { id: "b", text: "after", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Could you look _____ (care for) my cat while I'm away?", options: [{ id: "a", text: "after", correct: true }, { id: "b", text: "over", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Kelimelere sözlükten bak (look up).", correctAnswer: "Look up the words in the dictionary" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The police are looking into the matter.", options: [{ id: "a", text: "Polis meseleyi araştırıyor", correct: true }, { id: "b", text: "Polis bakıyor", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'Look up to':", options: [{ id: "a", text: "To admire and respect", correct: true }, { id: "b", text: "To search for", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He looks _____ (despises) on people who are poor.", options: [{ id: "a", text: "down", correct: true }, { id: "b", text: "up", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Dikkat et (look out)!", correctAnswer: "Look out! / Watch out!" },
            { id: 8, type: "SELECT", question: "Which means 'to examine briefly'?", options: [{ id: "a", text: "Look over", correct: true }, { id: "b", text: "Look through", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I'm looking _____ (searching) for my keys.", options: [{ id: "a", text: "for", correct: true }, { id: "b", text: "into", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Things are finally looking up.", options: [{ id: "a", text: "İşler sonunda düzeliyor (iyiye gidiyor)", correct: true }, { id: "b", text: "Her şey yukarıda", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Etrafa bakıyoruz.", correctAnswer: "We are looking around" },
            { id: 12, type: "SELECT", question: "Meaning of 'Look on':", options: [{ id: "a", text: "To watch without participating", correct: true }, { id: "b", text: "To continue reading", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I just looked _____ (visited briefly) to say hello.", options: [{ id: "a", text: "in", correct: true }, { id: "b", text: "out", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Geleceğe bakmalıyız.", correctAnswer: "We must look to the future" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He looked through the reports quickly.", options: [{ id: "a", text: "Raporları hızlıca inceledi", correct: true }, { id: "b", text: "Raporları okudu", correct: false }] },
            { id: 16, type: "SELECT", question: "Which means 'to be careful'?", options: [{ id: "a", text: "Look out", correct: true }, { id: "b", text: "Look at", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I'll look _____ (search for) the information for you.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "after", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Ona (look at) bak.", correctAnswer: "Look at him" },
            { id: 19, type: "SELECT", question: "Meaning of 'Look ahead':", options: [{ id: "a", text: "To think about the future", correct: true }, { id: "b", text: "To look straight", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "We are looking _____ (considering) buying a car.", options: [{ id: "a", text: "at", correct: true }, { id: "b", text: "for", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Mixed & Three-part Phrasal Verbs)
            { id: 1, type: "SELECT", question: "I can't put ___ with your behavior anymore.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "down", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "We've run _____ (exhausted supply) of milk.", options: [{ id: "a", text: "out", correct: true }, { id: "b", text: "away", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Sana yetişeceğim (catch up).", correctAnswer: "I'll catch up with you" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is trying to cut down on sugar.", options: [{ id: "a", text: "Şekeri azaltmaya çalışıyor", correct: true }, { id: "b", text: "Şeker yemiyor", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'Go through with':", options: [{ id: "a", text: "To complete something planned", correct: true }, { id: "b", text: "To check something", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I need to brush _____ (refresh knowledge) on my French.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "out", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Randevuyu iptal ettiler (call off).", correctAnswer: "They called off the meeting / appointment" },
            { id: 8, type: "SELECT", question: "Which means 'to invent'?", options: [{ id: "a", text: "Make up", correct: true }, { id: "b", text: "Make for", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He came _____ (discovered by chance) an old photo.", options: [{ id: "a", text: "across", correct: true }, { id: "b", text: "by", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "You should stand up for your rights.", options: [{ id: "a", text: "Haklarını savunmalısın", correct: true }, { id: "b", text: "Ayağa kalk", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu fikri kim ortaya attı (come up with)?", correctAnswer: "Who came up with this idea?" },
            { id: 12, type: "SELECT", question: "Meaning of 'Break out':", options: [{ id: "a", text: "To start suddenly (war/fire)", correct: true }, { id: "b", text: "To stop working", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The car broke _____ (stopped working) in the rain.", options: [{ id: "a", text: "down", correct: true }, { id: "b", text: "out", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Nihayet ortaya çıktı (turn up).", correctAnswer: "He finally turned up" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll look back on these days with fondness.", options: [{ id: "a", text: "Bu günleri sevgiyle yad edeceğim", correct: true }, { id: "b", text: "Geriye bakacağım", correct: false }] },
            { id: 16, type: "SELECT", question: "Which means 'to compensate for'?", options: [{ id: "a", text: "Make up for", correct: true }, { id: "b", text: "Make out", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Don't let me _____ (disappoint).", options: [{ id: "a", text: "down", correct: true }, { id: "b", text: "out", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Devam et (carry on).", correctAnswer: "Carry on! / Go on!" },
            { id: 19, type: "SELECT", question: "Meaning of 'Get away':", options: [{ id: "a", text: "To go on holiday", correct: true }, { id: "b", text: "To arrive", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I need to check _____ (get information) on the price.", options: [{ id: "a", text: "up", correct: true }, { id: "b", text: "in", correct: false }] }
        ]
    },
    212: {
        1: [ // QUIZ 1: EASY (Verb-Noun Collocations: Make, Do, Take, Have)
            { id: 1, type: "SELECT", question: "Could you ___ me a favor?", options: [{ id: "a", text: "do", correct: true }, { id: "b", text: "make", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Don't _____ (make) a noise; the baby is sleeping.", options: [{ id: "a", text: "make", correct: true }, { id: "b", text: "do", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bir karar vermelisin.", correctAnswer: "You must make a decision / take a decision" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll take a look at it later.", options: [{ id: "a", text: "Ona sonra bakacağım", correct: true }, { id: "b", text: "Ona baktım", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "do homework", correct: true }, { id: "b", text: "make homework", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We need to _____ (make) a plan.", options: [{ id: "a", text: "make", correct: true }, { id: "b", text: "do", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Duş alıyorum.", correctAnswer: "I'm having a shower / taking a shower" },
            { id: 8, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "take a break", correct: true }, { id: "b", text: "do a break", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She always _____ (does) her level best.", options: [{ id: "a", text: "does", correct: true }, { id: "b", text: "makes", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He made a mistake on the application.", options: [{ id: "a", text: "Başvuruda bir hata yaptı", correct: true }, { id: "b", text: "Başvuru yaptı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Denemelisin (take/have a go).", correctAnswer: "You should have a go / take a go / give it a try" },
            { id: 12, type: "SELECT", question: "Correct: '___ progress'", options: [{ id: "a", text: "make", correct: true }, { id: "b", text: "do", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Let's _____ (have) a party.", options: [{ id: "a", text: "have", correct: true }, { id: "b", text: "make", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Fotoğraf çekebilir misin?", correctAnswer: "Can you take a photo?" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I have to do the shopping this afternoon.", options: [{ id: "a", text: "Bu öğleden sonra alışveriş yapmam gerekiyor", correct: true }, { id: "b", text: "Alışverişe gideceğim", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "make an effort", correct: true }, { id: "b", text: "do an effort", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Can you _____ (take) a seat, please?", options: [{ id: "a", text: "take / have", correct: true }, { id: "b", text: "do", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Hata yapma.", correctAnswer: "Don't make a mistake" },
            { id: 19, type: "SELECT", question: "Which is correct?", options: [{ id: "a", text: "do exercise", correct: true }, { id: "b", text: "make exercise", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (has) a lot of fun at the beach.", options: [{ id: "a", text: "has", correct: true }, { id: "b", text: "makes", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Adjective-Noun Collocations)
            { id: 1, type: "SELECT", question: "I like ___ coffee.", options: [{ id: "a", text: "strong", correct: true }, { id: "b", text: "powerful", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "We got caught in _____ (heavy) rain.", options: [{ id: "a", text: "heavy", correct: true }, { id: "b", text: "strong", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Hızlı bir yemek (quick meal).", correctAnswer: "A quick meal" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "There was a broad range of opinions.", options: [{ id: "a", text: "Geniş bir görüş yelpazesi vardı", correct: true }, { id: "b", text: "Görüşler farklıydı", correct: false }] },
            { id: 5, type: "SELECT", question: "Opposite of 'light rain':", options: [{ id: "a", text: "heavy rain", correct: true }, { id: "b", text: "thick rain", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He is a _____ (heavy) smoker.", options: [{ id: "a", text: "heavy", correct: true }, { id: "b", text: "big", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Büyük bir hayal kırıklığı.", correctAnswer: "A big disappointment / A huge disappointment" },
            { id: 8, type: "SELECT", question: "Correct: '___ traffic'", options: [{ id: "a", text: "heavy", correct: true }, { id: "b", text: "strong", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The shop has a _____ (wide) variety of items.", options: [{ id: "a", text: "wide", correct: true }, { id: "b", text: "large", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He made a solemn promise.", options: [{ id: "a", text: "Resmi (ciddi) bir söz verdi", correct: true }, { id: "b", text: "Söz verdi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Koyu bir sis (thick fog).", correctAnswer: "A thick fog / A dense fog" },
            { id: 12, type: "SELECT", question: "Correct: 'a ___ sleep'", options: [{ id: "a", text: "deep", correct: true }, { id: "b", text: "heavy", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "She has a _____ (vivid) imagination.", options: [{ id: "a", text: "vivid", correct: true }, { id: "b", text: "strong", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Zayıf bir şans (slight chance).", correctAnswer: "A slight chance / A slim chance" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The news was a bitter disappointment.", options: [{ id: "a", text: "Haber acı bir hayal kırıklığıydı", correct: true }, { id: "b", text: "Haber kötüydü", correct: false }] },
            { id: 16, type: "SELECT", question: "Correct: '___ tea'", options: [{ id: "a", text: "strong", correct: true }, { id: "b", text: "hard", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I have a _____ (nagging) feeling something is wrong.", options: [{ id: "a", text: "nagging", correct: true }, { id: "b", text: "strong", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Yüksek ses (loud noise).", correctAnswer: "A loud noise" },
            { id: 19, type: "SELECT", question: "Correct: '___ wind'", options: [{ id: "a", text: "strong / high", correct: true }, { id: "b", text: "heavy", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "It was a _____ (narrow) escape.", options: [{ id: "a", text: "narrow", correct: true }, { id: "b", text: "small", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Common Idioms)
            { id: 1, type: "SELECT", question: "The exam was a piece of ___.", options: [{ id: "a", text: "cake", correct: true }, { id: "b", text: "bread", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I'm feeling a bit under the _____ (sick) today.", options: [{ id: "a", text: "weather", correct: true }, { id: "b", text: "moon", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Baklayı ağzından çıkar (spill the beans).", correctAnswer: "Spill the beans" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It cost an arm and a leg.", options: [{ id: "a", text: "Çok pahalıya patladı", correct: true }, { id: "b", text: "Ucuzdu", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'Break the ice':", options: [{ id: "a", text: "To start a conversation in a social setting", correct: true }, { id: "b", text: "To destroy something", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "You are pulling my _____ (joking).", options: [{ id: "a", text: "leg", correct: true }, { id: "b", text: "arm", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bir taşla iki kuş vurmak.", correctAnswer: "To kill two birds with one stone" },
            { id: 8, type: "SELECT", question: "Meaning of 'Once in a blue moon':", options: [{ id: "a", text: "Very rarely", correct: true }, { id: "b", text: "Every night", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Hit the _____ (go to sleep).", options: [{ id: "a", text: "sack / hay", correct: true }, { id: "b", text: "bed", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't judge a book by its cover.", options: [{ id: "a", text: "Bir kitabı kapağına göre yargılama", correct: true }, { id: "b", text: "Kitabı oku", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Kır dök (break a leg - good luck).", correctAnswer: "Break a leg!" },
            { id: 12, type: "SELECT", question: "Meaning of 'The elephant in the room':", options: [{ id: "a", text: "An obvious problem that no one wants to discuss", correct: true }, { id: "b", text: "A big animal", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Let's call it a _____ (stop working).", options: [{ id: "a", text: "day", correct: true }, { id: "b", text: "night", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Acele işe şeytan karışır.", correctAnswer: "Haste makes waste" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She's on cloud nine.", options: [{ id: "a", text: "Çok mutlu (havalarda uçuyor)", correct: true }, { id: "b", text: "Bulutların üzerinde", correct: false }] },
            { id: 16, type: "SELECT", question: "Meaning of 'Bite the bullet':", options: [{ id: "a", text: "To endure a painful situation bravely", correct: true }, { id: "b", text: "To eat something hard", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It's not rocket _____ (easy).", options: [{ id: "a", text: "science", correct: true }, { id: "b", text: "math", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Son gülen iyi güler.", correctAnswer: "He who laughs last, laughs best" },
            { id: 19, type: "SELECT", question: "Meaning of 'Cold feet':", options: [{ id: "a", text: "To be nervous about a big decision", correct: true }, { id: "b", text: "To be cold", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Play it by _____ (improvise).", options: [{ id: "a", text: "ear", correct: true }, { id: "b", text: "mouth", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Fixed Expressions)
            { id: 1, type: "SELECT", question: "___ the long run, it will be better.", options: [{ id: "a", text: "In", correct: true }, { id: "b", text: "At", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "By _____ means, you can join us.", options: [{ id: "a", text: "all", correct: true }, { id: "b", text: "any", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Öte yandan (on the other hand).", correctAnswer: "On the other hand" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "To sum up, we need to improve.", options: [{ id: "a", text: "Özetlemek gerekirse, gelişmemiz gerekiyor", correct: true }, { id: "b", text: "Gelişmeliyiz", correct: false }] },
            { id: 5, type: "SELECT", question: "Expression for 'as far as I know':", options: [{ id: "a", text: "To the best of my knowledge", correct: true }, { id: "b", text: "In my knowledge", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ of course, I'll help you.", options: [{ id: "a", text: "As / Matther", correct: true }, { id: "b", text: "It", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Her ihtimale karşı.", correctAnswer: "Just in case" },
            { id: 8, type: "SELECT", question: "Expression for 'immediately':", options: [{ id: "a", text: "Right away / At once", correct: true }, { id: "b", text: "Soon", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "In _____ (short), we are lost.", options: [{ id: "a", text: "short / brief", correct: true }, { id: "b", text: "summarize", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's out of the question.", options: [{ id: "a", text: "Söz konusu bile değil (imkansız)", correct: true }, { id: "b", text: "Soru dışı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Eninde sonunda.", correctAnswer: "Sooner or later / Eventually" },
            { id: 12, type: "SELECT", question: "Expression for 'at the same time':", options: [{ id: "a", text: "Simultaneously / All at once", correct: true }, { id: "b", text: "Then", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "For the _____ being, stay here.", options: [{ id: "a", text: "time", correct: true }, { id: "b", text: "now", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Genel olarak (on the whole).", correctAnswer: "On the whole / In general" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Mind your own business.", options: [{ id: "a", text: "Kendi işine bak", correct: true }, { id: "b", text: "İşini yap", correct: false }] },
            { id: 16, type: "SELECT", question: "Expression for 'luckily':", options: [{ id: "a", text: "As luck would have it", correct: true }, { id: "b", text: "Funny enough", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Take it for _____ (don't question).", options: [{ id: "a", text: "granted", correct: true }, { id: "b", text: "sure", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Boşuna.", correctAnswer: "In vain" },
            { id: 19, type: "SELECT", question: "Expression for 'suddenly':", options: [{ id: "a", text: "All of a sudden", correct: true }, { id: "b", text: "Sudden", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "On _____ (purpose), he did it.", options: [{ id: "a", text: "purpose", correct: true }, { id: "b", text: "intent", correct: false }] }
        ]
    },
    213: {
        1: [ // QUIZ 1: EASY (Semicolons & Colons)
            { id: 1, type: "SELECT", question: "Which connects two independent clauses without a conjunction?", options: [{ id: "a", text: "Semicolon (;)", correct: true }, { id: "b", text: "Comma (,)", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "You have two choices _____ (colon) stay or leave.", options: [{ id: "a", text: ":", correct: true }, { id: "b", text: ";", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Ali elma sever; Veli armut sever.", correctAnswer: "Ali likes apples; Veli likes pears" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The meeting was cancelled; however, we stayed.", options: [{ id: "a", text: "Toplantı iptal edildi; ancak biz kaldık", correct: true }, { id: "b", text: "Toplantı iptal edildi ve biz kaldık", correct: false }] },
            { id: 5, type: "SELECT", question: "A colon is used to ___.", options: [{ id: "a", text: "Introduce a list or explanation", correct: true }, { id: "b", text: "Separate items in a simple list", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I need three items _____ (colon) paper, pen, and ink.", options: [{ id: "a", text: ":", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Sonuç şuydu: Kaybettik.", correctAnswer: "The result was this: we lost" },
            { id: 8, type: "SELECT", question: "Which is correct before 'however' when connecting clauses?", options: [{ id: "a", text: "Semicolon (;)", correct: true }, { id: "b", text: "Colon (:)", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She is a scientist _____ her husband is a writer.", options: [{ id: "a", text: ";", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He had one goal: success.", options: [{ id: "a", text: "Tek bir amacı vardı: başarı", correct: true }, { id: "b", text: "Başarıya ulaştı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "İş bitti; eve gidelim.", correctAnswer: "The work is finished; let's go home" },
            { id: 12, type: "SELECT", question: "Use a colon to separate hours and minutes:", options: [{ id: "a", text: "10:30", correct: true }, { id: "b", text: "10,30", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The ingredients are as follows _____ eggs, milk, sugar.", options: [{ id: "a", text: ":", correct: true }, { id: "b", text: ";", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Üzgünüm; yardım edemem.", correctAnswer: "I'm sorry; I can't help" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Bring the Following: a map and a compass.", options: [{ id: "a", text: "Şunları getir: bir harita ve pusula", correct: true }, { id: "b", text: "Haritayı getir", correct: false }] },
            { id: 16, type: "SELECT", question: "Can a semicolon be used in a list with commas?", options: [{ id: "a", text: "Yes, to separate complex items", correct: true }, { id: "b", text: "No, never", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I visited London, England _____ Paris, France.", options: [{ id: "a", text: ";", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Biliyorum (semicolon) haklısın.", correctAnswer: "I know; you are right" },
            { id: 19, type: "SELECT", question: "Which is used after a formal salutation?", options: [{ id: "a", text: "Colon (in US) / Comma", correct: true }, { id: "b", text: "Semicolon", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He said it himself _____ 'I am guilty'.", options: [{ id: "a", text: ":", correct: true }, { id: "b", text: ",", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Hyphens & Dashes)
            { id: 1, type: "SELECT", question: "Which is used to link words together (e.g. well-known)?", options: [{ id: "a", text: "Hyphen (-)", correct: true }, { id: "b", text: "Dash (—)", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "She is a twenty _____ year _____ old woman.", options: [{ id: "a", text: "hyphen / hyphen (- / -)", correct: true }, { id: "b", text: "dash / dash", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Kendi kendine yardım (self-help).", correctAnswer: "Self-help" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It was a life-changing experience.", options: [{ id: "a", text: "Hayat değiştiren (vurgulu hyphen) bir deneyimdi", correct: true }, { id: "b", text: "Hayatım değişti", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is used to show a break in a sentence or emphasis?", options: [{ id: "a", text: "Dash (—)", correct: true }, { id: "b", text: "Hyphen (-)", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "My brother _____ the one in the Army _____ called me.", options: [{ id: "a", text: "dash / dash", correct: true }, { id: "b", text: "hyphen / hyphen", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "İyi bilinen (well-known).", correctAnswer: "Well-known" },
            { id: 8, type: "SELECT", question: "Compound adjective before noun: 'A ___ dog.'", options: [{ id: "a", text: "good-looking", correct: true }, { id: "b", text: "good looking", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Thirty _____ five people came.", options: [{ id: "a", text: "-", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It was a high-risk strategy.", options: [{ id: "a", text: "Yüksek riskli bir stratejiydi", correct: true }, { id: "b", text: "Riskli bir işti", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Son dakika haberi (last-minute).", correctAnswer: "Last-minute news" },
            { id: 12, type: "SELECT", question: "Suffix with hyphen for numbers:", options: [{ id: "a", text: "twenty-one", correct: true }, { id: "b", text: "twenty one", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "A half _____ hour wait.", options: [{ id: "a", text: "hyphen (-)", correct: true }, { id: "b", text: "blank", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Eski eş (ex-wife).", correctAnswer: "Ex-wife" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is a world-class athlete.", options: [{ id: "a", text: "Dünya çapında bir atlet", correct: true }, { id: "b", text: "İyi bir atlet", correct: false }] },
            { id: 16, type: "SELECT", question: "Which dash is longer?", options: [{ id: "a", text: "Em dash (—)", correct: true }, { id: "b", text: "En dash (–)", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Non _____ smoker.", options: [{ id: "a", text: "hyphen (-)", correct: true }, { id: "b", text: "blank", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Aniden — her şey değişti.", correctAnswer: "Suddenly — everything changed" },
            { id: 19, type: "SELECT", question: "Prefixes like 're-' with 'e':", options: [{ id: "a", text: "re-elect", correct: true }, { id: "b", text: "reelect", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The Great _____ West.", options: [{ id: "a", text: "hyphen (-)", correct: true }, { id: "b", text: "blank", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Formal vs Informal Style)
            { id: 1, type: "SELECT", question: "Which is more formal?", options: [{ id: "a", text: "Furthermore", correct: true }, { id: "b", text: "And", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (Formal), the results were positive.", options: [{ id: "a", text: "In conclusion / Consequently", correct: true }, { id: "b", text: "To end it", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu konuda (Formal - regarding).", correctAnswer: "Regarding this matter / Concerning this" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Should you require further assistance, contact us.", options: [{ id: "a", text: "Daha fazla yardıma ihtiyaç duyarsanız bizimle iletişime geçin", correct: true }, { id: "b", text: "Yardım için arayın", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is appropriate for a business letter?", options: [{ id: "a", text: "Yours sincerely", correct: true }, { id: "b", text: "Best wishes / Cheers", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (buy) -> Purchase (Formal).", options: [{ id: "a", text: "Purchase", correct: true }, { id: "b", text: "Buy", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Üzgünüm (Formal - I apologize).", correctAnswer: "I apologize / I would like to express my regret" },
            { id: 8, type: "SELECT", question: "Avoid use of ___ in formal writing.", options: [{ id: "a", text: "Contractions (don't, can't)", correct: true }, { id: "b", text: "Complex sentences", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (check) -> Verify (Formal).", options: [{ id: "a", text: "Verify", correct: true }, { id: "b", text: "Check", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The data indicates a significant increase.", options: [{ id: "a", text: "Veriler önemli bir artışa işaret ediyor", correct: true }, { id: "b", text: "Artış var", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Söyleyebilirim ki (Formal - I would argue that).", correctAnswer: "I would argue that / It could be argued that" },
            { id: 12, type: "SELECT", question: "Which is a formal way to say 'enough'?", options: [{ id: "a", text: "sufficient", correct: true }, { id: "b", text: "plenty", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (think about) -> Consider (Formal).", options: [{ id: "a", text: "Consider", correct: true }, { id: "b", text: "Think about", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bu nedenle (Formal - therefore).", correctAnswer: "Therefore / Consequently" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It is considered improper to arrive late.", options: [{ id: "a", text: "Geç gelmek uygunsuz kabul edilir", correct: true }, { id: "b", text: "Geç kalma", correct: false }] },
            { id: 16, type: "SELECT", question: "Formal way to say 'start'?", options: [{ id: "a", text: "commence", correct: true }, { id: "b", text: "begin", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (help) -> Assist (Formal).", options: [{ id: "a", text: "Assist", correct: true }, { id: "b", text: "Help", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Daha önce de belirttiğimiz gibi.", correctAnswer: "As previously stated / As mentioned before" },
            { id: 19, type: "SELECT", question: "In formal writing, do not start sentences with ___.", options: [{ id: "a", text: "But / And / So", correct: true }, { id: "b", text: "However / Nevertheless", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (tell) -> Inform (Formal).", options: [{ id: "a", text: "Inform", correct: true }, { id: "b", text: "Tell", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Substitution & Ellipsis)
            { id: 1, type: "SELECT", question: "A: Do you like tea? B: I hope ___.", options: [{ id: "a", text: "so", correct: true }, { id: "b", text: "not", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I wanted to go, but I couldn't _____ (go).", options: [{ id: "a", text: "(blank)", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Ben de öyle umuyorum.", correctAnswer: "I hope so" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He likes swimming, and so do I.", options: [{ id: "a", text: "O yüzmeyi seviyor, ben de", correct: true }, { id: "b", text: "Yüzmeyi seviyoruz", correct: false }] },
            { id: 5, type: "SELECT", question: "Use 'one' to avoid repeating a singular noun:", options: [{ id: "a", text: "Which one do you want?", correct: true }, { id: "b", text: "Which you want?", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He might call, and if he _____ (calls), tell him I'm out.", options: [{ id: "a", text: "does", correct: true }, { id: "b", text: "calls", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Zannetmiyorum.", correctAnswer: "I don't think so / I suppose not" },
            { id: 8, type: "SELECT", question: "Which avoids repetition of 'plural nouns'?", options: [{ id: "a", text: "ones", correct: true }, { id: "b", text: "some", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "She likes ice cream; I _____ too.", options: [{ id: "a", text: "do", correct: true }, { id: "b", text: "like", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I've seen many movies, but none as good as this one.", options: [{ id: "a", text: "Çok film gördüm ama bunun kadarı yok (ones/one replacement)", correct: true }, { id: "b", text: "Bu film iyi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Diğerini (one) seç.", correctAnswer: "Choose the other one" },
            { id: 12, type: "SELECT", question: "Ellipsis in 'I went and saw it':", options: [{ id: "a", text: "Omission of 'I' in the second clause", correct: true }, { id: "b", text: "Adding 'I' back", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "A: Are you ready? B: I _____.", options: [{ id: "a", text: "am / believe so", correct: true }, { id: "b", text: "be", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Öyle mi? (so/not)", correctAnswer: "Is that so? / Is it?" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'd like to help, but I can't.", options: [{ id: "a", text: "Yardım etmek isterdim ama edemem (ellipsis)", correct: true }, { id: "b", text: "Yardım edeceğim", correct: false }] },
            { id: 16, type: "SELECT", question: "Substitute for a verb phrase:", options: [{ id: "a", text: "do / so", correct: true }, { id: "b", text: "it", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "A: Will it rain? B: I think _____.", options: [{ id: "a", text: "so / not", correct: true }, { id: "b", text: "it", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Herkes biliyor, ama o bilmiyor (substitution).", correctAnswer: "Everyone knows, but he doesn't" },
            { id: 19, type: "SELECT", question: "Can we use 'do so' to avoid repeating a verb?", options: [{ id: "a", text: "Yes (He told me to go, and I did so)", correct: true }, { id: "b", text: "No", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "I'll take the red shirt and the blue _____.", options: [{ id: "a", text: "one", correct: true }, { id: "b", text: "ones", correct: false }] }
        ]
    },
    214: {
        1: [ // QUIZ 1: EASY (Greek/Latin Prefixes)
            { id: 1, type: "SELECT", question: "Prefix meaning 'against':", options: [{ id: "a", text: "anti-", correct: true }, { id: "b", text: "pro-", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The project was _____ (national) - involving many countries.", options: [{ id: "a", text: "international / multinational", correct: true }, { id: "b", text: "antinational", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Anlaşmazlık (dis-).", correctAnswer: "Disagreement" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is a pro-democracy activist.", options: [{ id: "a", text: "O, demokrasi yanlısı bir aktivist", correct: true }, { id: "b", text: "Demokrasiye karşı", correct: false }] },
            { id: 5, type: "SELECT", question: "Prefix meaning 'many':", options: [{ id: "a", text: "multi-", correct: true }, { id: "b", text: "semi-", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The water was _____ (pollute) - it was clean.", options: [{ id: "a", text: "unpolluted", correct: true }, { id: "b", text: "dispolluted", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Yanlış anlama (mis-).", correctAnswer: "Misunderstanding" },
            { id: 8, type: "SELECT", question: "Prefix meaning 'half':", options: [{ id: "a", text: "semi- / hemi-", correct: true }, { id: "b", text: "bi-", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The building was _____ (structure) - it was rebuilt.", options: [{ id: "a", text: "restructured", correct: true }, { id: "b", text: "unstructured", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's an auto-biography.", options: [{ id: "a", text: "Bir otobiyografi", correct: true }, { id: "b", text: "Bir biyografi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Görünmez (in-).", correctAnswer: "Invisible" },
            { id: 12, type: "SELECT", question: "Prefix meaning 'before':", options: [{ id: "a", text: "pre-", correct: true }, { id: "b", text: "post-", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "He is _____ (lingual) - speaks two languages.", options: [{ id: "a", text: "bilingual / multilingual", correct: true }, { id: "b", text: "unilingual", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Savaş sonrası (post-).", correctAnswer: "Post-war" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's a sub-zero temperature.", options: [{ id: "a", text: "Sıfırın altında bir sıcaklık", correct: true }, { id: "b", text: "Sıcak bir hava", correct: false }] },
            { id: 16, type: "SELECT", question: "Prefix meaning 'wrongly':", options: [{ id: "a", text: "mis-", correct: true }, { id: "b", text: "anti-", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The car was _____ (power) - it was very weak.", options: [{ id: "a", text: "underpowered", correct: true }, { id: "b", text: "overpowered", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Yetersiz (in-).", correctAnswer: "Inadequate / Insufficient" },
            { id: 19, type: "SELECT", question: "Prefix meaning 'self':", options: [{ id: "a", text: "auto-", correct: true }, { id: "b", text: "self-", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The soup was _____ (cook) - it was burnt.", options: [{ id: "a", text: "overcooked", correct: true }, { id: "b", text: "undercooked", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Suffixes for Professions & Concepts)
            { id: 1, type: "SELECT", question: "Suffix for a person who does science:", options: [{ id: "a", text: "-ist", correct: true }, { id: "b", text: "-ment", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "His _____ (happy) means everything to me.", options: [{ id: "a", text: "happiness", correct: true }, { id: "b", text: "happiment", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Yönetici (manage + er/or).", correctAnswer: "Manager / Director" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is a famous musician.", options: [{ id: "a", text: "O ünlü bir müzisyen", correct: true }, { id: "b", text: "Müzik yapıyor", correct: false }] },
            { id: 5, type: "SELECT", question: "Suffix for an abstract concept or state:", options: [{ id: "a", text: "-hood / -ness / -ship", correct: true }, { id: "b", text: "-er", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Their _____ (friend) lasted for years.", options: [{ id: "a", text: "friendship", correct: true }, { id: "b", text: "friendhood", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Çocukluk (child + hood).", correctAnswer: "Childhood" },
            { id: 8, type: "SELECT", question: "Suffix for 'result of an action':", options: [{ id: "a", text: "-ment / -ion", correct: true }, { id: "b", text: "-less", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I need your _____ (agree) on this.", options: [{ id: "a", text: "agreement", correct: true }, { id: "b", text: "agreeance", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She's a talented photographer.", options: [{ id: "a", text: "Yetenekli bir fotoğrafçı", correct: true }, { id: "b", text: "Fotoğraf çekiyor", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Özgürlük (free + dom).", correctAnswer: "Freedom" },
            { id: 12, type: "SELECT", question: "Suffix meaning 'full of':", options: [{ id: "a", text: "-ful", correct: true }, { id: "b", text: "-less", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The situation was _____ (hope).", options: [{ id: "a", text: "hopeful / hopeless", correct: true }, { id: "b", text: "hopement", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Nezaket (kind + ness).", correctAnswer: "Kindness" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Education is key.", options: [{ id: "a", text: "Eğitim anahtardır", correct: true }, { id: "b", text: "Okul iyidir", correct: false }] },
            { id: 16, type: "SELECT", question: "Suffix for 'ability':", options: [{ id: "a", text: "-able / -ible", correct: true }, { id: "b", text: "-ous", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It's an _____ (enjoy) trip.", options: [{ id: "a", text: "enjoyable", correct: true }, { id: "b", text: "enjoyment", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Yaratıcılık (create + ity).", correctAnswer: "Creativity" },
            { id: 19, type: "SELECT", question: "Suffix for 'study of':", options: [{ id: "a", text: "-logy", correct: true }, { id: "b", text: "-ism", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He is an _____ (economy) expert.", options: [{ id: "a", text: "economic / economy", correct: true }, { id: "b", text: "economically", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Word Families)
            { id: 1, type: "SELECT", question: "Noun form of 'Wide':", options: [{ id: "a", text: "Width", correct: true }, { id: "b", text: "Wideness", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "We need to _____ (wide) the road.", options: [{ id: "a", text: "widen", correct: true }, { id: "b", text: "width", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Başarı (succeed -> noun).", correctAnswer: "Success" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The strength of the bridge is impressive.", options: [{ id: "a", text: "Köprünün gücü etkileyici", correct: true }, { id: "b", text: "Köprü büyük", correct: false }] },
            { id: 5, type: "SELECT", question: "Adjective form of 'Danger':", options: [{ id: "a", text: "Dangerous", correct: true }, { id: "b", text: "Dangerly", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (success) in passing the exam.", options: [{ id: "a", text: "succeeded", correct: true }, { id: "b", text: "successful", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Derinlik (deep -> noun).", correctAnswer: "Depth" },
            { id: 8, type: "SELECT", question: "Verb form of 'Strong':", options: [{ id: "a", text: "Strengthen", correct: true }, { id: "b", text: "Strongen", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (high) of the building is 100 meters.", options: [{ id: "a", text: "height", correct: true }, { id: "b", text: "highness", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It was a courageous decision.", options: [{ id: "a", text: "Cesurca bir karardı", correct: true }, { id: "b", text: "İyi bir karardı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Büyüme (grow -> noun).", correctAnswer: "Growth" },
            { id: 12, type: "SELECT", question: "Adverb form of 'Real':", options: [{ id: "a", text: "Really / Actually", correct: true }, { id: "b", text: "Real", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (belief) you.", options: [{ id: "a", text: "believe", correct: true }, { id: "b", text: "belief", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Uzunluk (long -> noun).", correctAnswer: "Length" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Personal growth is important.", options: [{ id: "a", text: "Kişisel gelişim (büyüme) önemlidir", correct: true }, { id: "b", text: "Çalışmak iyidir", correct: false }] },
            { id: 16, type: "SELECT", question: "Noun form of 'Believe':", options: [{ id: "a", text: "Belief", correct: true }, { id: "b", text: "Believement", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The water is _____ (deep).", options: [{ id: "a", text: "deep", correct: true }, { id: "b", text: "depth", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Düzeltme (correct -> noun).", correctAnswer: "Correction" },
            { id: 19, type: "SELECT", question: "Verb form of 'Short':", options: [{ id: "a", text: "Shorten", correct: true }, { id: "b", text: "Short", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He is a very _____ (intelligence) person.", options: [{ id: "a", text: "intelligent", correct: true }, { id: "b", text: "intelligence", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Mixed Word Formation)
            { id: 1, type: "SELECT", question: "Choose the correct word:", options: [{ id: "a", text: "Unbelievable", correct: true }, { id: "b", text: "Disbelievable", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (equip) is ready.", options: [{ id: "a", text: "equipment", correct: true }, { id: "b", text: "equipping", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gözden kaçırmak (over-).", correctAnswer: "Overlook" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The expansion of the universe is fascinating.", options: [{ id: "a", text: "Evrenin genişlemesi büyüleyici", correct: true }, { id: "b", text: "Evren büyük", correct: false }] },
            { id: 5, type: "SELECT", question: "Choose the correct word:", options: [{ id: "a", text: "Mismanagement", correct: true }, { id: "b", text: "Unmanagement", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "He is _____ (replace) in this team.", options: [{ id: "a", text: "irreplaceable", correct: true }, { id: "b", text: "unreplaceable", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Geliştirmek (improve -> noun).", correctAnswer: "Improvement" },
            { id: 8, type: "SELECT", question: "Choose the correct word:", options: [{ id: "a", text: "Illiteracy", correct: true }, { id: "b", text: "Unliteracy", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I don't like _____ (kind).", options: [{ id: "a", text: "unkindness", correct: true }, { id: "b", text: "diskindness", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Her performance was exceptional.", options: [{ id: "a", text: "Performansı olağanüstüydü", correct: true }, { id: "b", text: "İyiydi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Yetersiz (inadequate).", correctAnswer: "Inadequate" },
            { id: 12, type: "SELECT", question: "Choose the correct word:", options: [{ id: "a", text: "Coexistence", correct: true }, { id: "b", text: "Inexistence", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (prepare) took all day.", options: [{ id: "a", text: "preparation", correct: true }, { id: "b", text: "preparedness", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bağımsızlık.", correctAnswer: "Independence" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Technological advancement is rapid.", options: [{ id: "a", text: "Teknolojik ilerleme hızlıdır", correct: true }, { id: "b", text: "Teknoloji iyidir", correct: false }] },
            { id: 16, type: "SELECT", question: "Choose the correct word:", options: [{ id: "a", text: "Unprecedented", correct: true }, { id: "b", text: "Imprecedented", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It was an _____ (expect) result.", options: [{ id: "a", text: "unexpected", correct: true }, { id: "b", text: "disexpected", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Girişimci (enterprise -> person).", correctAnswer: "Entrepreneur" },
            { id: 19, type: "SELECT", question: "Choose the correct word:", options: [{ id: "a", text: "Multiculturalism", correct: true }, { id: "b", text: "Biculturalism", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (organize) was perfect.", options: [{ id: "a", text: "organization / organisation", correct: true }, { id: "b", text: "organizing", correct: false }] }
        ]
    },
    215: {
        1: [ // QUIZ 1: EASY (Phrasal Verbs Review)
            { id: 1, type: "SELECT", question: "Meaning of 'Get along with':", options: [{ id: "a", text: "To have a good relationship", correct: true }, { id: "b", text: "To leave", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The plane will _____ (take) off soon.", options: [{ id: "a", text: "take", correct: true }, { id: "b", text: "get", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Yeni bir işe koyulalım (get down to).", correctAnswer: "Let's get down to business / work" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He takes after his grandfather.", options: [{ id: "a", text: "Büyükbabasına çekmiş (benziyor)", correct: true }, { id: "b", text: "Büyükbabasına bakıyor", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'Look into':", options: [{ id: "a", text: "To investigate", correct: true }, { id: "b", text: "To watch", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I'm looking _____ (forward) to seeing you.", options: [{ id: "a", text: "forward", correct: true }, { id: "b", text: "after", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Ona çok saygı duyuyorum (look up to).", correctAnswer: "I look up to him a lot" },
            { id: 8, type: "SELECT", question: "Which means 'to tolerate'?", options: [{ id: "a", text: "Put up with", correct: true }, { id: "b", text: "Put down", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "We ran _____ (out) of sugar.", options: [{ id: "a", text: "out", correct: true }, { id: "b", text: "away", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't let me down.", options: [{ id: "a", text: "Beni hayal kırıklığına uğratma", correct: true }, { id: "b", text: "Beni bırakma", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Mesajı iletebildin mi (get across)?", correctAnswer: "Did you get the message across?" },
            { id: 12, type: "SELECT", question: "Meaning of 'Call off':", options: [{ id: "a", text: "To cancel", correct: true }, { id: "b", text: "To postpone", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The car _____ (broke) down.", options: [{ id: "a", text: "broke", correct: true }, { id: "b", text: "took", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Sana az önce (get back to) dönecektim.", correctAnswer: "I was just about to get back to you" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I can't get over how much you've grown.", options: [{ id: "a", text: "Ne kadar büyüdüğüne inanamıyorum (get over - şaşkınlık/atlatma)", correct: true }, { id: "b", text: "Büyüdün", correct: false }] },
            { id: 16, type: "SELECT", question: "Meaning of 'Look after':", options: [{ id: "a", text: "To care for", correct: true }, { id: "b", text: "To search for", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (took) up tennis last year.", options: [{ id: "a", text: "took", correct: true }, { id: "b", text: "get", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Sözlükten bak (look up).", correctAnswer: "Look it up in the dictionary" },
            { id: 19, type: "SELECT", question: "Meaning of 'Get away with':", options: [{ id: "a", text: "To escape punishment", correct: true }, { id: "b", text: "To go away", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He came _____ (across) an old friend.", options: [{ id: "a", text: "across", correct: true }, { id: "b", text: "by", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Collocations & Idioms Review)
            { id: 1, type: "SELECT", question: "Correct: '___ a favor'", options: [{ id: "a", text: "do", correct: true }, { id: "b", text: "make", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The coffee is too _____ (strong).", options: [{ id: "a", text: "strong", correct: true }, { id: "b", text: "powerful", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Önemli bir karar (make/take decision).", correctAnswer: "An important decision" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's a piece of cake.", options: [{ id: "a", text: "Çocuk oyuncağı (çok kolay)", correct: true }, { id: "b", text: "Bir parça kek", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'Under the weather':", options: [{ id: "a", text: "Feeling slightly ill", correct: true }, { id: "b", text: "Being outside", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We had _____ (heavy) traffic.", options: [{ id: "a", text: "heavy", correct: true }, { id: "b", text: "strong", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bir şans ver (have a go).", correctAnswer: "Give it a go / Have a go" },
            { id: 8, type: "SELECT", question: "Correct: '___ homework'", options: [{ id: "a", text: "do", correct: true }, { id: "b", text: "make", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Don't pull my _____ (leg).", options: [{ id: "a", text: "leg", correct: true }, { id: "b", text: "arm", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He cost an arm and a leg.", options: [{ id: "a", text: "Çok pahalıydı", correct: true }, { id: "b", text: "Yaralandı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Başarılar (break a leg).", correctAnswer: "Break a leg / Good luck" },
            { id: 12, type: "SELECT", question: "Correct: '___ progress'", options: [{ id: "a", text: "make", correct: true }, { id: "b", text: "do", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "In the long _____ (run), we'll see.", options: [{ id: "a", text: "run", correct: true }, { id: "b", text: "way", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Kendi işine bak.", correctAnswer: "Mind your own business" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's out of the question.", options: [{ id: "a", text: "Mümkün değil", correct: true }, { id: "b", text: "Soru sor", correct: false }] },
            { id: 16, type: "SELECT", question: "Meaning of 'Once in a blue moon':", options: [{ id: "a", text: "Very rarely", correct: true }, { id: "b", text: "Sometimes", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Take it for _____ (granted).", options: [{ id: "a", text: "granted", correct: true }, { id: "b", text: "sure", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Hata yaptım.", correctAnswer: "I made a mistake" },
            { id: 19, type: "SELECT", question: "Correct: '___ noise'", options: [{ id: "a", text: "make", correct: true }, { id: "b", text: "do", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "She is on cloud _____ (nine).", options: [{ id: "a", text: "nine", correct: true }, { id: "b", text: "ten", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Style & Punctuation Review)
            { id: 1, type: "SELECT", question: "Which is more formal?", options: [{ id: "a", text: "consequently", correct: true }, { id: "b", text: "so", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I visited Rome, Italy _____ Paris, France.", options: [{ id: "a", text: "; (semicolon)", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu konuda (regarding).", correctAnswer: "Regarding this matter / Concerning this" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Should you have any questions, feel free to ask.", options: [{ id: "a", text: "Herhangi bir sorunuz olursa çekinmeden sorun", correct: true }, { id: "b", text: "Soru sorun", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is used for a list introductory phrase?", options: [{ id: "a", text: "Colon (:)", correct: true }, { id: "b", text: "Comma", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "A twenty _____ (hyphen) year _____ old.", options: [{ id: "a", text: "- / -", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Onu (one) seç.", correctAnswer: "Choose that one" },
            { id: 8, type: "SELECT", question: "Substitution in 'I hope ___':", options: [{ id: "a", text: "so / not", correct: true }, { id: "b", text: "it", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He said _____ (comma) 'Yes'.", options: [{ id: "a", text: ",", correct: true }, { id: "b", text: ":", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "In conclusion, the study was successful.", options: [{ id: "a", text: "Sonuç olarak çalışma aşamalı geçti (başarılıydı)", correct: true }, { id: "b", text: "Çalışmaya başladık", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Ben de öyle sanıyorum (I suppose so).", correctAnswer: "I suppose so / I think so" },
            { id: 12, type: "SELECT", question: "Which dash is for emphasis?", options: [{ id: "a", text: "Em dash (—)", correct: true }, { id: "b", text: "Hyphen (-)", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Purchase _____ (formal) -> Buy (informal).", options: [{ id: "a", text: "Purchase", correct: true }, { id: "b", text: "Buy", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Özetle.", correctAnswer: "To sum up / In summary / In short" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't judge a book by its cover.", options: [{ id: "a", text: "Kapağa göre yargılama", correct: true }, { id: "b", text: "Kitabı oku", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is a formal greeting?", options: [{ id: "a", text: "Dear Sir/Madam", correct: true }, { id: "b", text: "Hi there", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She is a scientist _____ her brother is a lawyer.", options: [{ id: "a", text: "; (semicolon)", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bu nedenle.", correctAnswer: "Therefore / Consequently" },
            { id: 19, type: "SELECT", question: "Ellipsis: 'I want to go, but I can't ___.'", options: [{ id: "a", text: "(blank)", correct: true }, { id: "b", text: "help", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Assist _____ (formal) -> Help (informal).", options: [{ id: "a", text: "Assist", correct: true }, { id: "b", text: "Help", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Word Building Review)
            { id: 1, type: "SELECT", question: "Noun form of 'Grow':", options: [{ id: "a", text: "Growth", correct: true }, { id: "b", text: "Growing", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The idea was _____ (believable).", options: [{ id: "a", text: "unbelievable", correct: true }, { id: "b", text: "disbelievable", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Derinlik (depth).", correctAnswer: "Depth" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "She has great creativity.", options: [{ id: "a", text: "Büyük bir yaratıcılığı var", correct: true }, { id: "b", text: "O yaratıcı", correct: false }] },
            { id: 5, type: "SELECT", question: "Adjective form of 'Succeed':", options: [{ id: "a", text: "Successful", correct: true }, { id: "b", text: "Successive", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The road was _____ (wide).", options: [{ id: "a", text: "widened", correct: true }, { id: "b", text: "width", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Geliştirmek (improve -> noun).", correctAnswer: "Improvement" },
            { id: 8, type: "SELECT", question: "Prefix for 'against':", options: [{ id: "a", text: "anti-", correct: true }, { id: "b", text: "pro-", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "His _____ (happy) is important.", options: [{ id: "a", text: "happiness", correct: true }, { id: "b", text: "happiment", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Technological advancement is quick.", options: [{ id: "a", text: "Teknolojik ilerleme hızlıdır", correct: true }, { id: "b", text: "Teknoloji iyidir", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Girişimci.", correctAnswer: "Entrepreneur" },
            { id: 12, type: "SELECT", question: "Suffix for professions:", options: [{ id: "a", text: "-er / -ist / -or", correct: true }, { id: "b", text: "-less", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I need your _____ (agree).", options: [{ id: "a", text: "agreement", correct: true }, { id: "b", text: "agreeance", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Görünmez (invisible).", correctAnswer: "Invisible" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Education is essential.", options: [{ id: "a", text: "Eğitim gereklidir", correct: true }, { id: "b", text: "Okul gereklidir", correct: false }] },
            { id: 16, type: "SELECT", question: "Prefix meaning 'self':", options: [{ id: "a", text: "auto-", correct: true }, { id: "b", text: "self-", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He is _____ (lingual).", options: [{ id: "a", text: "bilingual / multilingual", correct: true }, { id: "b", text: "unilingual", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Nezaket.", correctAnswer: "Kindness" },
            { id: 19, type: "SELECT", question: "Verb form of 'Strong':", options: [{ id: "a", text: "Strengthen", correct: true }, { id: "b", text: "Strongen", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The building height is low.", options: [{ id: "a", text: "height", correct: true }, { id: "b", text: "highness", correct: false }] }
        ]
    },
};
