import { Question } from '../../questions';

export const u216_220: Record<number, Record<number, Question[]>> = {
    216: {
        1: [ // QUIZ 1: EASY (Understanding Tone & Register)
            { id: 1, type: "SELECT", question: "Which word best describes a formal tone?", options: [{ id: "a", text: "objective", correct: true }, { id: "b", text: "slang", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The tone of a scientific paper should be _____ (neutral).", options: [{ id: "a", text: "neutral / objective", correct: true }, { id: "b", text: "passionate", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu yazı çok resmi.", correctAnswer: "This writing is very formal" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The author expresses a sense of urgency.", options: [{ id: "a", text: "Yazar bir aciliyet duygusu ifade ediyor", correct: true }, { id: "b", text: "Yazar mutlu", correct: false }] },
            { id: 5, type: "SELECT", question: "Which register is used with friends?", options: [{ id: "a", text: "Informal", correct: true }, { id: "b", text: "Formal", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Using 'consequently' indicates a _____ (formal) register.", options: [{ id: "a", text: "formal", correct: true }, { id: "b", text: "casual", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Eleştirel bir bakış açısı.", correctAnswer: "A critical perspective / viewpoint" },
            { id: 8, type: "SELECT", question: "Tone in: 'I'll never forgive you!'", options: [{ id: "a", text: "angry / resentful", correct: true }, { id: "b", text: "joyful", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The speaker's tone was _____ (sarcastic).", options: [{ id: "a", text: "sarcastic", correct: true }, { id: "b", text: "polite", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Her tone was remarkably apologetic.", options: [{ id: "a", text: "Tavrı (tonu) dikkat çekici şekilde özür dileyiciydi", correct: true }, { id: "b", text: "Kızgındı", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "İyimser bir yaklaşım.", correctAnswer: "An optimistic approach" },
            { id: 12, type: "SELECT", question: "Register of 'Hey, what's up?'", options: [{ id: "a", text: "casual / informal", correct: true }, { id: "b", text: "academic", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Academic writing avoids _____ (first) person pronouns.", options: [{ id: "a", text: "first", correct: true }, { id: "b", text: "third", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Mizahi bir hikaye.", correctAnswer: "A humorous story" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The speech was delivered in a somber tone.", options: [{ id: "a", text: "Konuşma kasvetli (ciddi) bir tonda yapıldı", correct: true }, { id: "b", text: "Konuşma neşeliydi", correct: false }] },
            { id: 16, type: "SELECT", question: "Register of 'Please be advised...'", options: [{ id: "a", text: "formal / professional", correct: true }, { id: "b", text: "slang", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "A persuasive text aims to _____ (convince) the reader.", options: [{ id: "a", text: "convince / persuade", correct: true }, { id: "b", text: "confuse", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Önyargılı bir görüş.", correctAnswer: "A biased opinion / view" },
            { id: 19, type: "SELECT", question: "Tone in: 'Wait, I think I'm lost.'", options: [{ id: "a", text: "uncertain / confused", correct: true }, { id: "b", text: "confident", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Technical manuals use a _____ (direct) tone.", options: [{ id: "a", text: "direct / instructive", correct: true }, { id: "b", text: "poetic", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Contextual Clues for Vocabulary)
            { id: 1, type: "SELECT", question: "Meaning of 'fragile' in context: 'Handle with care; it's fragile.'", options: [{ id: "a", text: "easily broken", correct: true }, { id: "b", text: "very strong", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The shop was _____ (crowd) on Saturday.", options: [{ id: "a", text: "crowded / packed", correct: true }, { id: "b", text: "empty", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bağlamdan anlamı çıkar (deduce).", correctAnswer: "Deduce the meaning from the context" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Despite the obstacles, she persevered.", options: [{ id: "a", text: "Engellere rağmen sebat etti (devam etti)", correct: true }, { id: "b", text: "Engellere takıldı", correct: false }] },
            { id: 5, type: "SELECT", question: "Defintion of 'meticulous' in: 'He is a meticulous worker.'", options: [{ id: "a", text: "very careful with details", correct: true }, { id: "b", text: "lazy", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Her _____ (tire) efforts led to success.", options: [{ id: "a", text: "tireless / constant", correct: true }, { id: "b", text: "weak", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Göz ardı edilemeyecek kadar önemli.", correctAnswer: "Too important to be ignored / overlooked" },
            { id: 8, type: "SELECT", question: "Meaning of 'ambiguous' in context:", options: [{ id: "a", text: "having more than one meaning", correct: true }, { id: "b", text: "very clear", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (accidental) broke the vase.", options: [{ id: "a", text: "accidentally", correct: true }, { id: "b", text: "intentional", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The atmosphere was tense.", options: [{ id: "a", text: "Atmosfer gergindi", correct: true }, { id: "b", text: "Hava güzeldi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bu kelime ne anlama geliyor?", correctAnswer: "What does this word mean?" },
            { id: 12, type: "SELECT", question: "Meaning of 'innovative':", options: [{ id: "a", text: "new and original", correct: true }, { id: "b", text: "old-fashioned", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The evidence was _____ (conclude).", options: [{ id: "a", text: "conclusive / direct", correct: true }, { id: "b", text: "weak", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Anlamı tahmin et (guess).", correctAnswer: "Guess the meaning" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It was an inevitable outcome.", options: [{ id: "a", text: "Kaçınılmaz bir sonuçtu", correct: true }, { id: "b", text: "Sürpriz bir sonuçtu", correct: false }] },
            { id: 16, type: "SELECT", question: "Antonym of 'vague':", options: [{ id: "a", text: "precise", correct: true }, { id: "b", text: "unclear", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He spoke with _____ (fluent).", options: [{ id: "a", text: "fluency", correct: true }, { id: "b", text: "fluent", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Mantıklı bir açıklama.", correctAnswer: "A logical explanation" },
            { id: 19, type: "SELECT", question: "Meaning of 'scarce':", options: [{ id: "a", text: "limited or hard to find", correct: true }, { id: "b", text: "plentiful", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "They made a _____ (simultaneous) decision.", options: [{ id: "a", text: "simultaneous", correct: true }, { id: "b", text: "separate", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Logical Sequence & Cohesion)
            { id: 1, type: "SELECT", question: "Which transition shows contrast?", options: [{ id: "a", text: "on the other hand", correct: true }, { id: "b", text: "furthermore", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He was late; _____ (result), he missed the start.", options: [{ id: "a", text: "consequently / therefore", correct: true }, { id: "b", text: "however", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Buna ek olarak.", correctAnswer: "In addition / Additionally / Moreover" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Firstly, we must identify the problem.", options: [{ id: "a", text: "İlk olarak, problemi tanımlamalıyız", correct: true }, { id: "b", text: "Problemi çözmeliyiz", correct: false }] },
            { id: 5, type: "SELECT", question: "Which transition summarizes?", options: [{ id: "a", text: "In short / To sum up", correct: true }, { id: "b", text: "Firstly", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "She is smart. _____ (addition), she is kind.", options: [{ id: "a", text: "Moreover / Furthermore", correct: true }, { id: "b", text: "But", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Aksine (on the contrary).", correctAnswer: "On the contrary" },
            { id: 8, type: "SELECT", question: "Transition for example:", options: [{ id: "a", text: "for instance / for example", correct: true }, { id: "b", text: "namely", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "I like fruit. _____ (specifically), apples.", options: [{ id: "a", text: "Specifically / Particularly", correct: true }, { id: "b", text: "General", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Despite his age, he is very active.", options: [{ id: "a", text: "Yaşına rağmen çok aktif", correct: true }, { id: "b", text: "Yaşlı ve aktif", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Başka bir deyişle.", correctAnswer: "In other words" },
            { id: 12, type: "SELECT", question: "Transition for emphasis:", options: [{ id: "a", text: "in fact / indeed", correct: true }, { id: "b", text: "maybe", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The car is old. _____ (consequence), it breaks often.", options: [{ id: "a", text: "Hence / Consequently", correct: true }, { id: "b", text: "Instead", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Aksi takdirde (otherwise).", correctAnswer: "Otherwise" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Alternatively, we could take the bus.", options: [{ id: "a", text: "Alternatif olarak otobüse binebiliriz", correct: true }, { id: "b", text: "Otobüsle gidiyoruz", correct: false }] },
            { id: 16, type: "SELECT", question: "Transition for concession:", options: [{ id: "a", text: "admittedly / even though", correct: true }, { id: "b", text: "already", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He worked hard. _____ (success), he won.", options: [{ id: "a", text: "As a result / Thus", correct: true }, { id: "b", text: "Before", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bu bağlamda.", correctAnswer: "In this context" },
            { id: 19, type: "SELECT", question: "Transition for sequence:", options: [{ id: "a", text: "subsequently / afterwards", correct: true }, { id: "b", text: "initially", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "It was raining; _____ (nevertheless), he went out.", options: [{ id: "a", text: "nevertheless / nonetheless", correct: true }, { id: "b", text: "so", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Summarizing & Inference)
            { id: 1, type: "SELECT", question: "To summarize means to ___.", options: [{ id: "a", text: "state the main points briefly", correct: true }, { id: "b", text: "write the whole text again", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "An inference is a _____ (guess) based on evidence.", options: [{ id: "a", text: "conclusion / deduction", correct: true }, { id: "b", text: "lie", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Ana fikri belirtin.", correctAnswer: "State the main idea" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We can infer that the character is sad.", options: [{ id: "a", text: "Karakterin üzgün olduğu sonucuna varabiliriz", correct: true }, { id: "b", text: "Karakter üzgün", correct: false }] },
            { id: 5, type: "SELECT", question: "Purpose of an introduction:", options: [{ id: "a", text: "To present the topic and main argument", correct: true }, { id: "b", text: "To end the discussion", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The text _____ (imply) that change is coming.", options: [{ id: "a", text: "implies / suggests", correct: true }, { id: "b", text: "demands", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Kısaca (briefly).", correctAnswer: "In brief / Briefly" },
            { id: 8, type: "SELECT", question: "Direct inference: 'Shadows are long' -> It's ___.", options: [{ id: "a", text: "late afternoon or early morning", correct: true }, { id: "b", text: "noon", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "A summary should be _____ (concise).", options: [{ id: "a", text: "concise / short", correct: true }, { id: "b", text: "long", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The overall conclusion was positive.", options: [{ id: "a", text: "Genel sonuç olumluydu", correct: true }, { id: "b", text: "Olumlu oldu", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Mesajı vurgulayalım.", correctAnswer: "Let's emphasize the message" },
            { id: 12, type: "SELECT", question: "Inference: 'The ground is wet' -> ___.", options: [{ id: "a", text: "It rained.", correct: true }, { id: "b", text: "It's sunny.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The author _____ (criticize) the policy.", options: [{ id: "a", text: "criticizes", correct: true }, { id: "b", text: "supports", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Görüşünüzü destekleyin.", correctAnswer: "Support your opinion" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The findings support the hypothesis.", options: [{ id: "a", text: "Bulgular hipotezi destekliyor", correct: true }, { id: "b", text: "Hipotez doğru", correct: false }] },
            { id: 16, type: "SELECT", question: "Purpose of concluding paragraph:", options: [{ id: "a", text: "To restate the main points and give a final thought", correct: true }, { id: "b", text: "To add new information", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The text is an _____ (analyze) of social trends.", options: [{ id: "a", text: "analysis", correct: true }, { id: "b", text: "analog", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Önemli detayları özetleyin.", correctAnswer: "Summarize the key details" },
            { id: 19, type: "SELECT", question: "Inference: 'He check his watch again' -> ___.", options: [{ id: "a", text: "He is in a hurry or waiting for something.", correct: true }, { id: "b", text: "He is sleeping.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (demonstrate) his skill.", options: [{ id: "a", text: "demonstrated / showed", correct: true }, { id: "b", text: "gave", correct: false }] }
        ]
    },
    217: {
        1: [ // QUIZ 1: EASY (Idiomatic Speech in Context)
            { id: 1, type: "SELECT", question: "Meaning of 'break a leg' in a theater context:", options: [{ id: "a", text: "good luck", correct: true }, { id: "b", text: "hurt yourself", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He is always _____ (beat) around the bush.", options: [{ id: "a", text: "beating", correct: true }, { id: "b", text: "hitting", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Beni yanlış anlama.", correctAnswer: "Don't get me wrong / Don't misunderstand me" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's not my cup of tea.", options: [{ id: "a", text: "Bana göre değil (sevmem)", correct: true }, { id: "b", text: "Çayım değil", correct: false }] },
            { id: 5, type: "SELECT", question: "Meaning of 'under the weather':", options: [{ id: "a", text: "feeling sick", correct: true }, { id: "b", text: "feeling cold", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Let's call it a _____ (stop working).", options: [{ id: "a", text: "day", correct: true }, { id: "b", text: "night", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Lafı ağzımdan aldın.", correctAnswer: "You took the words right out of my mouth" },
            { id: 8, type: "SELECT", question: "Meaning of 'spill the beans':", options: [{ id: "a", text: "to reveal a secret", correct: true }, { id: "b", text: "to cook", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "That's the _____ (final) straw.", options: [{ id: "a", text: "last / final", correct: true }, { id: "b", text: "only", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He's pulling your leg.", options: [{ id: "a", text: "Sana şaka yapıyor (kafa buluyor)", correct: true }, { id: "b", text: "Bacağını çekiyor", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Zaman uçup gidiyor.", correctAnswer: "Time flies" },
            { id: 12, type: "SELECT", question: "Meaning of 'piece of cake':", options: [{ id: "a", text: "very easy", correct: true }, { id: "b", text: "a small snack", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "Don't judge a book by its _____ (cover).", options: [{ id: "a", text: "cover", correct: true }, { id: "b", text: "page", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Baklayı ağzından çıkar.", correctAnswer: "Spill the beans" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We need to break the ice.", options: [{ id: "a", text: "Buzları eritmeliyiz (sohbeti başlatmalıyız)", correct: true }, { id: "b", text: "Buzu kırmalıyız", correct: false }] },
            { id: 16, type: "SELECT", question: "Meaning of 'on cloud nine':", options: [{ id: "a", text: "extreme happiness", correct: true }, { id: "b", text: "high altitude", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It cost an arm and a _____ (leg).", options: [{ id: "a", text: "leg", correct: true }, { id: "b", text: "foot", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bir taşla iki kuş.", correctAnswer: "Two birds with one stone" },
            { id: 19, type: "SELECT", question: "Meaning of 'cold feet':", options: [{ id: "a", text: "nervousness", correct: true }, { id: "b", text: "winter", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Keep your _____ (chin) up.", options: [{ id: "a", text: "chin", correct: true }, { id: "b", text: "head", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Regional Accents & Variations)
            { id: 1, type: "SELECT", question: "Which is a common US English word for 'pavement'?", options: [{ id: "a", text: "sidewalk", correct: true }, { id: "b", text: "footpath", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "In the UK, they call it a _____ (lift); in the US, an elevator.", options: [{ id: "a", text: "lift", correct: true }, { id: "b", text: "raiser", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Kamyon (US - Truck).", correctAnswer: "Truck / Lorry (UK)" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll see you at the weekend.", options: [{ id: "a", text: "Hafta sonu görüşürüz (UK style 'at the')", correct: true }, { id: "b", text: "Görüşürüz", correct: false }] },
            { id: 5, type: "SELECT", question: "Which is common UK English for 'apartment'?", options: [{ id: "a", text: "flat", correct: true }, { id: "b", text: "house", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "US: French Fries; UK: _____ (chips).", options: [{ id: "a", text: "chips", correct: true }, { id: "b", text: "fries", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Tatil (US - Vacation).", correctAnswer: "Vacation / Holiday (UK)" },
            { id: 8, type: "SELECT", question: "UK spelling of 'color':", options: [{ id: "a", text: "colour", correct: true }, { id: "b", text: "color", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "US: Subway; UK: _____ (underground).", options: [{ id: "a", text: "underground / tube", correct: true }, { id: "b", text: "subway", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Do you have a mobile phone?", options: [{ id: "a", text: "Cep telefonun var mı? (UK mobile vs US cell)", correct: true }, { id: "b", text: "Telefonun var mı?", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Eczane (UK - Pharmacy/Chemist's).", correctAnswer: "Pharmacy / Chemist's / Drugstore (US)" },
            { id: 12, type: "SELECT", question: "Meaning of 'reckon' (highly common in UK/Aus):", options: [{ id: "a", text: "to think or believe", correct: true }, { id: "b", text: "to run", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "UK: Biscuit; US: _____ (cookie).", options: [{ id: "a", text: "cookie", correct: true }, { id: "b", text: "cracker", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Futbol (US - Soccer).", correctAnswer: "Soccer / Football (UK)" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I've misplaced my jumper.", options: [{ id: "a", text: "Kazağımı (UK jumper vs US sweater) kaybettim", correct: true }, { id: "b", text: "Ceketimi kaybettim", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is a common Australian greeting?", options: [{ id: "a", text: "G'day", correct: true }, { id: "b", text: "Cheers", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "UK: Petrol; US: _____ (gas).", options: [{ id: "a", text: "gas / gasoline", correct: true }, { id: "b", text: "petrol", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Çöp kutusu (US - Trash can).", correctAnswer: "Trash can / Bin / Dustbin (UK)" },
            { id: 19, type: "SELECT", question: "Meaning of 'mate' in UK/Aus context:", options: [{ id: "a", text: "friend", correct: true }, { id: "b", text: "enemy", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "US: Trunk (car); UK: _____ (boot).", options: [{ id: "a", text: "boot", correct: true }, { id: "b", text: "trunk", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Detecting Sarcasm & Understatement)
            { id: 1, type: "SELECT", question: "Which phrase often indicates sarcasm?", options: [{ id: "a", text: "Oh, brilliant!", correct: true }, { id: "b", text: "That is interesting.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Saying 'I'm okay' after a major accident is an _____ (understatement).", options: [{ id: "a", text: "understatement", correct: true }, { id: "b", text: "exaggeration", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Harika bir fikir! (Sarcastic).", correctAnswer: "What a brilliant idea! / Great job! (ironic)" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Wow, you're early. Only two hours late.", options: [{ id: "a", text: "Vay canına, erkencisin. Sadece iki saat rötarla. (Sarcastic)", correct: true }, { id: "b", text: "Geldin", correct: false }] },
            { id: 5, type: "SELECT", question: "An understatement ___ the importance of something.", options: [{ id: "a", text: "minimizes", correct: true }, { id: "b", text: "maximizes", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "That's _____ (just) what I needed! (after a problem).", options: [{ id: "a", text: "just / exactly", correct: true }, { id: "b", text: "hardly", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bu biraz (bit) pahalı.", correctAnswer: "This is a bit expensive / slightly pricy" },
            { id: 8, type: "SELECT", question: "Irony is when the meaning is ___ of the words used.", options: [{ id: "a", text: "opposite", correct: true }, { id: "b", text: "same", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He is _____ (not) the smartest person... (Understatement).", options: [{ id: "a", text: "not exactly / not quite", correct: true }, { id: "b", text: "very", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Nice weather, isn't it? (during a storm).", options: [{ id: "a", text: "Güzel hava, değil mi? (Fırtına sırasında - Ironic)", correct: true }, { id: "b", text: "Hava kötü", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Aferin sana! (Ironic).", correctAnswer: "Well done! / Good for you! (sarcastic context)" },
            { id: 12, type: "SELECT", question: "Which is an understatement for a huge disaster?", options: [{ id: "a", text: "It's a bit of a mess.", correct: true }, { id: "b", text: "It's a total catastrophe.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I could _____ (care) less. (Sarcasm).", options: [{ id: "a", text: "couldn't / could", correct: true }, { id: "b", text: "did", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Gerçekten mi?", correctAnswer: "Really? / You don't say!" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'm sure that will work out perfectly. (said with doubt).", options: [{ id: "a", text: "Bunun mükemmel işe yarayacağından eminim (şüpheyle - Sarcastic)", correct: true }, { id: "b", text: "İşe yarayacak", correct: false }] },
            { id: 16, type: "SELECT", question: "Purpose of sarcasm:", options: [{ id: "a", text: "to mock or convey humor/contempt", correct: true }, { id: "b", text: "to be very polite", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Tell me _____ (all) about it. (said bored).", options: [{ id: "a", text: "all", correct: true }, { id: "b", text: "nothing", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Önemli değil (Understatement for major help).", correctAnswer: "It was nothing / No problem" },
            { id: 19, type: "SELECT", question: "Understatement used for politeness:", options: [{ id: "a", text: "I may have made a small mistake.", correct: true }, { id: "b", text: "I messed up everything.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "That was _____ (quite) helpful. (Sarcastic).", options: [{ id: "a", text: "quite / really", correct: true }, { id: "b", text: "hardly", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Listening for Details in Lectures)
            { id: 1, type: "SELECT", question: "Main purpose of a lecture introduction:", options: [{ id: "a", text: "to outline the main points", correct: true }, { id: "b", text: "to conclude the session", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The speaker _____ (emphasize) the importance of data.", options: [{ id: "a", text: "emphasized / stressed", correct: true }, { id: "b", text: "forgot", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Raporu özetleyin.", correctAnswer: "Summarize the report" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "In contrast to previous theories, we find that...", options: [{ id: "a", text: "Önceki teorilerin aksine şunu görüyoruz ki...", correct: true }, { id: "b", text: "Önceki teorilere göre", correct: false }] },
            { id: 5, type: "SELECT", question: "Which word signals a conclusion?", options: [{ id: "a", text: "finally / to sum up", correct: true }, { id: "b", text: "firstly", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (main) point is this.", options: [{ id: "a", text: "main / key", correct: true }, { id: "b", text: "small", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bu veriler şunu gösteriyor.", correctAnswer: "This data shows / indicates that" },
            { id: 8, type: "SELECT", question: "Listening strategy: 'Predicting' means ___.", options: [{ id: "a", text: "anticipating what the speaker will say next", correct: true }, { id: "b", text: "writing everything down", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Pay close _____ (attention) to the figures.", options: [{ id: "a", text: "attention", correct: true }, { id: "b", text: "look", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "There are two fundamental factors to consider.", options: [{ id: "a", text: "Dikkate alınması gereken iki temel faktör var", correct: true }, { id: "b", text: "Faktörler önemli", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Özellikle (particulary) dikkat edin.", correctAnswer: "Pay particular attention / especially notice" },
            { id: 12, type: "SELECT", question: "Signaling word for an example:", options: [{ id: "a", text: "for instance / for example", correct: true }, { id: "b", text: "however", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The study _____ (reveal) a significant trend.", options: [{ id: "a", text: "revealed / showed", correct: true }, { id: "b", text: "hid", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Çalışmanın sonuçları.", correctAnswer: "The results of the study" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Essentially, the process is very simple.", options: [{ id: "a", text: "Esasen süreç (işlem) çok basit", correct: true }, { id: "b", text: "Süreç zor", correct: false }] },
            { id: 16, type: "SELECT", question: "Signaling word for a contrast:", options: [{ id: "a", text: "nevertheless / despite", correct: true }, { id: "b", text: "furthermore", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (finding) were unexpected.", options: [{ id: "a", text: "findings / results", correct: true }, { id: "b", text: "starts", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bunu detaylıca açıklayacağım.", correctAnswer: "I'll explain this in detail" },
            { id: 19, type: "SELECT", question: "Key listening skill: 'Filtering' means ___.", options: [{ id: "a", text: "ignoring irrelevant information", correct: true }, { id: "b", text: "writing every single word", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The Evidence _____ (suggest) that...", options: [{ id: "a", text: "suggests / indicates", correct: true }, { id: "b", text: "lies", correct: false }] }
        ]
    },
    218: {
        1: [ // QUIZ 1: EASY (Thesis Statements & Hook Sentences)
            { id: 1, type: "SELECT", question: "What is the purpose of a thesis statement?", options: [{ id: "a", text: "to state the main argument of the essay", correct: true }, { id: "b", text: "to list all the facts", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "An effective _____ (hook) grabs the reader's attention.", options: [{ id: "a", text: "hook", correct: true }, { id: "b", text: "end", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu makalenin ana fikri şudur.", correctAnswer: "The main idea of this essay / paper is as follows" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "A thesis statement should be debatable.", options: [{ id: "a", text: "Bir tez ifadesi tartışılabilir olmalıdır", correct: true }, { id: "b", text: "Tez doğrudur", correct: false }] },
            { id: 5, type: "SELECT", question: "Where is the thesis statement usually located?", options: [{ id: "a", text: "at the end of the introduction", correct: true }, { id: "b", text: "in the conclusion only", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (intro) sets the stage for the argument.", options: [{ id: "a", text: "introduction", correct: true }, { id: "b", text: "summary", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Dikkat çekici bir giriş.", correctAnswer: "A compelling introduction / an engaging start" },
            { id: 8, type: "SELECT", question: "A 'hook' can be ___.", options: [{ id: "a", text: "a quote, a question, or a startling fact", correct: true }, { id: "b", text: "a list of references", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The thesis statement provides a _____ (map) for the essay.", options: [{ id: "a", text: "roadmap / guide", correct: true }, { id: "b", text: "finish", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Keep your thesis concise and clear.", options: [{ id: "a", text: "Tezinizi kısa ve net tutun", correct: true }, { id: "b", text: "Tez yazın", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Argümanınızı savunun.", correctAnswer: "Defend your argument" },
            { id: 12, type: "SELECT", question: "Which is a good thesis example?", options: [{ id: "a", text: "Climate change is a global problem that requires immediate international action.", correct: true }, { id: "b", text: "I like the sun.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (topic) sentence introduces the paragraph's main idea.", options: [{ id: "a", text: "topic", correct: true }, { id: "b", text: "main", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bu iddia tartışmalıdır.", correctAnswer: "This claim is controversial / debatable" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The introduction should proceed from general to specific.", options: [{ id: "a", text: "Giriş genelden özele doğru ilerlemelidir", correct: true }, { id: "b", text: "Giriş özel olmalıdır", correct: false }] },
            { id: 16, type: "SELECT", question: "A thesis statement is NOT ___.", options: [{ id: "a", text: "a simple statement of fact", correct: true }, { id: "b", text: "an opinion", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "You must _____ (state) your position clearly.", options: [{ id: "a", text: "state / declare", correct: true }, { id: "b", text: "hide", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Özet olarak (all in all).", correctAnswer: "All in all / In summary" },
            { id: 19, type: "SELECT", question: "An essay's 'hook' comes ___.", options: [{ id: "a", text: "at the very beginning", correct: true }, { id: "b", text: "in the middle", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The thesis is the _____ (core) of your essay.", options: [{ id: "a", text: "core / heart", correct: true }, { id: "b", text: "end", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Counter-arguments & Rebuttals)
            { id: 1, type: "SELECT", question: "What is a counter-argument?", options: [{ id: "a", text: "an opposing viewpoint", correct: true }, { id: "b", text: "another supporting fact", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "A _____ (rebut) addresses the counter-argument.", options: [{ id: "a", text: "rebuttal", correct: true }, { id: "b", text: "repeat", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bazıları şunu iddia edebilir (argue).", correctAnswer: "Some might argue that / Others may claim that" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It is important to acknowledge opposing views.", options: [{ id: "a", text: "Karşıt görüşleri kabul etmek önemlidir", correct: true }, { id: "b", text: "Görüşler farklıdır", correct: false }] },
            { id: 5, type: "SELECT", question: "Why include a counter-argument?", options: [{ id: "a", text: "to show that you've considered multiple perspectives", correct: true }, { id: "b", text: "to confuse the reader", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (contrast), there are valid reasons to disagree.", options: [{ id: "a", text: "In contrast / Conversely", correct: true }, { id: "b", text: "Similarly", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Buna rağmen (nevertheless).", correctAnswer: "Nevertheless / Despite this" },
            { id: 8, type: "SELECT", question: "Which word signals a rebuttal?", options: [{ id: "a", text: "However / Yet / Nonetheless", correct: true }, { id: "b", text: "Furthermore", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "While some believe X, the evidence _____ (suggest) Y.", options: [{ id: "a", text: "suggests / shows", correct: true }, { id: "b", text: "ignores", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Despite these objections, the plan is sound.", options: [{ id: "a", text: "Bu itirazlara rağmen plan sağlam (mantıklı)", correct: true }, { id: "b", text: "Plan kötü", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Buna itiraz edebiliriz.", correctAnswer: "We can object to this / This can be challenged" },
            { id: 12, type: "SELECT", question: "A good rebuttal should be ___.", options: [{ id: "a", text: "logical and evidence-based", correct: true }, { id: "b", text: "emotional and loud", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "That argument is _____ (valid) but incomplete.", options: [{ id: "a", text: "valid / sound", correct: true }, { id: "b", text: "wrong", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Aksine (on the contrary).", correctAnswer: "On the contrary" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We must consider the potential drawbacks.", options: [{ id: "a", text: "Potansiyel dezavantajları dikkate almalıyız", correct: true }, { id: "b", text: "Avantajları düşünmeliyiz", correct: false }] },
            { id: 16, type: "SELECT", question: "Rebuttal phrase:", options: [{ id: "a", text: "This fails to account for...", correct: true }, { id: "b", text: "I agree with...", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (admit), this is a complex issue.", options: [{ id: "a", text: "Admittedly", correct: true }, { id: "b", text: "Clearly", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Bu bakış açısı (perspective) yanlıştır.", correctAnswer: "This perspective is flawed / incorrect" },
            { id: 19, type: "SELECT", question: "Counter-argument marker:", options: [{ id: "a", text: "On the other hand...", correct: true }, { id: "b", text: "First of all...", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "His argument _____ (lack) scientific proof.", options: [{ id: "a", text: "lacks", correct: true }, { id: "b", text: "has", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Cohesion & Coherence)
            { id: 1, type: "SELECT", question: "Cohesion refers to ___.", options: [{ id: "a", text: "the grammatical links between sentences", correct: true }, { id: "b", text: "the overall logic of the essay", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Use _____ (transition) words to improve flow.", options: [{ id: "a", text: "transition / linking", correct: true }, { id: "b", text: "hard", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu durum şunu gösterir (demonstrate).", correctAnswer: "This demonstrates that / This shows that" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Coherence ensures that the reader can follow the logic.", options: [{ id: "a", text: "Tutarlılık (coherence), okuyucunun mantığı takip edebilmesini sağlar", correct: true }, { id: "b", text: "Mantık önemlidir", correct: false }] },
            { id: 5, type: "SELECT", question: "Which signals an additional point?", options: [{ id: "a", text: "Furthermore / Moreover", correct: true }, { id: "b", text: "Conversely", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (result), the experiment was stopped.", options: [{ id: "a", text: "Consequently / Therefore", correct: true }, { id: "b", text: "Initially", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bu bağlamda (context).", correctAnswer: "In this context" },
            { id: 8, type: "SELECT", question: "Which word signals an example?", options: [{ id: "a", text: "Particularly / Specifically", correct: true }, { id: "b", text: "Briefly", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The previous study was flawed. _____ (similarly), this one lacks data.", options: [{ id: "a", text: "Similarly / Likewise", correct: true }, { id: "b", text: "Finally", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Maintaining a consistent perspective is key to coherence.", options: [{ id: "a", text: "Tutarlı bir bakış açısını sürdürmek tutarlılığın anahtarıdır", correct: true }, { id: "b", text: "Bakış açısı anahtardır", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Önceki bölümde (section).", correctAnswer: "In the preceding section / In the previous part" },
            { id: 12, type: "SELECT", question: "Which signals a logical conclusion?", options: [{ id: "a", text: "Hence / Thus", correct: true }, { id: "b", text: "But", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (summary), we recommend the following.", options: [{ id: "a", text: "In conclusion / To summarize", correct: true }, { id: "b", text: "Firstly", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Aşağıdaki hususlar (points).", correctAnswer: "The following points / The points listed below" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Transition words prevent the text from being disjointed.", options: [{ id: "a", text: "Geçiş kelimeleri metnin kopuk olmasını engeller", correct: true }, { id: "b", text: "Kelimeler önemlidir", correct: false }] },
            { id: 16, type: "SELECT", question: "Cohesive device: 'The former' and 'The latter' refer to ___.", options: [{ id: "a", text: "previously mentioned items in order", correct: true }, { id: "b", text: "the future topics", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "It was a _____ (success) attempt.", options: [{ id: "a", text: "successful", correct: true }, { id: "b", text: "successively", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Öte yandan.", correctAnswer: "On the other hand" },
            { id: 19, type: "SELECT", question: "Which word signals a shift in topic?", options: [{ id: "a", text: "Regarding / with respect to", correct: true }, { id: "b", text: "And", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Wait until _____ (notify).", options: [{ id: "a", text: "notified / further notice", correct: true }, { id: "b", text: "note", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Citations & Academic Integrity)
            { id: 1, type: "SELECT", question: "What is plagiarism?", options: [{ id: "a", text: "using someone else's work without credit", correct: true }, { id: "b", text: "working too hard", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "You must _____ (cite) your sources.", options: [{ id: "a", text: "cite / attribute", correct: true }, { id: "b", text: "hide", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Kaynakça bölümü.", correctAnswer: "References section / Bibliography" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Proper citation avoids academic misconduct.", options: [{ id: "a", text: "Düzgün atıf yapmak akademik usulsüzlükten kaçınmayı sağlar", correct: true }, { id: "b", text: "Atıf yapın", correct: false }] },
            { id: 5, type: "SELECT", question: "What is a 'paraphrase'?", options: [{ id: "a", text: "rewriting an idea in your own words", correct: true }, { id: "b", text: "copying directly", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Use _____ (quote) marks for direct speech.", options: [{ id: "a", text: "quotation / quote", correct: true }, { id: "b", text: "mark", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Verilere göre (according to).", correctAnswer: "According to the data" },
            { id: 8, type: "SELECT", question: "Common citation style:", options: [{ id: "a", text: "APA / MLA", correct: true }, { id: "b", text: "PDF", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (source) of the quote is Shakespeare.", options: [{ id: "a", text: "source", correct: true }, { id: "b", text: "start", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Always cross-reference your findings.", options: [{ id: "a", text: "Bulgularınızı daima çapraz kontrol edin (atıf yapın)", correct: true }, { id: "b", text: "Bulgulara bakın", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Yazar şöyle demiştir (state).", correctAnswer: "The author states that / as the author claims" },
            { id: 12, type: "SELECT", question: "Definition of 'credible source':", options: [{ id: "a", text: "trustworthy and reliable", correct: true }, { id: "b", text: "anyone on the internet", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It was a _____ (peer) reviewed journal.", options: [{ id: "a", text: "peer-reviewed", correct: true }, { id: "b", text: "best-reviewed", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Doğrudan alıntı.", correctAnswer: "Direct quotation / citation" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The bibliography lists all consulted works.", options: [{ id: "a", text: "Kaynakça, danışılan tüm eserleri listeler", correct: true }, { id: "b", text: "Eserleri oku", correct: false }] },
            { id: 16, type: "SELECT", question: "When to cite?", options: [{ id: "a", text: "whenever you use an external idea", correct: true }, { id: "b", text: "only for direct quotes", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "She _____ (paraphrase) the entire chapter.", options: [{ id: "a", text: "paraphrased", correct: true }, { id: "b", text: "copied", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Asıl yazar.", correctAnswer: "The original author" },
            { id: 19, type: "SELECT", question: "Integrity means ___.", options: [{ id: "a", text: "honesty and moral principles", correct: true }, { id: "b", text: "intelligence", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The study _____ (document) the decline.", options: [{ id: "a", text: "documented / documents", correct: true }, { id: "b", text: "said", correct: false }] }
        ]
    },
    219: {
        1: [ // QUIZ 1: EASY (Email Etiquette)
            { id: 1, type: "SELECT", question: "A formal way to start an email to someone you don't know:", options: [{ id: "a", text: "Dear Sir/Madam", correct: true }, { id: "b", text: "Hey there", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I am writing with _____ (regard) to your recent inquiry.", options: [{ id: "a", text: "regard", correct: true }, { id: "b", text: "thanks", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Lütfen ekteki dosyayı bulun.", correctAnswer: "Please find the attached file / Please find attached" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I look forward to hearing from you.", options: [{ id: "a", text: "Sizden haber bekliyorum (iletişime geçmenizi bekliyorum)", correct: true }, { id: "b", text: "Sizi bekliyorum", correct: false }] },
            { id: 5, type: "SELECT", question: "A professional way to end a formal email:", options: [{ id: "a", text: "Yours sincerely / Yours faithfully", correct: true }, { id: "b", text: "Cheers", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Please let me know if you _____ (require) any further information.", options: [{ id: "a", text: "require / need", correct: true }, { id: "b", text: "ask", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "İlginiz için teşekkürler.", correctAnswer: "Thank you for your interest / Thank you for your attention" },
            { id: 8, type: "SELECT", question: "Which is more professional for an 'out of office' reply?", options: [{ id: "a", text: "I will be out of the office until Monday.", correct: true }, { id: "b", text: "I'm not here. Bye.", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Apologies for the _____ (delay) in responding.", options: [{ id: "a", text: "delay", correct: true }, { id: "b", text: "late", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'm following up on our meeting from yesterday.", options: [{ id: "a", text: "Dünkü toplantımızla ilgili takip (takip e-postası) yapıyorum", correct: true }, { id: "b", text: "Toplantı bitti", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Müsait olduğunuzda.", correctAnswer: "At your earliest convenience" },
            { id: 12, type: "SELECT", question: "What does 'cc' mean in an email context?", options: [{ id: "a", text: "carbon copy (sending a copy to others)", correct: true }, { id: "b", text: "cancel computer", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "I would appreciate a _____ (prompt) reply.", options: [{ id: "a", text: "prompt / quick", correct: true }, { id: "b", text: "slow", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bir toplantı ayarlayalım.", correctAnswer: "Let's schedule a meeting / Let's set up a meeting" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The deadline for the proposal is Friday.", options: [{ id: "a", text: "Teklif için son tarih (deadline) Cuma günü", correct: true }, { id: "b", text: "Teklif Cuma günü", correct: false }] },
            { id: 16, type: "SELECT", question: "Register of 'Best regards':", options: [{ id: "a", text: "semi-formal / professional", correct: true }, { id: "b", text: "very informal", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I am writing to _____ (confirm) our appointment.", options: [{ id: "a", text: "confirm", correct: true }, { id: "b", text: "think", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Gerektiğinde.", correctAnswer: "As required / when necessary" },
            { id: 19, type: "SELECT", question: "Which is better for a business email subject line?", options: [{ id: "a", text: "Project Update - April 2024", correct: true }, { id: "b", text: "Question", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Thank you for your _____ (assist).", options: [{ id: "a", text: "assistance / help", correct: true }, { id: "b", text: "assist", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Negotiating & Persuading)
            { id: 1, type: "SELECT", question: "Meaning of 'finding common ground':", options: [{ id: "a", text: "reaching an agreement on shared interests", correct: true }, { id: "b", text: "finding a place to sit", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I am open to _____ (compromise).", options: [{ id: "a", text: "compromise", correct: true }, { id: "b", text: "fight", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Bu teklif çok cazip.", correctAnswer: "This offer is very tempting / attractive" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We need to weigh the pros and cons.", options: [{ id: "a", text: "Artıları ve eksileri tartmalıyız (değerlendirmeliyiz)", correct: true }, { id: "b", text: "Plan iyi", correct: false }] },
            { id: 5, type: "SELECT", question: "Which phrase initiates a negotiation?", options: [{ id: "a", text: "What if we were to...", correct: true }, { id: "b", text: "No, thanks.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "That's a _____ (benefit) deal for both parties.", options: [{ id: "a", text: "beneficial / win-win", correct: true }, { id: "b", text: "bad", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Aynı fikirdeyiz (on the same page).", correctAnswer: "We are on the same page / We share the same view" },
            { id: 8, type: "SELECT", question: "Meaning of 'leverage':", options: [{ id: "a", text: "strategic advantage", correct: true }, { id: "b", text: "a heavy weight", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Let's touch _____ (base) later.", options: [{ id: "a", text: "base", correct: true }, { id: "b", text: "ground", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The bottom line is that we need more time.", options: [{ id: "a", text: "Sonuç (asıl nokta) şu ki, daha fazla zamana ihtiyacımız var", correct: true }, { id: "b", text: "Zamanımız var", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Bir anlașmaya vardık (reach agreement).", correctAnswer: "We have reached an agreement" },
            { id: 12, type: "SELECT", question: "Which word means 'to convince'?", options: [{ id: "a", text: "persuade", correct: true }, { id: "b", text: "order", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "This proposal is _____ (negotiable).", options: [{ id: "a", text: "negotiable", correct: true }, { id: "b", text: "static", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Önerinizi dikkate alacağız.", correctAnswer: "We will take your suggestion into consideration" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'm afraid I can't go any lower on the price.", options: [{ id: "a", text: "Korkarım fiyatta daha aşağı inemem", correct: true }, { id: "b", text: "Fiyat düştü", correct: false }] },
            { id: 16, type: "SELECT", question: "What is a 'deadlock' in negotiation?", options: [{ id: "a", text: "a situation where no progress can be made", correct: true }, { id: "b", text: "a very fast deal", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He _____ (persuade) me to join.", options: [{ id: "a", text: "persuaded / convinced", correct: true }, { id: "b", text: "asked", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Uzun vadede (in the long run).", correctAnswer: "In the long run / over time" },
            { id: 19, type: "SELECT", question: "Conflict resolution phrase:", options: [{ id: "a", text: "Let's explore other options.", correct: true }, { id: "b", text: "This is my way or the highway.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The meeting ended on a _____ (positive) note.", options: [{ id: "a", text: "positive", correct: true }, { id: "b", text: "bad", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Presenting Data & Reports)
            { id: 1, type: "SELECT", question: "Purpose of an executive summary:", options: [{ id: "a", text: "to provide a brief overview of a report", correct: true }, { id: "b", text: "to list all mathematical calculations", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The chart _____ (illustrate) the growth.", options: [{ id: "a", text: "illustrates / shows", correct: true }, { id: "b", text: "draws", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Veriler şunu gösteriyor.", correctAnswer: "The data shows / indicates / suggests that" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "There was a sharp increase in sales.", options: [{ id: "a", text: "Satışlarda keskin bir artış oldu", correct: true }, { id: "b", text: "Satışlar arttı", correct: false }] },
            { id: 5, type: "SELECT", question: "Which graph shows changes over time?", options: [{ id: "a", text: "line graph", correct: true }, { id: "b", text: "pie chart", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "As you can _____ (see) from the table...", options: [{ id: "a", text: "see / observe", correct: true }, { id: "b", text: "look", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Aşağıdaki rakamlar (figures).", correctAnswer: "The following figures / the numbers below" },
            { id: 8, type: "SELECT", question: "Which phrase leads into a conclusion?", options: [{ id: "a", text: "To wrap up... / In summary...", correct: true }, { id: "b", text: "Firstly...", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Sales _____ (plummet) last month. (decreased rapidly).", options: [{ id: "a", text: "plummeted / dropped", correct: true }, { id: "b", text: "rose", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The findings are consistent with our expectations.", options: [{ id: "a", text: "Bulgular beklentilerimizle tutarlı", correct: true }, { id: "b", text: "Bulgular iyi", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Performanstaki düșüș.", correctAnswer: "The decline in performance / decrease in quality" },
            { id: 12, type: "SELECT", question: "Meaning of 'statistically significant':", options: [{ id: "a", text: "not likely due to chance", correct: true }, { id: "b", text: "very large numbers", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (majority) of respondents agreed.", options: [{ id: "a", text: "majority", correct: true }, { id: "b", text: "major", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bu eğilim (trend) devam ediyor.", correctAnswer: "This trend is continuing / ongoing" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Overall, the project was a success.", options: [{ id: "a", text: "Genel olarak proje bir bașarıydı", correct: true }, { id: "b", text: "Proje bitti", correct: false }] },
            { id: 16, type: "SELECT", question: "Definition of 'benchmark':", options: [{ id: "a", text: "a standard for comparison", correct: true }, { id: "b", text: "a type of chair", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "We need to _____ (analyze) the results.", options: [{ id: "a", text: "analyze", correct: true }, { id: "b", text: "analyzing", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Yıllık rapor (annual).", correctAnswer: "Annual report" },
            { id: 19, type: "SELECT", question: "Presentation tip:", options: [{ id: "a", text: "Use clear visuals and keep text minimal.", correct: true }, { id: "b", text: "Read every word from the slides.", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "This _____ (imply) that we need a change.", options: [{ id: "a", text: "implies / suggests", correct: true }, { id: "b", text: "says", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Job Interviews & Prof. Vocab)
            { id: 1, type: "SELECT", question: "Common interview question: 'What are your strengths?'", options: [{ id: "a", text: "I'm a good team player and problem solver.", correct: true }, { id: "b", text: "I like coffee.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "He has many _____ (transfer) skills.", options: [{ id: "a", text: "transferable", correct: true }, { id: "b", text: "giving", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Özgeçmișinizi (CV) gönderin.", correctAnswer: "Send your CV / resumé" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Tell me about a time you handled conflict.", options: [{ id: "a", text: "Bana çatıșmayı yönettiğiniz (hallettiğiniz) bir zamandan bahsedin", correct: true }, { id: "b", text: "Çatıșma kötü", correct: false }] },
            { id: 5, type: "SELECT", question: "What is a 'track record'?", options: [{ id: "a", text: "past performance history", correct: true }, { id: "b", text: "a music album", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "I am _____ (look) for a new challenge.", options: [{ id: "a", text: "looking", correct: true }, { id: "b", text: "seeking", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Bașvurunuz için teșekkürler.", correctAnswer: "Thank you for your application" },
            { id: 8, type: "SELECT", question: "What does 'hard skills' refer to?", options: [{ id: "a", text: "technical abilities", correct: true }, { id: "b", text: "personality traits", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "He is very _____ (ambition).", options: [{ id: "a", text: "ambitious", correct: true }, { id: "b", text: "ambition", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "We will be in touch shortly.", options: [{ id: "a", text: "Kısa süre içinde iletișime geçeceğiz", correct: true }, { id: "b", text: "Görüșürüz", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Sorumluluklarımı biliyorum.", correctAnswer: "I know my responsibilities / duties" },
            { id: 12, type: "SELECT", question: "Meaning of 'proactive':", options: [{ id: "a", text: "taking action before it's needed", correct: true }, { id: "b", text: "lazy", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "She is _____ (qualified) for the role.", options: [{ id: "a", text: "qualified", correct: true }, { id: "b", text: "quality", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Ekibimize hoș geldiniz.", correctAnswer: "Welcome to our team" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Your background in marketing is impressive.", options: [{ id: "a", text: "Pazarlama konusundaki geçmișiniz etkileyici", correct: true }, { id: "b", text: "Pazarlama iyidir", correct: false }] },
            { id: 16, type: "SELECT", question: "What is 'networking'?", options: [{ id: "a", text: "building professional relationships", correct: true }, { id: "b", text: "fixing a computer", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "The role _____ (require) travel.", options: [{ id: "a", text: "requires / involves", correct: true }, { id: "b", text: "wants", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Esnek çalıșma saatleri.", correctAnswer: "Flexible working hours / shift" },
            { id: 19, type: "SELECT", question: "Definition of 'outsourcing':", options: [{ id: "a", text: "hiring external sources for tasks", correct: true }, { id: "b", text: "buying food", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Thank you for the _____ (opportune).", options: [{ id: "a", text: "opportunity", correct: true }, { id: "b", text: "hope", correct: false }] }
        ]
    },
    220: {
        1: [ // QUIZ 1: EASY (Grammar Milestone Review)
            { id: 1, type: "SELECT", question: "Which is the subjunctive form?", options: [{ id: "a", text: "I suggest he go.", correct: true }, { id: "b", text: "I suggest he goes.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "Rarely _____ (have) I seen such a beautiful sight. (Inversion).", options: [{ id: "a", text: "have", correct: true }, { id: "b", text: "I have", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Gitseydim (If I had gone).", correctAnswer: "If I had gone" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Little did he know about the surprise.", options: [{ id: "a", text: "Sürpriz hakkında çok az şey biliyordu (hiç bilmiyordu)", correct: true }, { id: "b", text: "Sürprizi biliyordu", correct: false }] },
            { id: 5, type: "SELECT", question: "Which shows mixed conditional?", options: [{ id: "a", text: "If I had studied, I would be happy now.", correct: true }, { id: "b", text: "If I study, I will pass.", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "Had I _____ (know), I wouldn't have come.", options: [{ id: "a", text: "known", correct: true }, { id: "b", text: "knew", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Yorulmuş olmalı (must have been).", correctAnswer: "He must have been tired" },
            { id: 8, type: "SELECT", question: "Passive form of 'They built the house':", options: [{ id: "a", text: "The house was built.", correct: true }, { id: "b", text: "The house built.", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "No sooner had he left _____ (than) it started raining.", options: [{ id: "a", text: "than", correct: true }, { id: "b", text: "when", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'd rather you didn't tell him.", options: [{ id: "a", text: "Ona söylememeni tercih ederim", correct: true }, { id: "b", text: "Ona söyle", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Keşke burada olsaydı.", correctAnswer: "I wish he were here / If only he were here" },
            { id: 12, type: "SELECT", question: "Relative clause: 'The man, ___ I met, was nice.'", options: [{ id: "a", text: "whom / who", correct: true }, { id: "b", text: "which", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "It is essential that he _____ (arrive) on time.", options: [{ id: "a", text: "arrive", correct: true }, { id: "b", text: "arrives", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bunu yapmış olamam.", correctAnswer: "I couldn't have done that" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Neither of them was invited.", options: [{ id: "a", text: "İkisi de davet edilmedi", correct: true }, { id: "b", text: "Biri davet edildi", correct: false }] },
            { id: 16, type: "SELECT", question: "Which is more formal?", options: [{ id: "a", text: "Should you need help...", correct: true }, { id: "b", text: "If you need help...", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "Not only is he smart, _____ (but) he is also kind.", options: [{ id: "a", text: "but", correct: true }, { id: "b", text: "and", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Onu yapmasını sağladım (have sbd do).", correctAnswer: "I had him do it / I got him to do it" },
            { id: 19, type: "SELECT", question: "Causative: 'I had my car ___.'", options: [{ id: "a", text: "fixed / repaired", correct: true }, { id: "b", text: "fix", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "By next year, I _____ (finish) my study.", options: [{ id: "a", text: "will have finished", correct: true }, { id: "b", text: "finish", correct: false }] }
        ],
        2: [ // QUIZ 2: MEDIUM (Vocab & Idioms Milestone Review)
            { id: 1, type: "SELECT", question: "Meaning of 'cut to the chase':", options: [{ id: "a", text: "get to the point", correct: true }, { id: "b", text: "run away", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "The situation was _____ (ambiguous). (not clear).", options: [{ id: "a", text: "ambiguous", correct: true }, { id: "b", text: "vivid", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Başarılar (break a leg).", correctAnswer: "Break a leg / Good luck" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "He is down to earth.", options: [{ id: "a", text: "O gerçekçidir (alçakgönüllüdür)", correct: true }, { id: "b", text: "O yerde", correct: false }] },
            { id: 5, type: "SELECT", question: "Antonym of 'generous':", options: [{ id: "a", text: "stingy / mean", correct: true }, { id: "b", text: "kind", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We need to _____ (address) the issue.", options: [{ id: "a", text: "address / handle", correct: true }, { id: "b", text: "hide", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Olağanüstü bir başarı.", correctAnswer: "An extraordinary achievement / success" },
            { id: 8, type: "SELECT", question: "Meaning of 'burn the midnight oil':", options: [{ id: "a", text: "work late at night", correct: true }, { id: "b", text: "cook at night", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "His efforts were _____ (vain). (useless).", options: [{ id: "a", text: "in vain", correct: true }, { id: "b", text: "good", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It's a long shot, but let's try.", options: [{ id: "a", text: "Düşük bir ihtimal ama deneyelim", correct: true }, { id: "b", text: "Uzun bir yol", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Görünüşe göre (apparently).", correctAnswer: "Apparently / Seemingly" },
            { id: 12, type: "SELECT", question: "Collocation: '___ a promise'", options: [{ id: "a", text: "keep / make / break", correct: true }, { id: "b", text: "do", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The _____ (majority) of people like it.", options: [{ id: "a", text: "majority", correct: true }, { id: "b", text: "major", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Hayal kırıklığı.", correctAnswer: "Disappointment / Frustration" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Don't jump to conclusions.", options: [{ id: "a", text: "Hemen sonuca varma (yargılama)", correct: true }, { id: "b", text: "Zıplama", correct: false }] },
            { id: 16, type: "SELECT", question: "Which means 'to tolerate'?", options: [{ id: "a", text: "put up with", correct: true }, { id: "b", text: "put down", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "He passed with flying _____ (color).", options: [{ id: "a", text: "colors / colours", correct: true }, { id: "b", text: "lights", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Kaçınılmaz (inevitable).", correctAnswer: "Inevitable / Unavoidable" },
            { id: 19, type: "SELECT", question: "Meaning of 'vague':", options: [{ id: "a", text: "not clear or definite", correct: true }, { id: "b", text: "very sharp", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Take it with a grain of _____ (salt).", options: [{ id: "a", text: "salt", correct: true }, { id: "b", text: "pepper", correct: false }] }
        ],
        3: [ // QUIZ 3: HARD (Reading & Style Milestone Review)
            { id: 1, type: "SELECT", question: "Which shows a critical tone?", options: [{ id: "a", text: "The approach is fundamentally flawed.", correct: true }, { id: "b", text: "It is a nice idea.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (contrast), the data suggests otherwise.", options: [{ id: "a", text: "However / On the contrary", correct: true }, { id: "b", text: "Similarly", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Buna ek olarak.", correctAnswer: "Additionally / In addition / Moreover" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "In light of recent events, we must act.", options: [{ id: "a", text: "Son olayların ışığında harekete geçmeliyiz", correct: true }, { id: "b", text: "Olaylar ışıklı", correct: false }] },
            { id: 5, type: "SELECT", question: "What is an em dash (—) used for?", options: [{ id: "a", text: "emphasis or interruption", correct: true }, { id: "b", text: "hyphenating words", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "The study _____ (demonstrate) clear growth.", options: [{ id: "a", text: "demonstrated / showed", correct: true }, { id: "b", text: "said", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Özetle.", correctAnswer: "In summary / To conclude / To sum up" },
            { id: 8, type: "SELECT", question: "Which is a more formal register?", options: [{ id: "a", text: "Furthermore", correct: true }, { id: "b", text: "And also", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "We must consider the _____ (drawback).", options: [{ id: "a", text: "drawbacks / disadvantages", correct: true }, { id: "b", text: "backs", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The findings support the initial hypothesis.", options: [{ id: "a", text: "Bulgular ilk hipotezi destekliyor", correct: true }, { id: "b", text: "Hipotez doğru", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Mesajı vurgulayalım.", correctAnswer: "Let's emphasize the message" },
            { id: 12, type: "SELECT", question: "Which is used for a list introductory phrase?", options: [{ id: "a", text: "Colon (:)", correct: true }, { id: "b", text: "Comma", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "_____ (admit), this is a difficult task.", options: [{ id: "a", text: "Admittedly", correct: true }, { id: "b", text: "Surely", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Bu bağlamda.", correctAnswer: "In this context" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "It goes without saying that health is important.", options: [{ id: "a", text: "Sağlığın önemli olduğunu söylemeye gerek bile yok (açıktır)", correct: true }, { id: "b", text: "Sağlık önemli", correct: false }] },
            { id: 16, type: "SELECT", question: "Substitution: 'Do you think it will rain?' 'I hope ___.'", options: [{ id: "a", text: "not / so", correct: true }, { id: "b", text: "it", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I visited Berlin, Germany _____ Paris, France.", options: [{ id: "a", text: "; (semicolon)", correct: true }, { id: "b", text: ",", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "Göz ardı edilemez.", correctAnswer: "It cannot be ignored / overlooked" },
            { id: 19, type: "SELECT", question: "Which punctuation mark is used for a sudden thought?", options: [{ id: "a", text: "Dash / Parentheses", correct: true }, { id: "b", text: "Full stop", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "The text _____ (imply) a hidden message.", options: [{ id: "a", text: "implies / suggests", correct: true }, { id: "b", text: "shows", correct: false }] }
        ],
        4: [ // QUIZ 4: EXPERT (Functional & Milestone Review)
            { id: 1, type: "SELECT", question: "Requesting information formally:", options: [{ id: "a", text: "I was wondering if you could provide...", correct: true }, { id: "b", text: "Give me the info.", correct: false }] },
            { id: 2, type: "FILL_BLANK", question: "Doldur:", sentence: "I _____ (apology) for any inconvenience caused.", options: [{ id: "a", text: "apologize", correct: true }, { id: "b", text: "sorry", correct: false }] },
            { id: 3, type: "TRANSLATE", question: "Çevir:", hint: "Sizden haber bekliyorum.", correctAnswer: "I look forward to hearing from you" },
            { id: 4, type: "LISTENING", question: "Duyduğunu seç:", audioText: "Should you have any questions, feel free to ask.", options: [{ id: "a", text: "Herhangi bir sorunuz olursa çekinmeden sorun", correct: true }, { id: "b", text: "Soru sormayın", correct: false }] },
            { id: 5, type: "SELECT", question: "Negotiation: 'What if we were to ___?'", options: [{ id: "a", text: "increase the budget", correct: true }, { id: "b", text: "sleeping now", correct: false }] },
            { id: 6, type: "FILL_BLANK", question: "Doldur:", sentence: "We need to find common _____ (agree).", options: [{ id: "a", text: "ground", correct: true }, { id: "b", text: "space", correct: false }] },
            { id: 7, type: "TRANSLATE", question: "Çevir:", hint: "Anlaşmaya vardık.", correctAnswer: "We have reached an agreement / We struck a deal" },
            { id: 8, type: "SELECT", question: "Professional sign-off:", options: [{ id: "a", text: "Best regards / Sincerely", correct: true }, { id: "b", text: "Bye bye", correct: false }] },
            { id: 9, type: "FILL_BLANK", question: "Doldur:", sentence: "Please find the _____ (attach) file.", options: [{ id: "a", text: "attached", correct: true }, { id: "b", text: "attach", correct: false }] },
            { id: 10, type: "LISTENING", question: "Duyduğunu seç:", audioText: "I'll get back to you as soon as possible.", options: [{ id: "a", text: "Mümkün olan en kısa sürede size geri döneceğim", correct: true }, { id: "b", text: "Bekle", correct: false }] },
            { id: 11, type: "TRANSLATE", question: "Çevir:", hint: "Müsait olduğunuzda.", correctAnswer: "At your earliest convenience" },
            { id: 12, type: "SELECT", question: "Job interview: 'Why should we hire you?'", options: [{ id: "a", text: "I have the relevant experience and skills.", correct: true }, { id: "b", text: "I don't know.", correct: false }] },
            { id: 13, type: "FILL_BLANK", question: "Doldur:", sentence: "The role _____ (involve) some travel.", options: [{ id: "a", text: "involves / requires", correct: true }, { id: "b", text: "needs", correct: false }] },
            { id: 14, type: "TRANSLATE", question: "Çevir:", hint: "Ekibimize katılın.", correctAnswer: "Join our team" },
            { id: 15, type: "LISTENING", question: "Duyduğunu seç:", audioText: "The bottom line is that we need to cut costs.", options: [{ id: "a", text: "Sonuç (asıl nokta) şu ki, maliyetleri düşürmeliyiz", correct: true }, { id: "b", text: "Harika iş", correct: false }] },
            { id: 16, type: "SELECT", question: "Meaning of 'proactive':", options: [{ id: "a", text: "taking initiative", correct: true }, { id: "b", text: "reactive", correct: false }] },
            { id: 17, type: "FILL_BLANK", question: "Doldur:", sentence: "I appreciate your _____ (assist).", options: [{ id: "a", text: "assistance / help", correct: true }, { id: "b", text: "look", correct: false }] },
            { id: 18, type: "TRANSLATE", question: "Çevir:", hint: "İşbirliğiniz için teşekkürler.", correctAnswer: "Thank you for your cooperation" },
            { id: 19, type: "SELECT", question: "Register of 'Promptly':", options: [{ id: "a", text: "formal (meaning quickly)", correct: true }, { id: "b", text: "slang", correct: false }] },
            { id: 20, type: "FILL_BLANK", question: "Doldur:", sentence: "Best of _____ (luck) with your project.", options: [{ id: "a", text: "luck", correct: true }, { id: "b", text: "life", correct: false }] }
        ]
    }
};
